// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module bnn_bnn_Pipeline_pack_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        l1_bits_reload,
        l1_bits_16_reload,
        l1_bits_32_reload,
        l1_bits_48_reload,
        l1_bits_64_reload,
        l1_bits_80_reload,
        l1_bits_96_reload,
        l1_bits_112_reload,
        l1_bits_1_reload,
        l1_bits_17_reload,
        l1_bits_33_reload,
        l1_bits_49_reload,
        l1_bits_65_reload,
        l1_bits_81_reload,
        l1_bits_97_reload,
        l1_bits_113_reload,
        l1_bits_2_reload,
        l1_bits_18_reload,
        l1_bits_34_reload,
        l1_bits_50_reload,
        l1_bits_66_reload,
        l1_bits_82_reload,
        l1_bits_98_reload,
        l1_bits_114_reload,
        l1_bits_3_reload,
        l1_bits_19_reload,
        l1_bits_35_reload,
        l1_bits_51_reload,
        l1_bits_67_reload,
        l1_bits_83_reload,
        l1_bits_99_reload,
        l1_bits_115_reload,
        l1_bits_4_reload,
        l1_bits_20_reload,
        l1_bits_36_reload,
        l1_bits_52_reload,
        l1_bits_68_reload,
        l1_bits_84_reload,
        l1_bits_100_reload,
        l1_bits_116_reload,
        l1_bits_5_reload,
        l1_bits_21_reload,
        l1_bits_37_reload,
        l1_bits_53_reload,
        l1_bits_69_reload,
        l1_bits_85_reload,
        l1_bits_101_reload,
        l1_bits_117_reload,
        l1_bits_6_reload,
        l1_bits_22_reload,
        l1_bits_38_reload,
        l1_bits_54_reload,
        l1_bits_70_reload,
        l1_bits_86_reload,
        l1_bits_102_reload,
        l1_bits_118_reload,
        l1_bits_7_reload,
        l1_bits_23_reload,
        l1_bits_39_reload,
        l1_bits_55_reload,
        l1_bits_71_reload,
        l1_bits_87_reload,
        l1_bits_103_reload,
        l1_bits_119_reload,
        l1_bits_8_reload,
        l1_bits_24_reload,
        l1_bits_40_reload,
        l1_bits_56_reload,
        l1_bits_72_reload,
        l1_bits_88_reload,
        l1_bits_104_reload,
        l1_bits_120_reload,
        l1_bits_9_reload,
        l1_bits_25_reload,
        l1_bits_41_reload,
        l1_bits_57_reload,
        l1_bits_73_reload,
        l1_bits_89_reload,
        l1_bits_105_reload,
        l1_bits_121_reload,
        l1_bits_10_reload,
        l1_bits_26_reload,
        l1_bits_42_reload,
        l1_bits_58_reload,
        l1_bits_74_reload,
        l1_bits_90_reload,
        l1_bits_106_reload,
        l1_bits_122_reload,
        l1_bits_11_reload,
        l1_bits_27_reload,
        l1_bits_43_reload,
        l1_bits_59_reload,
        l1_bits_75_reload,
        l1_bits_91_reload,
        l1_bits_107_reload,
        l1_bits_123_reload,
        l1_bits_12_reload,
        l1_bits_28_reload,
        l1_bits_44_reload,
        l1_bits_60_reload,
        l1_bits_76_reload,
        l1_bits_92_reload,
        l1_bits_108_reload,
        l1_bits_124_reload,
        l1_bits_13_reload,
        l1_bits_29_reload,
        l1_bits_45_reload,
        l1_bits_61_reload,
        l1_bits_77_reload,
        l1_bits_93_reload,
        l1_bits_109_reload,
        l1_bits_125_reload,
        l1_bits_14_reload,
        l1_bits_30_reload,
        l1_bits_46_reload,
        l1_bits_62_reload,
        l1_bits_78_reload,
        l1_bits_94_reload,
        l1_bits_110_reload,
        l1_bits_126_reload,
        l1_bits_15_reload,
        l1_bits_31_reload,
        l1_bits_47_reload,
        l1_bits_63_reload,
        l1_bits_79_reload,
        l1_bits_95_reload,
        l1_bits_111_reload,
        l1_bits_127_reload,
        p_0_0282_7102_out,
        p_0_0282_7102_out_ap_vld,
        p_0_0282_6100_out,
        p_0_0282_6100_out_ap_vld,
        p_0_0282_598_out,
        p_0_0282_598_out_ap_vld,
        p_0_0282_496_out,
        p_0_0282_496_out_ap_vld,
        p_0_0282_394_out,
        p_0_0282_394_out_ap_vld,
        p_0_0282_292_out,
        p_0_0282_292_out_ap_vld,
        p_0_0282_190_out,
        p_0_0282_190_out_ap_vld,
        p_0_028288_out,
        p_0_028288_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [0:0] l1_bits_reload;
input  [0:0] l1_bits_16_reload;
input  [0:0] l1_bits_32_reload;
input  [0:0] l1_bits_48_reload;
input  [0:0] l1_bits_64_reload;
input  [0:0] l1_bits_80_reload;
input  [0:0] l1_bits_96_reload;
input  [0:0] l1_bits_112_reload;
input  [0:0] l1_bits_1_reload;
input  [0:0] l1_bits_17_reload;
input  [0:0] l1_bits_33_reload;
input  [0:0] l1_bits_49_reload;
input  [0:0] l1_bits_65_reload;
input  [0:0] l1_bits_81_reload;
input  [0:0] l1_bits_97_reload;
input  [0:0] l1_bits_113_reload;
input  [0:0] l1_bits_2_reload;
input  [0:0] l1_bits_18_reload;
input  [0:0] l1_bits_34_reload;
input  [0:0] l1_bits_50_reload;
input  [0:0] l1_bits_66_reload;
input  [0:0] l1_bits_82_reload;
input  [0:0] l1_bits_98_reload;
input  [0:0] l1_bits_114_reload;
input  [0:0] l1_bits_3_reload;
input  [0:0] l1_bits_19_reload;
input  [0:0] l1_bits_35_reload;
input  [0:0] l1_bits_51_reload;
input  [0:0] l1_bits_67_reload;
input  [0:0] l1_bits_83_reload;
input  [0:0] l1_bits_99_reload;
input  [0:0] l1_bits_115_reload;
input  [0:0] l1_bits_4_reload;
input  [0:0] l1_bits_20_reload;
input  [0:0] l1_bits_36_reload;
input  [0:0] l1_bits_52_reload;
input  [0:0] l1_bits_68_reload;
input  [0:0] l1_bits_84_reload;
input  [0:0] l1_bits_100_reload;
input  [0:0] l1_bits_116_reload;
input  [0:0] l1_bits_5_reload;
input  [0:0] l1_bits_21_reload;
input  [0:0] l1_bits_37_reload;
input  [0:0] l1_bits_53_reload;
input  [0:0] l1_bits_69_reload;
input  [0:0] l1_bits_85_reload;
input  [0:0] l1_bits_101_reload;
input  [0:0] l1_bits_117_reload;
input  [0:0] l1_bits_6_reload;
input  [0:0] l1_bits_22_reload;
input  [0:0] l1_bits_38_reload;
input  [0:0] l1_bits_54_reload;
input  [0:0] l1_bits_70_reload;
input  [0:0] l1_bits_86_reload;
input  [0:0] l1_bits_102_reload;
input  [0:0] l1_bits_118_reload;
input  [0:0] l1_bits_7_reload;
input  [0:0] l1_bits_23_reload;
input  [0:0] l1_bits_39_reload;
input  [0:0] l1_bits_55_reload;
input  [0:0] l1_bits_71_reload;
input  [0:0] l1_bits_87_reload;
input  [0:0] l1_bits_103_reload;
input  [0:0] l1_bits_119_reload;
input  [0:0] l1_bits_8_reload;
input  [0:0] l1_bits_24_reload;
input  [0:0] l1_bits_40_reload;
input  [0:0] l1_bits_56_reload;
input  [0:0] l1_bits_72_reload;
input  [0:0] l1_bits_88_reload;
input  [0:0] l1_bits_104_reload;
input  [0:0] l1_bits_120_reload;
input  [0:0] l1_bits_9_reload;
input  [0:0] l1_bits_25_reload;
input  [0:0] l1_bits_41_reload;
input  [0:0] l1_bits_57_reload;
input  [0:0] l1_bits_73_reload;
input  [0:0] l1_bits_89_reload;
input  [0:0] l1_bits_105_reload;
input  [0:0] l1_bits_121_reload;
input  [0:0] l1_bits_10_reload;
input  [0:0] l1_bits_26_reload;
input  [0:0] l1_bits_42_reload;
input  [0:0] l1_bits_58_reload;
input  [0:0] l1_bits_74_reload;
input  [0:0] l1_bits_90_reload;
input  [0:0] l1_bits_106_reload;
input  [0:0] l1_bits_122_reload;
input  [0:0] l1_bits_11_reload;
input  [0:0] l1_bits_27_reload;
input  [0:0] l1_bits_43_reload;
input  [0:0] l1_bits_59_reload;
input  [0:0] l1_bits_75_reload;
input  [0:0] l1_bits_91_reload;
input  [0:0] l1_bits_107_reload;
input  [0:0] l1_bits_123_reload;
input  [0:0] l1_bits_12_reload;
input  [0:0] l1_bits_28_reload;
input  [0:0] l1_bits_44_reload;
input  [0:0] l1_bits_60_reload;
input  [0:0] l1_bits_76_reload;
input  [0:0] l1_bits_92_reload;
input  [0:0] l1_bits_108_reload;
input  [0:0] l1_bits_124_reload;
input  [0:0] l1_bits_13_reload;
input  [0:0] l1_bits_29_reload;
input  [0:0] l1_bits_45_reload;
input  [0:0] l1_bits_61_reload;
input  [0:0] l1_bits_77_reload;
input  [0:0] l1_bits_93_reload;
input  [0:0] l1_bits_109_reload;
input  [0:0] l1_bits_125_reload;
input  [0:0] l1_bits_14_reload;
input  [0:0] l1_bits_30_reload;
input  [0:0] l1_bits_46_reload;
input  [0:0] l1_bits_62_reload;
input  [0:0] l1_bits_78_reload;
input  [0:0] l1_bits_94_reload;
input  [0:0] l1_bits_110_reload;
input  [0:0] l1_bits_126_reload;
input  [0:0] l1_bits_15_reload;
input  [0:0] l1_bits_31_reload;
input  [0:0] l1_bits_47_reload;
input  [0:0] l1_bits_63_reload;
input  [0:0] l1_bits_79_reload;
input  [0:0] l1_bits_95_reload;
input  [0:0] l1_bits_111_reload;
input  [0:0] l1_bits_127_reload;
output  [15:0] p_0_0282_7102_out;
output   p_0_0282_7102_out_ap_vld;
output  [15:0] p_0_0282_6100_out;
output   p_0_0282_6100_out_ap_vld;
output  [15:0] p_0_0282_598_out;
output   p_0_0282_598_out_ap_vld;
output  [15:0] p_0_0282_496_out;
output   p_0_0282_496_out_ap_vld;
output  [15:0] p_0_0282_394_out;
output   p_0_0282_394_out_ap_vld;
output  [15:0] p_0_0282_292_out;
output   p_0_0282_292_out_ap_vld;
output  [15:0] p_0_0282_190_out;
output   p_0_0282_190_out_ap_vld;
output  [15:0] p_0_028288_out;
output   p_0_028288_out_ap_vld;

reg ap_idle;
reg p_0_0282_7102_out_ap_vld;
reg p_0_0282_6100_out_ap_vld;
reg p_0_0282_598_out_ap_vld;
reg p_0_0282_496_out_ap_vld;
reg p_0_0282_394_out_ap_vld;
reg p_0_0282_292_out_ap_vld;
reg p_0_0282_190_out_ap_vld;
reg p_0_028288_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln26_fu_1188_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [3:0] w_fu_320;
wire   [3:0] add_ln26_fu_1194_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_w_2;
reg   [15:0] p_0_028288_fu_324;
wire   [15:0] word_4_fu_1844_p17;
wire   [2:0] trunc_ln26_fu_1200_p1;
reg   [15:0] p_0_0282_190_fu_328;
reg   [15:0] p_0_0282_292_fu_332;
reg   [15:0] p_0_0282_394_fu_336;
reg   [15:0] p_0_0282_496_fu_340;
reg   [15:0] p_0_0282_598_fu_344;
reg   [15:0] p_0_0282_6100_fu_348;
reg   [15:0] p_0_0282_7102_fu_352;
wire   [0:0] word_fu_1204_p17;
wire   [0:0] tmp_s_fu_1244_p17;
wire   [0:0] tmp_15_fu_1284_p17;
wire   [0:0] tmp_16_fu_1324_p17;
wire   [0:0] tmp_17_fu_1364_p17;
wire   [0:0] tmp_18_fu_1404_p17;
wire   [0:0] tmp_19_fu_1444_p17;
wire   [0:0] tmp_20_fu_1484_p17;
wire   [0:0] tmp_21_fu_1524_p17;
wire   [0:0] tmp_22_fu_1564_p17;
wire   [0:0] tmp_23_fu_1604_p17;
wire   [0:0] tmp_24_fu_1644_p17;
wire   [0:0] tmp_25_fu_1684_p17;
wire   [0:0] tmp_26_fu_1724_p17;
wire   [0:0] tmp_27_fu_1764_p17;
wire   [0:0] tmp_28_fu_1804_p17;
wire   [0:0] word_fu_1204_p19;
wire   [0:0] tmp_s_fu_1244_p19;
wire   [0:0] tmp_15_fu_1284_p19;
wire   [0:0] tmp_16_fu_1324_p19;
wire   [0:0] tmp_17_fu_1364_p19;
wire   [0:0] tmp_18_fu_1404_p19;
wire   [0:0] tmp_19_fu_1444_p19;
wire   [0:0] tmp_20_fu_1484_p19;
wire   [0:0] tmp_21_fu_1524_p19;
wire   [0:0] tmp_22_fu_1564_p19;
wire   [0:0] tmp_23_fu_1604_p19;
wire   [0:0] tmp_24_fu_1644_p19;
wire   [0:0] tmp_25_fu_1684_p19;
wire   [0:0] tmp_26_fu_1724_p19;
wire   [0:0] tmp_27_fu_1764_p19;
wire   [0:0] tmp_28_fu_1804_p19;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [2:0] word_fu_1204_p1;
wire   [2:0] word_fu_1204_p3;
wire   [2:0] word_fu_1204_p5;
wire   [2:0] word_fu_1204_p7;
wire  signed [2:0] word_fu_1204_p9;
wire  signed [2:0] word_fu_1204_p11;
wire  signed [2:0] word_fu_1204_p13;
wire  signed [2:0] word_fu_1204_p15;
wire   [2:0] tmp_s_fu_1244_p1;
wire   [2:0] tmp_s_fu_1244_p3;
wire   [2:0] tmp_s_fu_1244_p5;
wire   [2:0] tmp_s_fu_1244_p7;
wire  signed [2:0] tmp_s_fu_1244_p9;
wire  signed [2:0] tmp_s_fu_1244_p11;
wire  signed [2:0] tmp_s_fu_1244_p13;
wire  signed [2:0] tmp_s_fu_1244_p15;
wire   [2:0] tmp_15_fu_1284_p1;
wire   [2:0] tmp_15_fu_1284_p3;
wire   [2:0] tmp_15_fu_1284_p5;
wire   [2:0] tmp_15_fu_1284_p7;
wire  signed [2:0] tmp_15_fu_1284_p9;
wire  signed [2:0] tmp_15_fu_1284_p11;
wire  signed [2:0] tmp_15_fu_1284_p13;
wire  signed [2:0] tmp_15_fu_1284_p15;
wire   [2:0] tmp_16_fu_1324_p1;
wire   [2:0] tmp_16_fu_1324_p3;
wire   [2:0] tmp_16_fu_1324_p5;
wire   [2:0] tmp_16_fu_1324_p7;
wire  signed [2:0] tmp_16_fu_1324_p9;
wire  signed [2:0] tmp_16_fu_1324_p11;
wire  signed [2:0] tmp_16_fu_1324_p13;
wire  signed [2:0] tmp_16_fu_1324_p15;
wire   [2:0] tmp_17_fu_1364_p1;
wire   [2:0] tmp_17_fu_1364_p3;
wire   [2:0] tmp_17_fu_1364_p5;
wire   [2:0] tmp_17_fu_1364_p7;
wire  signed [2:0] tmp_17_fu_1364_p9;
wire  signed [2:0] tmp_17_fu_1364_p11;
wire  signed [2:0] tmp_17_fu_1364_p13;
wire  signed [2:0] tmp_17_fu_1364_p15;
wire   [2:0] tmp_18_fu_1404_p1;
wire   [2:0] tmp_18_fu_1404_p3;
wire   [2:0] tmp_18_fu_1404_p5;
wire   [2:0] tmp_18_fu_1404_p7;
wire  signed [2:0] tmp_18_fu_1404_p9;
wire  signed [2:0] tmp_18_fu_1404_p11;
wire  signed [2:0] tmp_18_fu_1404_p13;
wire  signed [2:0] tmp_18_fu_1404_p15;
wire   [2:0] tmp_19_fu_1444_p1;
wire   [2:0] tmp_19_fu_1444_p3;
wire   [2:0] tmp_19_fu_1444_p5;
wire   [2:0] tmp_19_fu_1444_p7;
wire  signed [2:0] tmp_19_fu_1444_p9;
wire  signed [2:0] tmp_19_fu_1444_p11;
wire  signed [2:0] tmp_19_fu_1444_p13;
wire  signed [2:0] tmp_19_fu_1444_p15;
wire   [2:0] tmp_20_fu_1484_p1;
wire   [2:0] tmp_20_fu_1484_p3;
wire   [2:0] tmp_20_fu_1484_p5;
wire   [2:0] tmp_20_fu_1484_p7;
wire  signed [2:0] tmp_20_fu_1484_p9;
wire  signed [2:0] tmp_20_fu_1484_p11;
wire  signed [2:0] tmp_20_fu_1484_p13;
wire  signed [2:0] tmp_20_fu_1484_p15;
wire   [2:0] tmp_21_fu_1524_p1;
wire   [2:0] tmp_21_fu_1524_p3;
wire   [2:0] tmp_21_fu_1524_p5;
wire   [2:0] tmp_21_fu_1524_p7;
wire  signed [2:0] tmp_21_fu_1524_p9;
wire  signed [2:0] tmp_21_fu_1524_p11;
wire  signed [2:0] tmp_21_fu_1524_p13;
wire  signed [2:0] tmp_21_fu_1524_p15;
wire   [2:0] tmp_22_fu_1564_p1;
wire   [2:0] tmp_22_fu_1564_p3;
wire   [2:0] tmp_22_fu_1564_p5;
wire   [2:0] tmp_22_fu_1564_p7;
wire  signed [2:0] tmp_22_fu_1564_p9;
wire  signed [2:0] tmp_22_fu_1564_p11;
wire  signed [2:0] tmp_22_fu_1564_p13;
wire  signed [2:0] tmp_22_fu_1564_p15;
wire   [2:0] tmp_23_fu_1604_p1;
wire   [2:0] tmp_23_fu_1604_p3;
wire   [2:0] tmp_23_fu_1604_p5;
wire   [2:0] tmp_23_fu_1604_p7;
wire  signed [2:0] tmp_23_fu_1604_p9;
wire  signed [2:0] tmp_23_fu_1604_p11;
wire  signed [2:0] tmp_23_fu_1604_p13;
wire  signed [2:0] tmp_23_fu_1604_p15;
wire   [2:0] tmp_24_fu_1644_p1;
wire   [2:0] tmp_24_fu_1644_p3;
wire   [2:0] tmp_24_fu_1644_p5;
wire   [2:0] tmp_24_fu_1644_p7;
wire  signed [2:0] tmp_24_fu_1644_p9;
wire  signed [2:0] tmp_24_fu_1644_p11;
wire  signed [2:0] tmp_24_fu_1644_p13;
wire  signed [2:0] tmp_24_fu_1644_p15;
wire   [2:0] tmp_25_fu_1684_p1;
wire   [2:0] tmp_25_fu_1684_p3;
wire   [2:0] tmp_25_fu_1684_p5;
wire   [2:0] tmp_25_fu_1684_p7;
wire  signed [2:0] tmp_25_fu_1684_p9;
wire  signed [2:0] tmp_25_fu_1684_p11;
wire  signed [2:0] tmp_25_fu_1684_p13;
wire  signed [2:0] tmp_25_fu_1684_p15;
wire   [2:0] tmp_26_fu_1724_p1;
wire   [2:0] tmp_26_fu_1724_p3;
wire   [2:0] tmp_26_fu_1724_p5;
wire   [2:0] tmp_26_fu_1724_p7;
wire  signed [2:0] tmp_26_fu_1724_p9;
wire  signed [2:0] tmp_26_fu_1724_p11;
wire  signed [2:0] tmp_26_fu_1724_p13;
wire  signed [2:0] tmp_26_fu_1724_p15;
wire   [2:0] tmp_27_fu_1764_p1;
wire   [2:0] tmp_27_fu_1764_p3;
wire   [2:0] tmp_27_fu_1764_p5;
wire   [2:0] tmp_27_fu_1764_p7;
wire  signed [2:0] tmp_27_fu_1764_p9;
wire  signed [2:0] tmp_27_fu_1764_p11;
wire  signed [2:0] tmp_27_fu_1764_p13;
wire  signed [2:0] tmp_27_fu_1764_p15;
wire   [2:0] tmp_28_fu_1804_p1;
wire   [2:0] tmp_28_fu_1804_p3;
wire   [2:0] tmp_28_fu_1804_p5;
wire   [2:0] tmp_28_fu_1804_p7;
wire  signed [2:0] tmp_28_fu_1804_p9;
wire  signed [2:0] tmp_28_fu_1804_p11;
wire  signed [2:0] tmp_28_fu_1804_p13;
wire  signed [2:0] tmp_28_fu_1804_p15;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 w_fu_320 = 4'd0;
#0 p_0_028288_fu_324 = 16'd0;
#0 p_0_0282_190_fu_328 = 16'd0;
#0 p_0_0282_292_fu_332 = 16'd0;
#0 p_0_0282_394_fu_336 = 16'd0;
#0 p_0_0282_496_fu_340 = 16'd0;
#0 p_0_0282_598_fu_344 = 16'd0;
#0 p_0_0282_6100_fu_348 = 16'd0;
#0 p_0_0282_7102_fu_352 = 16'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) bnn_sparsemux_17_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_17_3_1_1_1_U180(
    .din0(l1_bits_reload),
    .din1(l1_bits_16_reload),
    .din2(l1_bits_32_reload),
    .din3(l1_bits_48_reload),
    .din4(l1_bits_64_reload),
    .din5(l1_bits_80_reload),
    .din6(l1_bits_96_reload),
    .din7(l1_bits_112_reload),
    .def(word_fu_1204_p17),
    .sel(trunc_ln26_fu_1200_p1),
    .dout(word_fu_1204_p19)
);

(* dissolve_hierarchy = "yes" *) bnn_sparsemux_17_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_17_3_1_1_1_U181(
    .din0(l1_bits_1_reload),
    .din1(l1_bits_17_reload),
    .din2(l1_bits_33_reload),
    .din3(l1_bits_49_reload),
    .din4(l1_bits_65_reload),
    .din5(l1_bits_81_reload),
    .din6(l1_bits_97_reload),
    .din7(l1_bits_113_reload),
    .def(tmp_s_fu_1244_p17),
    .sel(trunc_ln26_fu_1200_p1),
    .dout(tmp_s_fu_1244_p19)
);

(* dissolve_hierarchy = "yes" *) bnn_sparsemux_17_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_17_3_1_1_1_U182(
    .din0(l1_bits_2_reload),
    .din1(l1_bits_18_reload),
    .din2(l1_bits_34_reload),
    .din3(l1_bits_50_reload),
    .din4(l1_bits_66_reload),
    .din5(l1_bits_82_reload),
    .din6(l1_bits_98_reload),
    .din7(l1_bits_114_reload),
    .def(tmp_15_fu_1284_p17),
    .sel(trunc_ln26_fu_1200_p1),
    .dout(tmp_15_fu_1284_p19)
);

(* dissolve_hierarchy = "yes" *) bnn_sparsemux_17_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_17_3_1_1_1_U183(
    .din0(l1_bits_3_reload),
    .din1(l1_bits_19_reload),
    .din2(l1_bits_35_reload),
    .din3(l1_bits_51_reload),
    .din4(l1_bits_67_reload),
    .din5(l1_bits_83_reload),
    .din6(l1_bits_99_reload),
    .din7(l1_bits_115_reload),
    .def(tmp_16_fu_1324_p17),
    .sel(trunc_ln26_fu_1200_p1),
    .dout(tmp_16_fu_1324_p19)
);

(* dissolve_hierarchy = "yes" *) bnn_sparsemux_17_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_17_3_1_1_1_U184(
    .din0(l1_bits_4_reload),
    .din1(l1_bits_20_reload),
    .din2(l1_bits_36_reload),
    .din3(l1_bits_52_reload),
    .din4(l1_bits_68_reload),
    .din5(l1_bits_84_reload),
    .din6(l1_bits_100_reload),
    .din7(l1_bits_116_reload),
    .def(tmp_17_fu_1364_p17),
    .sel(trunc_ln26_fu_1200_p1),
    .dout(tmp_17_fu_1364_p19)
);

(* dissolve_hierarchy = "yes" *) bnn_sparsemux_17_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_17_3_1_1_1_U185(
    .din0(l1_bits_5_reload),
    .din1(l1_bits_21_reload),
    .din2(l1_bits_37_reload),
    .din3(l1_bits_53_reload),
    .din4(l1_bits_69_reload),
    .din5(l1_bits_85_reload),
    .din6(l1_bits_101_reload),
    .din7(l1_bits_117_reload),
    .def(tmp_18_fu_1404_p17),
    .sel(trunc_ln26_fu_1200_p1),
    .dout(tmp_18_fu_1404_p19)
);

(* dissolve_hierarchy = "yes" *) bnn_sparsemux_17_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_17_3_1_1_1_U186(
    .din0(l1_bits_6_reload),
    .din1(l1_bits_22_reload),
    .din2(l1_bits_38_reload),
    .din3(l1_bits_54_reload),
    .din4(l1_bits_70_reload),
    .din5(l1_bits_86_reload),
    .din6(l1_bits_102_reload),
    .din7(l1_bits_118_reload),
    .def(tmp_19_fu_1444_p17),
    .sel(trunc_ln26_fu_1200_p1),
    .dout(tmp_19_fu_1444_p19)
);

(* dissolve_hierarchy = "yes" *) bnn_sparsemux_17_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_17_3_1_1_1_U187(
    .din0(l1_bits_7_reload),
    .din1(l1_bits_23_reload),
    .din2(l1_bits_39_reload),
    .din3(l1_bits_55_reload),
    .din4(l1_bits_71_reload),
    .din5(l1_bits_87_reload),
    .din6(l1_bits_103_reload),
    .din7(l1_bits_119_reload),
    .def(tmp_20_fu_1484_p17),
    .sel(trunc_ln26_fu_1200_p1),
    .dout(tmp_20_fu_1484_p19)
);

(* dissolve_hierarchy = "yes" *) bnn_sparsemux_17_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_17_3_1_1_1_U188(
    .din0(l1_bits_8_reload),
    .din1(l1_bits_24_reload),
    .din2(l1_bits_40_reload),
    .din3(l1_bits_56_reload),
    .din4(l1_bits_72_reload),
    .din5(l1_bits_88_reload),
    .din6(l1_bits_104_reload),
    .din7(l1_bits_120_reload),
    .def(tmp_21_fu_1524_p17),
    .sel(trunc_ln26_fu_1200_p1),
    .dout(tmp_21_fu_1524_p19)
);

(* dissolve_hierarchy = "yes" *) bnn_sparsemux_17_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_17_3_1_1_1_U189(
    .din0(l1_bits_9_reload),
    .din1(l1_bits_25_reload),
    .din2(l1_bits_41_reload),
    .din3(l1_bits_57_reload),
    .din4(l1_bits_73_reload),
    .din5(l1_bits_89_reload),
    .din6(l1_bits_105_reload),
    .din7(l1_bits_121_reload),
    .def(tmp_22_fu_1564_p17),
    .sel(trunc_ln26_fu_1200_p1),
    .dout(tmp_22_fu_1564_p19)
);

(* dissolve_hierarchy = "yes" *) bnn_sparsemux_17_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_17_3_1_1_1_U190(
    .din0(l1_bits_10_reload),
    .din1(l1_bits_26_reload),
    .din2(l1_bits_42_reload),
    .din3(l1_bits_58_reload),
    .din4(l1_bits_74_reload),
    .din5(l1_bits_90_reload),
    .din6(l1_bits_106_reload),
    .din7(l1_bits_122_reload),
    .def(tmp_23_fu_1604_p17),
    .sel(trunc_ln26_fu_1200_p1),
    .dout(tmp_23_fu_1604_p19)
);

(* dissolve_hierarchy = "yes" *) bnn_sparsemux_17_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_17_3_1_1_1_U191(
    .din0(l1_bits_11_reload),
    .din1(l1_bits_27_reload),
    .din2(l1_bits_43_reload),
    .din3(l1_bits_59_reload),
    .din4(l1_bits_75_reload),
    .din5(l1_bits_91_reload),
    .din6(l1_bits_107_reload),
    .din7(l1_bits_123_reload),
    .def(tmp_24_fu_1644_p17),
    .sel(trunc_ln26_fu_1200_p1),
    .dout(tmp_24_fu_1644_p19)
);

(* dissolve_hierarchy = "yes" *) bnn_sparsemux_17_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_17_3_1_1_1_U192(
    .din0(l1_bits_12_reload),
    .din1(l1_bits_28_reload),
    .din2(l1_bits_44_reload),
    .din3(l1_bits_60_reload),
    .din4(l1_bits_76_reload),
    .din5(l1_bits_92_reload),
    .din6(l1_bits_108_reload),
    .din7(l1_bits_124_reload),
    .def(tmp_25_fu_1684_p17),
    .sel(trunc_ln26_fu_1200_p1),
    .dout(tmp_25_fu_1684_p19)
);

(* dissolve_hierarchy = "yes" *) bnn_sparsemux_17_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_17_3_1_1_1_U193(
    .din0(l1_bits_13_reload),
    .din1(l1_bits_29_reload),
    .din2(l1_bits_45_reload),
    .din3(l1_bits_61_reload),
    .din4(l1_bits_77_reload),
    .din5(l1_bits_93_reload),
    .din6(l1_bits_109_reload),
    .din7(l1_bits_125_reload),
    .def(tmp_26_fu_1724_p17),
    .sel(trunc_ln26_fu_1200_p1),
    .dout(tmp_26_fu_1724_p19)
);

(* dissolve_hierarchy = "yes" *) bnn_sparsemux_17_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_17_3_1_1_1_U194(
    .din0(l1_bits_14_reload),
    .din1(l1_bits_30_reload),
    .din2(l1_bits_46_reload),
    .din3(l1_bits_62_reload),
    .din4(l1_bits_78_reload),
    .din5(l1_bits_94_reload),
    .din6(l1_bits_110_reload),
    .din7(l1_bits_126_reload),
    .def(tmp_27_fu_1764_p17),
    .sel(trunc_ln26_fu_1200_p1),
    .dout(tmp_27_fu_1764_p19)
);

(* dissolve_hierarchy = "yes" *) bnn_sparsemux_17_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_17_3_1_1_1_U195(
    .din0(l1_bits_15_reload),
    .din1(l1_bits_31_reload),
    .din2(l1_bits_47_reload),
    .din3(l1_bits_63_reload),
    .din4(l1_bits_79_reload),
    .din5(l1_bits_95_reload),
    .din6(l1_bits_111_reload),
    .din7(l1_bits_127_reload),
    .def(tmp_28_fu_1804_p17),
    .sel(trunc_ln26_fu_1200_p1),
    .dout(tmp_28_fu_1804_p19)
);

bnn_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln26_fu_1188_p2 == 1'd0)) begin
            w_fu_320 <= add_ln26_fu_1194_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            w_fu_320 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln26_fu_1188_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln26_fu_1200_p1 == 3'd0))) begin
        p_0_028288_fu_324 <= word_4_fu_1844_p17;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln26_fu_1188_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln26_fu_1200_p1 == 3'd1))) begin
        p_0_0282_190_fu_328 <= word_4_fu_1844_p17;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln26_fu_1188_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln26_fu_1200_p1 == 3'd2))) begin
        p_0_0282_292_fu_332 <= word_4_fu_1844_p17;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln26_fu_1188_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln26_fu_1200_p1 == 3'd3))) begin
        p_0_0282_394_fu_336 <= word_4_fu_1844_p17;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln26_fu_1188_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln26_fu_1200_p1 == 3'd4))) begin
        p_0_0282_496_fu_340 <= word_4_fu_1844_p17;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln26_fu_1188_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln26_fu_1200_p1 == 3'd5))) begin
        p_0_0282_598_fu_344 <= word_4_fu_1844_p17;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln26_fu_1188_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln26_fu_1200_p1 == 3'd6))) begin
        p_0_0282_6100_fu_348 <= word_4_fu_1844_p17;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln26_fu_1188_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln26_fu_1200_p1 == 3'd7))) begin
        p_0_0282_7102_fu_352 <= word_4_fu_1844_p17;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln26_fu_1188_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_w_2 = 4'd0;
    end else begin
        ap_sig_allocacmp_w_2 = w_fu_320;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln26_fu_1188_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_028288_out_ap_vld = 1'b1;
    end else begin
        p_0_028288_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln26_fu_1188_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_0282_190_out_ap_vld = 1'b1;
    end else begin
        p_0_0282_190_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln26_fu_1188_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_0282_292_out_ap_vld = 1'b1;
    end else begin
        p_0_0282_292_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln26_fu_1188_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_0282_394_out_ap_vld = 1'b1;
    end else begin
        p_0_0282_394_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln26_fu_1188_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_0282_496_out_ap_vld = 1'b1;
    end else begin
        p_0_0282_496_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln26_fu_1188_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_0282_598_out_ap_vld = 1'b1;
    end else begin
        p_0_0282_598_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln26_fu_1188_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_0282_6100_out_ap_vld = 1'b1;
    end else begin
        p_0_0282_6100_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln26_fu_1188_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_0282_7102_out_ap_vld = 1'b1;
    end else begin
        p_0_0282_7102_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln26_fu_1194_p2 = (ap_sig_allocacmp_w_2 + 4'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln26_fu_1188_p2 = ((ap_sig_allocacmp_w_2 == 4'd8) ? 1'b1 : 1'b0);

assign p_0_028288_out = p_0_028288_fu_324;

assign p_0_0282_190_out = p_0_0282_190_fu_328;

assign p_0_0282_292_out = p_0_0282_292_fu_332;

assign p_0_0282_394_out = p_0_0282_394_fu_336;

assign p_0_0282_496_out = p_0_0282_496_fu_340;

assign p_0_0282_598_out = p_0_0282_598_fu_344;

assign p_0_0282_6100_out = p_0_0282_6100_fu_348;

assign p_0_0282_7102_out = p_0_0282_7102_fu_352;

assign tmp_15_fu_1284_p17 = 'bx;

assign tmp_16_fu_1324_p17 = 'bx;

assign tmp_17_fu_1364_p17 = 'bx;

assign tmp_18_fu_1404_p17 = 'bx;

assign tmp_19_fu_1444_p17 = 'bx;

assign tmp_20_fu_1484_p17 = 'bx;

assign tmp_21_fu_1524_p17 = 'bx;

assign tmp_22_fu_1564_p17 = 'bx;

assign tmp_23_fu_1604_p17 = 'bx;

assign tmp_24_fu_1644_p17 = 'bx;

assign tmp_25_fu_1684_p17 = 'bx;

assign tmp_26_fu_1724_p17 = 'bx;

assign tmp_27_fu_1764_p17 = 'bx;

assign tmp_28_fu_1804_p17 = 'bx;

assign tmp_s_fu_1244_p17 = 'bx;

assign trunc_ln26_fu_1200_p1 = ap_sig_allocacmp_w_2[2:0];

assign word_4_fu_1844_p17 = {{{{{{{{{{{{{{{{word_fu_1204_p19}, {tmp_s_fu_1244_p19}}, {tmp_15_fu_1284_p19}}, {tmp_16_fu_1324_p19}}, {tmp_17_fu_1364_p19}}, {tmp_18_fu_1404_p19}}, {tmp_19_fu_1444_p19}}, {tmp_20_fu_1484_p19}}, {tmp_21_fu_1524_p19}}, {tmp_22_fu_1564_p19}}, {tmp_23_fu_1604_p19}}, {tmp_24_fu_1644_p19}}, {tmp_25_fu_1684_p19}}, {tmp_26_fu_1724_p19}}, {tmp_27_fu_1764_p19}}, {tmp_28_fu_1804_p19}};

assign word_fu_1204_p17 = 'bx;

endmodule //bnn_bnn_Pipeline_pack_loop
