

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST"},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.l1_bits_U"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.l1_bits_1_U"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.l1_bits_2_U"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.l1_bits_3_U"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.l1_bits_4_U"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.l1_bits_5_U"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.l1_bits_6_U"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.l1_bits_7_U"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.l1_packed_U"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.l2_bits_U"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.l2_bits_1_U"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.l2_bits_2_U"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.l2_bits_3_U"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.l2_bits_4_U"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.l2_bits_5_U"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.l2_bits_6_U"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.l2_bits_7_U"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_50_1_fu_124"},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_50_1_fu_124.w1_U"},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_50_1_fu_124.mac_muladd_8ns_6ns_6ns_13_4_1_U1"},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_Pipeline_VITIS_LOOP_82_1_VITIS_LOOP_50_1_fu_124.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "22", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_Pipeline_VITIS_LOOP_24_1_fu_148"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_Pipeline_VITIS_LOOP_24_1_fu_148.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "24", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_Pipeline_VITIS_LOOP_108_2_VITIS_LOOP_50_1_fu_161"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_Pipeline_VITIS_LOOP_108_2_VITIS_LOOP_50_1_fu_161.w2_U"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_Pipeline_VITIS_LOOP_108_2_VITIS_LOOP_50_1_fu_161.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "27", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_Pipeline_VITIS_LOOP_24_11_fu_176"},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_Pipeline_VITIS_LOOP_24_11_fu_176.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "29", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_Pipeline_VITIS_LOOP_129_3_fu_192"},
	{"ID" : "30", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_Pipeline_VITIS_LOOP_129_3_fu_192.p_ZL2w3_0_U"},
	{"ID" : "31", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_Pipeline_VITIS_LOOP_129_3_fu_192.p_ZL2w3_1_U"},
	{"ID" : "32", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_Pipeline_VITIS_LOOP_129_3_fu_192.flow_control_loop_pipe_sequential_init_U"}]}
set DependenceCheckSize 0
