-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bnn_bnn_Pipeline_l3_loop is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_0_0271104_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    p_0_0271_1106_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    p_0_0271_2108_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    p_0_0271_3110_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    ys_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    ys_ce0 : OUT STD_LOGIC;
    ys_we0 : OUT STD_LOGIC;
    ys_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of bnn_bnn_Pipeline_l3_loop is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv8_C0 : STD_LOGIC_VECTOR (7 downto 0) := "11000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln139_fu_198_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal w3_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal w3_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal w3_address1 : STD_LOGIC_VECTOR (5 downto 0);
    signal w3_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal w3_address2 : STD_LOGIC_VECTOR (5 downto 0);
    signal w3_q2 : STD_LOGIC_VECTOR (15 downto 0);
    signal w3_address3 : STD_LOGIC_VECTOR (5 downto 0);
    signal w3_q3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal n_1_reg_1722 : STD_LOGIC_VECTOR (3 downto 0);
    signal n_1_reg_1722_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal n_1_reg_1722_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln11_2_fu_486_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln11_2_reg_1751 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln11_5_fu_512_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln11_5_reg_1756 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln11_9_fu_538_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln11_9_reg_1761 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln11_12_fu_564_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln11_12_reg_1766 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln11_17_fu_789_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln11_17_reg_1771 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln11_20_fu_815_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln11_20_reg_1776 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln11_24_fu_841_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln11_24_reg_1781 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln11_27_fu_867_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln11_27_reg_1786 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln11_32_fu_1092_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln11_32_reg_1791 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln11_35_fu_1118_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln11_35_reg_1796 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln11_39_fu_1144_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln11_39_reg_1801 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln11_42_fu_1170_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln11_42_reg_1806 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln11_47_fu_1395_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln11_47_reg_1811 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln11_50_fu_1421_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln11_50_reg_1816 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln11_54_fu_1447_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln11_54_reg_1821 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln11_57_fu_1473_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln11_57_reg_1826 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln64_2_fu_1667_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln64_2_reg_1831 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln142_fu_1690_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln60_fu_218_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln60_1_fu_231_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln60_2_fu_244_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln60_3_fu_257_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln139_fu_1673_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal n_fu_100 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln139_fu_204_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_n_1 : STD_LOGIC_VECTOR (3 downto 0);
    signal w3_ce3_local : STD_LOGIC;
    signal w3_ce2_local : STD_LOGIC;
    signal w3_ce1_local : STD_LOGIC;
    signal w3_ce0_local : STD_LOGIC;
    signal ys_we0_local : STD_LOGIC;
    signal ys_ce0_local : STD_LOGIC;
    signal shl_ln2_fu_210_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal or_ln60_7_fu_223_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal or_ln60_8_fu_236_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal or_ln60_9_fu_249_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal xor_ln60_fu_267_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xnor_fu_272_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal cnt_fu_278_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_286_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_298_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_310_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_322_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_334_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_346_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_358_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_370_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_382_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_394_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_fu_406_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_fu_418_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_430_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_fu_442_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_fu_454_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln11_fu_294_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln8_fu_282_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln11_fu_466_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_1_fu_306_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_2_fu_318_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln11_1_fu_476_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_16_fu_482_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln11_15_fu_472_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln11_3_fu_330_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_4_fu_342_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln11_3_fu_492_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_5_fu_354_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_6_fu_366_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln11_4_fu_502_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_19_fu_508_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln11_18_fu_498_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln11_7_fu_378_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_8_fu_390_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln11_7_fu_518_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_9_fu_402_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_10_fu_414_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln11_8_fu_528_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_23_fu_534_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln11_22_fu_524_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln11_11_fu_426_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_12_fu_438_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln11_10_fu_544_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_13_fu_450_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_14_fu_462_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln11_11_fu_554_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_26_fu_560_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln11_25_fu_550_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal xor_ln60_2_fu_570_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xnor_1_fu_575_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal cnt_2_fu_581_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_15_fu_589_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_fu_601_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_fu_613_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_18_fu_625_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_19_fu_637_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_20_fu_649_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_fu_661_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_fu_673_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_23_fu_685_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_24_fu_697_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_25_fu_709_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_26_fu_721_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_27_fu_733_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_28_fu_745_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_29_fu_757_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln11_29_fu_597_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln8_1_fu_585_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln11_15_fu_769_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_30_fu_609_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_31_fu_621_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln11_16_fu_779_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_45_fu_785_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln11_44_fu_775_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln11_32_fu_633_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_33_fu_645_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln11_18_fu_795_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_34_fu_657_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_35_fu_669_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln11_19_fu_805_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_48_fu_811_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln11_47_fu_801_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln11_36_fu_681_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_37_fu_693_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln11_22_fu_821_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_38_fu_705_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_39_fu_717_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln11_23_fu_831_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_52_fu_837_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln11_51_fu_827_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln11_40_fu_729_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_41_fu_741_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln11_25_fu_847_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_42_fu_753_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_43_fu_765_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln11_26_fu_857_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_55_fu_863_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln11_54_fu_853_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal xor_ln60_4_fu_873_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xnor_2_fu_878_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal cnt_4_fu_884_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_30_fu_892_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_31_fu_904_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_32_fu_916_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_33_fu_928_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_34_fu_940_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_35_fu_952_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_36_fu_964_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_37_fu_976_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_38_fu_988_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_39_fu_1000_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_40_fu_1012_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_41_fu_1024_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_42_fu_1036_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_43_fu_1048_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_44_fu_1060_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln11_58_fu_900_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln8_2_fu_888_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln11_30_fu_1072_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_59_fu_912_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_60_fu_924_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln11_31_fu_1082_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_74_fu_1088_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln11_73_fu_1078_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln11_61_fu_936_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_62_fu_948_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln11_33_fu_1098_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_63_fu_960_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_64_fu_972_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln11_34_fu_1108_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_77_fu_1114_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln11_76_fu_1104_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln11_65_fu_984_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_66_fu_996_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln11_37_fu_1124_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_67_fu_1008_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_68_fu_1020_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln11_38_fu_1134_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_81_fu_1140_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln11_80_fu_1130_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln11_69_fu_1032_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_70_fu_1044_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln11_40_fu_1150_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_71_fu_1056_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_72_fu_1068_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln11_41_fu_1160_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_84_fu_1166_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln11_83_fu_1156_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal xor_ln60_6_fu_1176_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal xnor_3_fu_1181_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal cnt_6_fu_1187_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_45_fu_1195_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_46_fu_1207_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_47_fu_1219_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_48_fu_1231_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_49_fu_1243_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_50_fu_1255_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_51_fu_1267_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_52_fu_1279_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_53_fu_1291_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_54_fu_1303_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_55_fu_1315_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_56_fu_1327_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_57_fu_1339_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_58_fu_1351_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_59_fu_1363_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln11_87_fu_1203_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln8_3_fu_1191_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln11_45_fu_1375_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_88_fu_1215_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_89_fu_1227_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln11_46_fu_1385_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_103_fu_1391_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln11_102_fu_1381_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln11_90_fu_1239_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_91_fu_1251_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln11_48_fu_1401_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_92_fu_1263_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_93_fu_1275_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln11_49_fu_1411_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_106_fu_1417_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln11_105_fu_1407_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln11_94_fu_1287_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_95_fu_1299_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln11_52_fu_1427_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_96_fu_1311_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_97_fu_1323_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln11_53_fu_1437_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_110_fu_1443_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln11_109_fu_1433_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln11_98_fu_1335_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_99_fu_1347_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln11_55_fu_1453_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_100_fu_1359_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_101_fu_1371_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln11_56_fu_1463_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln11_113_fu_1469_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln11_112_fu_1459_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln11_20_fu_1482_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln11_17_fu_1479_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln11_6_fu_1485_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln11_27_fu_1498_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln11_24_fu_1495_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln11_13_fu_1501_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln11_28_fu_1507_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln11_21_fu_1491_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln11_49_fu_1520_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln11_46_fu_1517_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln11_21_fu_1523_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln11_56_fu_1536_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln11_53_fu_1533_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln11_28_fu_1539_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln11_57_fu_1545_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln11_50_fu_1529_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln11_78_fu_1558_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln11_75_fu_1555_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln11_36_fu_1561_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln11_85_fu_1574_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln11_82_fu_1571_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln11_43_fu_1577_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln11_86_fu_1583_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln11_79_fu_1567_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln11_107_fu_1596_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln11_104_fu_1593_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln11_51_fu_1599_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln11_114_fu_1612_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln11_111_fu_1609_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln11_58_fu_1615_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln11_115_fu_1621_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln11_108_fu_1605_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal cnt_1_fu_1511_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal cnt_3_fu_1549_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal cnt_5_fu_1587_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal cnt_7_fu_1625_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln61_1_fu_1635_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln61_fu_1631_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln64_fu_1647_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln61_2_fu_1639_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln64_fu_1643_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln64_1_fu_1657_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln64_2_fu_1663_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln64_1_fu_1653_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal shl_ln64_2_fu_1677_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal dot_fu_1684_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component bnn_bnn_Pipeline_l3_loop_w3_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        address1 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        address2 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce2 : IN STD_LOGIC;
        q2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        address3 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce3 : IN STD_LOGIC;
        q3 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component bnn_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    w3_U : component bnn_bnn_Pipeline_l3_loop_w3_ROM_AUTO_1R
    generic map (
        DataWidth => 16,
        AddressRange => 40,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => w3_address0,
        ce0 => w3_ce0_local,
        q0 => w3_q0,
        address1 => w3_address1,
        ce1 => w3_ce1_local,
        q1 => w3_q1,
        address2 => w3_address2,
        ce2 => w3_ce2_local,
        q2 => w3_q2,
        address3 => w3_address3,
        ce3 => w3_ce3_local,
        q3 => w3_q3);

    flow_control_loop_pipe_sequential_init_U : component bnn_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    n_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln139_fu_198_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    n_fu_100 <= add_ln139_fu_204_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    n_fu_100 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln11_12_reg_1766 <= add_ln11_12_fu_564_p2;
                add_ln11_17_reg_1771 <= add_ln11_17_fu_789_p2;
                add_ln11_20_reg_1776 <= add_ln11_20_fu_815_p2;
                add_ln11_24_reg_1781 <= add_ln11_24_fu_841_p2;
                add_ln11_27_reg_1786 <= add_ln11_27_fu_867_p2;
                add_ln11_2_reg_1751 <= add_ln11_2_fu_486_p2;
                add_ln11_32_reg_1791 <= add_ln11_32_fu_1092_p2;
                add_ln11_35_reg_1796 <= add_ln11_35_fu_1118_p2;
                add_ln11_39_reg_1801 <= add_ln11_39_fu_1144_p2;
                add_ln11_42_reg_1806 <= add_ln11_42_fu_1170_p2;
                add_ln11_47_reg_1811 <= add_ln11_47_fu_1395_p2;
                add_ln11_50_reg_1816 <= add_ln11_50_fu_1421_p2;
                add_ln11_54_reg_1821 <= add_ln11_54_fu_1447_p2;
                add_ln11_57_reg_1826 <= add_ln11_57_fu_1473_p2;
                add_ln11_5_reg_1756 <= add_ln11_5_fu_512_p2;
                add_ln11_9_reg_1761 <= add_ln11_9_fu_538_p2;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                n_1_reg_1722 <= ap_sig_allocacmp_n_1;
                n_1_reg_1722_pp0_iter1_reg <= n_1_reg_1722;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln64_2_reg_1831 <= add_ln64_2_fu_1667_p2;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                n_1_reg_1722_pp0_iter2_reg <= n_1_reg_1722_pp0_iter1_reg;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln11_10_fu_544_p2 <= std_logic_vector(unsigned(zext_ln11_11_fu_426_p1) + unsigned(zext_ln11_12_fu_438_p1));
    add_ln11_11_fu_554_p2 <= std_logic_vector(unsigned(zext_ln11_13_fu_450_p1) + unsigned(zext_ln11_14_fu_462_p1));
    add_ln11_12_fu_564_p2 <= std_logic_vector(unsigned(zext_ln11_26_fu_560_p1) + unsigned(zext_ln11_25_fu_550_p1));
    add_ln11_13_fu_1501_p2 <= std_logic_vector(unsigned(zext_ln11_27_fu_1498_p1) + unsigned(zext_ln11_24_fu_1495_p1));
    add_ln11_15_fu_769_p2 <= std_logic_vector(unsigned(zext_ln11_29_fu_597_p1) + unsigned(zext_ln8_1_fu_585_p1));
    add_ln11_16_fu_779_p2 <= std_logic_vector(unsigned(zext_ln11_30_fu_609_p1) + unsigned(zext_ln11_31_fu_621_p1));
    add_ln11_17_fu_789_p2 <= std_logic_vector(unsigned(zext_ln11_45_fu_785_p1) + unsigned(zext_ln11_44_fu_775_p1));
    add_ln11_18_fu_795_p2 <= std_logic_vector(unsigned(zext_ln11_32_fu_633_p1) + unsigned(zext_ln11_33_fu_645_p1));
    add_ln11_19_fu_805_p2 <= std_logic_vector(unsigned(zext_ln11_34_fu_657_p1) + unsigned(zext_ln11_35_fu_669_p1));
    add_ln11_1_fu_476_p2 <= std_logic_vector(unsigned(zext_ln11_1_fu_306_p1) + unsigned(zext_ln11_2_fu_318_p1));
    add_ln11_20_fu_815_p2 <= std_logic_vector(unsigned(zext_ln11_48_fu_811_p1) + unsigned(zext_ln11_47_fu_801_p1));
    add_ln11_21_fu_1523_p2 <= std_logic_vector(unsigned(zext_ln11_49_fu_1520_p1) + unsigned(zext_ln11_46_fu_1517_p1));
    add_ln11_22_fu_821_p2 <= std_logic_vector(unsigned(zext_ln11_36_fu_681_p1) + unsigned(zext_ln11_37_fu_693_p1));
    add_ln11_23_fu_831_p2 <= std_logic_vector(unsigned(zext_ln11_38_fu_705_p1) + unsigned(zext_ln11_39_fu_717_p1));
    add_ln11_24_fu_841_p2 <= std_logic_vector(unsigned(zext_ln11_52_fu_837_p1) + unsigned(zext_ln11_51_fu_827_p1));
    add_ln11_25_fu_847_p2 <= std_logic_vector(unsigned(zext_ln11_40_fu_729_p1) + unsigned(zext_ln11_41_fu_741_p1));
    add_ln11_26_fu_857_p2 <= std_logic_vector(unsigned(zext_ln11_42_fu_753_p1) + unsigned(zext_ln11_43_fu_765_p1));
    add_ln11_27_fu_867_p2 <= std_logic_vector(unsigned(zext_ln11_55_fu_863_p1) + unsigned(zext_ln11_54_fu_853_p1));
    add_ln11_28_fu_1539_p2 <= std_logic_vector(unsigned(zext_ln11_56_fu_1536_p1) + unsigned(zext_ln11_53_fu_1533_p1));
    add_ln11_2_fu_486_p2 <= std_logic_vector(unsigned(zext_ln11_16_fu_482_p1) + unsigned(zext_ln11_15_fu_472_p1));
    add_ln11_30_fu_1072_p2 <= std_logic_vector(unsigned(zext_ln11_58_fu_900_p1) + unsigned(zext_ln8_2_fu_888_p1));
    add_ln11_31_fu_1082_p2 <= std_logic_vector(unsigned(zext_ln11_59_fu_912_p1) + unsigned(zext_ln11_60_fu_924_p1));
    add_ln11_32_fu_1092_p2 <= std_logic_vector(unsigned(zext_ln11_74_fu_1088_p1) + unsigned(zext_ln11_73_fu_1078_p1));
    add_ln11_33_fu_1098_p2 <= std_logic_vector(unsigned(zext_ln11_61_fu_936_p1) + unsigned(zext_ln11_62_fu_948_p1));
    add_ln11_34_fu_1108_p2 <= std_logic_vector(unsigned(zext_ln11_63_fu_960_p1) + unsigned(zext_ln11_64_fu_972_p1));
    add_ln11_35_fu_1118_p2 <= std_logic_vector(unsigned(zext_ln11_77_fu_1114_p1) + unsigned(zext_ln11_76_fu_1104_p1));
    add_ln11_36_fu_1561_p2 <= std_logic_vector(unsigned(zext_ln11_78_fu_1558_p1) + unsigned(zext_ln11_75_fu_1555_p1));
    add_ln11_37_fu_1124_p2 <= std_logic_vector(unsigned(zext_ln11_65_fu_984_p1) + unsigned(zext_ln11_66_fu_996_p1));
    add_ln11_38_fu_1134_p2 <= std_logic_vector(unsigned(zext_ln11_67_fu_1008_p1) + unsigned(zext_ln11_68_fu_1020_p1));
    add_ln11_39_fu_1144_p2 <= std_logic_vector(unsigned(zext_ln11_81_fu_1140_p1) + unsigned(zext_ln11_80_fu_1130_p1));
    add_ln11_3_fu_492_p2 <= std_logic_vector(unsigned(zext_ln11_3_fu_330_p1) + unsigned(zext_ln11_4_fu_342_p1));
    add_ln11_40_fu_1150_p2 <= std_logic_vector(unsigned(zext_ln11_69_fu_1032_p1) + unsigned(zext_ln11_70_fu_1044_p1));
    add_ln11_41_fu_1160_p2 <= std_logic_vector(unsigned(zext_ln11_71_fu_1056_p1) + unsigned(zext_ln11_72_fu_1068_p1));
    add_ln11_42_fu_1170_p2 <= std_logic_vector(unsigned(zext_ln11_84_fu_1166_p1) + unsigned(zext_ln11_83_fu_1156_p1));
    add_ln11_43_fu_1577_p2 <= std_logic_vector(unsigned(zext_ln11_85_fu_1574_p1) + unsigned(zext_ln11_82_fu_1571_p1));
    add_ln11_45_fu_1375_p2 <= std_logic_vector(unsigned(zext_ln11_87_fu_1203_p1) + unsigned(zext_ln8_3_fu_1191_p1));
    add_ln11_46_fu_1385_p2 <= std_logic_vector(unsigned(zext_ln11_88_fu_1215_p1) + unsigned(zext_ln11_89_fu_1227_p1));
    add_ln11_47_fu_1395_p2 <= std_logic_vector(unsigned(zext_ln11_103_fu_1391_p1) + unsigned(zext_ln11_102_fu_1381_p1));
    add_ln11_48_fu_1401_p2 <= std_logic_vector(unsigned(zext_ln11_90_fu_1239_p1) + unsigned(zext_ln11_91_fu_1251_p1));
    add_ln11_49_fu_1411_p2 <= std_logic_vector(unsigned(zext_ln11_92_fu_1263_p1) + unsigned(zext_ln11_93_fu_1275_p1));
    add_ln11_4_fu_502_p2 <= std_logic_vector(unsigned(zext_ln11_5_fu_354_p1) + unsigned(zext_ln11_6_fu_366_p1));
    add_ln11_50_fu_1421_p2 <= std_logic_vector(unsigned(zext_ln11_106_fu_1417_p1) + unsigned(zext_ln11_105_fu_1407_p1));
    add_ln11_51_fu_1599_p2 <= std_logic_vector(unsigned(zext_ln11_107_fu_1596_p1) + unsigned(zext_ln11_104_fu_1593_p1));
    add_ln11_52_fu_1427_p2 <= std_logic_vector(unsigned(zext_ln11_94_fu_1287_p1) + unsigned(zext_ln11_95_fu_1299_p1));
    add_ln11_53_fu_1437_p2 <= std_logic_vector(unsigned(zext_ln11_96_fu_1311_p1) + unsigned(zext_ln11_97_fu_1323_p1));
    add_ln11_54_fu_1447_p2 <= std_logic_vector(unsigned(zext_ln11_110_fu_1443_p1) + unsigned(zext_ln11_109_fu_1433_p1));
    add_ln11_55_fu_1453_p2 <= std_logic_vector(unsigned(zext_ln11_98_fu_1335_p1) + unsigned(zext_ln11_99_fu_1347_p1));
    add_ln11_56_fu_1463_p2 <= std_logic_vector(unsigned(zext_ln11_100_fu_1359_p1) + unsigned(zext_ln11_101_fu_1371_p1));
    add_ln11_57_fu_1473_p2 <= std_logic_vector(unsigned(zext_ln11_113_fu_1469_p1) + unsigned(zext_ln11_112_fu_1459_p1));
    add_ln11_58_fu_1615_p2 <= std_logic_vector(unsigned(zext_ln11_114_fu_1612_p1) + unsigned(zext_ln11_111_fu_1609_p1));
    add_ln11_5_fu_512_p2 <= std_logic_vector(unsigned(zext_ln11_19_fu_508_p1) + unsigned(zext_ln11_18_fu_498_p1));
    add_ln11_6_fu_1485_p2 <= std_logic_vector(unsigned(zext_ln11_20_fu_1482_p1) + unsigned(zext_ln11_17_fu_1479_p1));
    add_ln11_7_fu_518_p2 <= std_logic_vector(unsigned(zext_ln11_7_fu_378_p1) + unsigned(zext_ln11_8_fu_390_p1));
    add_ln11_8_fu_528_p2 <= std_logic_vector(unsigned(zext_ln11_9_fu_402_p1) + unsigned(zext_ln11_10_fu_414_p1));
    add_ln11_9_fu_538_p2 <= std_logic_vector(unsigned(zext_ln11_23_fu_534_p1) + unsigned(zext_ln11_22_fu_524_p1));
    add_ln11_fu_466_p2 <= std_logic_vector(unsigned(zext_ln11_fu_294_p1) + unsigned(zext_ln8_fu_282_p1));
    add_ln139_fu_204_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_n_1) + unsigned(ap_const_lv4_1));
    add_ln64_1_fu_1657_p2 <= std_logic_vector(unsigned(zext_ln61_2_fu_1639_p1) + unsigned(zext_ln64_fu_1643_p1));
    add_ln64_2_fu_1667_p2 <= std_logic_vector(unsigned(zext_ln64_2_fu_1663_p1) + unsigned(zext_ln64_1_fu_1653_p1));
    add_ln64_fu_1647_p2 <= std_logic_vector(unsigned(zext_ln61_1_fu_1635_p1) + unsigned(zext_ln61_fu_1631_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln139_fu_198_p2)
    begin
        if (((icmp_ln139_fu_198_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_n_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, n_fu_100, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_n_1 <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_n_1 <= n_fu_100;
        end if; 
    end process;

    cnt_1_fu_1511_p2 <= std_logic_vector(unsigned(zext_ln11_28_fu_1507_p1) + unsigned(zext_ln11_21_fu_1491_p1));
    cnt_2_fu_581_p1 <= xnor_1_fu_575_p2(1 - 1 downto 0);
    cnt_3_fu_1549_p2 <= std_logic_vector(unsigned(zext_ln11_57_fu_1545_p1) + unsigned(zext_ln11_50_fu_1529_p1));
    cnt_4_fu_884_p1 <= xnor_2_fu_878_p2(1 - 1 downto 0);
    cnt_5_fu_1587_p2 <= std_logic_vector(unsigned(zext_ln11_86_fu_1583_p1) + unsigned(zext_ln11_79_fu_1567_p1));
    cnt_6_fu_1187_p1 <= xnor_3_fu_1181_p2(1 - 1 downto 0);
    cnt_7_fu_1625_p2 <= std_logic_vector(unsigned(zext_ln11_115_fu_1621_p1) + unsigned(zext_ln11_108_fu_1605_p1));
    cnt_fu_278_p1 <= xnor_fu_272_p2(1 - 1 downto 0);
    dot_fu_1684_p2 <= std_logic_vector(unsigned(shl_ln64_2_fu_1677_p3) + unsigned(ap_const_lv8_C0));
    icmp_ln139_fu_198_p2 <= "1" when (ap_sig_allocacmp_n_1 = ap_const_lv4_A) else "0";
    or_ln60_7_fu_223_p3 <= (ap_sig_allocacmp_n_1 & ap_const_lv2_1);
    or_ln60_8_fu_236_p3 <= (ap_sig_allocacmp_n_1 & ap_const_lv2_2);
    or_ln60_9_fu_249_p3 <= (ap_sig_allocacmp_n_1 & ap_const_lv2_3);
        sext_ln142_fu_1690_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(dot_fu_1684_p2),32));

    shl_ln2_fu_210_p3 <= (ap_sig_allocacmp_n_1 & ap_const_lv2_0);
    shl_ln64_2_fu_1677_p3 <= (add_ln64_2_reg_1831 & ap_const_lv1_0);
    tmp_10_fu_406_p3 <= xnor_fu_272_p2(11 downto 11);
    tmp_11_fu_418_p3 <= xnor_fu_272_p2(12 downto 12);
    tmp_12_fu_430_p3 <= xnor_fu_272_p2(13 downto 13);
    tmp_13_fu_442_p3 <= xnor_fu_272_p2(14 downto 14);
    tmp_14_fu_454_p3 <= xnor_fu_272_p2(15 downto 15);
    tmp_15_fu_589_p3 <= xnor_1_fu_575_p2(1 downto 1);
    tmp_16_fu_601_p3 <= xnor_1_fu_575_p2(2 downto 2);
    tmp_17_fu_613_p3 <= xnor_1_fu_575_p2(3 downto 3);
    tmp_18_fu_625_p3 <= xnor_1_fu_575_p2(4 downto 4);
    tmp_19_fu_637_p3 <= xnor_1_fu_575_p2(5 downto 5);
    tmp_1_fu_298_p3 <= xnor_fu_272_p2(2 downto 2);
    tmp_20_fu_649_p3 <= xnor_1_fu_575_p2(6 downto 6);
    tmp_21_fu_661_p3 <= xnor_1_fu_575_p2(7 downto 7);
    tmp_22_fu_673_p3 <= xnor_1_fu_575_p2(8 downto 8);
    tmp_23_fu_685_p3 <= xnor_1_fu_575_p2(9 downto 9);
    tmp_24_fu_697_p3 <= xnor_1_fu_575_p2(10 downto 10);
    tmp_25_fu_709_p3 <= xnor_1_fu_575_p2(11 downto 11);
    tmp_26_fu_721_p3 <= xnor_1_fu_575_p2(12 downto 12);
    tmp_27_fu_733_p3 <= xnor_1_fu_575_p2(13 downto 13);
    tmp_28_fu_745_p3 <= xnor_1_fu_575_p2(14 downto 14);
    tmp_29_fu_757_p3 <= xnor_1_fu_575_p2(15 downto 15);
    tmp_2_fu_310_p3 <= xnor_fu_272_p2(3 downto 3);
    tmp_30_fu_892_p3 <= xnor_2_fu_878_p2(1 downto 1);
    tmp_31_fu_904_p3 <= xnor_2_fu_878_p2(2 downto 2);
    tmp_32_fu_916_p3 <= xnor_2_fu_878_p2(3 downto 3);
    tmp_33_fu_928_p3 <= xnor_2_fu_878_p2(4 downto 4);
    tmp_34_fu_940_p3 <= xnor_2_fu_878_p2(5 downto 5);
    tmp_35_fu_952_p3 <= xnor_2_fu_878_p2(6 downto 6);
    tmp_36_fu_964_p3 <= xnor_2_fu_878_p2(7 downto 7);
    tmp_37_fu_976_p3 <= xnor_2_fu_878_p2(8 downto 8);
    tmp_38_fu_988_p3 <= xnor_2_fu_878_p2(9 downto 9);
    tmp_39_fu_1000_p3 <= xnor_2_fu_878_p2(10 downto 10);
    tmp_3_fu_322_p3 <= xnor_fu_272_p2(4 downto 4);
    tmp_40_fu_1012_p3 <= xnor_2_fu_878_p2(11 downto 11);
    tmp_41_fu_1024_p3 <= xnor_2_fu_878_p2(12 downto 12);
    tmp_42_fu_1036_p3 <= xnor_2_fu_878_p2(13 downto 13);
    tmp_43_fu_1048_p3 <= xnor_2_fu_878_p2(14 downto 14);
    tmp_44_fu_1060_p3 <= xnor_2_fu_878_p2(15 downto 15);
    tmp_45_fu_1195_p3 <= xnor_3_fu_1181_p2(1 downto 1);
    tmp_46_fu_1207_p3 <= xnor_3_fu_1181_p2(2 downto 2);
    tmp_47_fu_1219_p3 <= xnor_3_fu_1181_p2(3 downto 3);
    tmp_48_fu_1231_p3 <= xnor_3_fu_1181_p2(4 downto 4);
    tmp_49_fu_1243_p3 <= xnor_3_fu_1181_p2(5 downto 5);
    tmp_4_fu_334_p3 <= xnor_fu_272_p2(5 downto 5);
    tmp_50_fu_1255_p3 <= xnor_3_fu_1181_p2(6 downto 6);
    tmp_51_fu_1267_p3 <= xnor_3_fu_1181_p2(7 downto 7);
    tmp_52_fu_1279_p3 <= xnor_3_fu_1181_p2(8 downto 8);
    tmp_53_fu_1291_p3 <= xnor_3_fu_1181_p2(9 downto 9);
    tmp_54_fu_1303_p3 <= xnor_3_fu_1181_p2(10 downto 10);
    tmp_55_fu_1315_p3 <= xnor_3_fu_1181_p2(11 downto 11);
    tmp_56_fu_1327_p3 <= xnor_3_fu_1181_p2(12 downto 12);
    tmp_57_fu_1339_p3 <= xnor_3_fu_1181_p2(13 downto 13);
    tmp_58_fu_1351_p3 <= xnor_3_fu_1181_p2(14 downto 14);
    tmp_59_fu_1363_p3 <= xnor_3_fu_1181_p2(15 downto 15);
    tmp_5_fu_346_p3 <= xnor_fu_272_p2(6 downto 6);
    tmp_6_fu_358_p3 <= xnor_fu_272_p2(7 downto 7);
    tmp_7_fu_370_p3 <= xnor_fu_272_p2(8 downto 8);
    tmp_8_fu_382_p3 <= xnor_fu_272_p2(9 downto 9);
    tmp_9_fu_394_p3 <= xnor_fu_272_p2(10 downto 10);
    tmp_fu_286_p3 <= xnor_fu_272_p2(1 downto 1);
    w3_address0 <= zext_ln60_3_fu_257_p1(6 - 1 downto 0);
    w3_address1 <= zext_ln60_2_fu_244_p1(6 - 1 downto 0);
    w3_address2 <= zext_ln60_1_fu_231_p1(6 - 1 downto 0);
    w3_address3 <= zext_ln60_fu_218_p1(6 - 1 downto 0);

    w3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            w3_ce0_local <= ap_const_logic_1;
        else 
            w3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    w3_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            w3_ce1_local <= ap_const_logic_1;
        else 
            w3_ce1_local <= ap_const_logic_0;
        end if; 
    end process;


    w3_ce2_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            w3_ce2_local <= ap_const_logic_1;
        else 
            w3_ce2_local <= ap_const_logic_0;
        end if; 
    end process;


    w3_ce3_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            w3_ce3_local <= ap_const_logic_1;
        else 
            w3_ce3_local <= ap_const_logic_0;
        end if; 
    end process;

    xnor_1_fu_575_p2 <= (xor_ln60_2_fu_570_p2 xor w3_q2);
    xnor_2_fu_878_p2 <= (xor_ln60_4_fu_873_p2 xor w3_q1);
    xnor_3_fu_1181_p2 <= (xor_ln60_6_fu_1176_p2 xor w3_q0);
    xnor_fu_272_p2 <= (xor_ln60_fu_267_p2 xor w3_q3);
    xor_ln60_2_fu_570_p2 <= (p_0_0271_1106_reload xor ap_const_lv16_FFFF);
    xor_ln60_4_fu_873_p2 <= (p_0_0271_2108_reload xor ap_const_lv16_FFFF);
    xor_ln60_6_fu_1176_p2 <= (p_0_0271_3110_reload xor ap_const_lv16_FFFF);
    xor_ln60_fu_267_p2 <= (p_0_0271104_reload xor ap_const_lv16_FFFF);
    ys_address0 <= zext_ln139_fu_1673_p1(4 - 1 downto 0);
    ys_ce0 <= ys_ce0_local;

    ys_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)))) then 
            ys_ce0_local <= ap_const_logic_1;
        else 
            ys_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    ys_d0 <= sext_ln142_fu_1690_p1;
    ys_we0 <= ys_we0_local;

    ys_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ys_we0_local <= ap_const_logic_1;
        else 
            ys_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln11_100_fu_1359_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_58_fu_1351_p3),2));
    zext_ln11_101_fu_1371_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_59_fu_1363_p3),2));
    zext_ln11_102_fu_1381_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_45_fu_1375_p2),3));
    zext_ln11_103_fu_1391_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_46_fu_1385_p2),3));
    zext_ln11_104_fu_1593_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_47_reg_1811),4));
    zext_ln11_105_fu_1407_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_48_fu_1401_p2),3));
    zext_ln11_106_fu_1417_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_49_fu_1411_p2),3));
    zext_ln11_107_fu_1596_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_50_reg_1816),4));
    zext_ln11_108_fu_1605_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_51_fu_1599_p2),5));
    zext_ln11_109_fu_1433_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_52_fu_1427_p2),3));
    zext_ln11_10_fu_414_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_10_fu_406_p3),2));
    zext_ln11_110_fu_1443_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_53_fu_1437_p2),3));
    zext_ln11_111_fu_1609_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_54_reg_1821),4));
    zext_ln11_112_fu_1459_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_55_fu_1453_p2),3));
    zext_ln11_113_fu_1469_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_56_fu_1463_p2),3));
    zext_ln11_114_fu_1612_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_57_reg_1826),4));
    zext_ln11_115_fu_1621_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_58_fu_1615_p2),5));
    zext_ln11_11_fu_426_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_11_fu_418_p3),2));
    zext_ln11_12_fu_438_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_12_fu_430_p3),2));
    zext_ln11_13_fu_450_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_13_fu_442_p3),2));
    zext_ln11_14_fu_462_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_14_fu_454_p3),2));
    zext_ln11_15_fu_472_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_fu_466_p2),3));
    zext_ln11_16_fu_482_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_1_fu_476_p2),3));
    zext_ln11_17_fu_1479_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_2_reg_1751),4));
    zext_ln11_18_fu_498_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_3_fu_492_p2),3));
    zext_ln11_19_fu_508_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_4_fu_502_p2),3));
    zext_ln11_1_fu_306_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_298_p3),2));
    zext_ln11_20_fu_1482_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_5_reg_1756),4));
    zext_ln11_21_fu_1491_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_6_fu_1485_p2),5));
    zext_ln11_22_fu_524_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_7_fu_518_p2),3));
    zext_ln11_23_fu_534_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_8_fu_528_p2),3));
    zext_ln11_24_fu_1495_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_9_reg_1761),4));
    zext_ln11_25_fu_550_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_10_fu_544_p2),3));
    zext_ln11_26_fu_560_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_11_fu_554_p2),3));
    zext_ln11_27_fu_1498_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_12_reg_1766),4));
    zext_ln11_28_fu_1507_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_13_fu_1501_p2),5));
    zext_ln11_29_fu_597_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_15_fu_589_p3),2));
    zext_ln11_2_fu_318_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_310_p3),2));
    zext_ln11_30_fu_609_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_16_fu_601_p3),2));
    zext_ln11_31_fu_621_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_17_fu_613_p3),2));
    zext_ln11_32_fu_633_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_18_fu_625_p3),2));
    zext_ln11_33_fu_645_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_19_fu_637_p3),2));
    zext_ln11_34_fu_657_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_20_fu_649_p3),2));
    zext_ln11_35_fu_669_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_21_fu_661_p3),2));
    zext_ln11_36_fu_681_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_22_fu_673_p3),2));
    zext_ln11_37_fu_693_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_23_fu_685_p3),2));
    zext_ln11_38_fu_705_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_24_fu_697_p3),2));
    zext_ln11_39_fu_717_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_25_fu_709_p3),2));
    zext_ln11_3_fu_330_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_322_p3),2));
    zext_ln11_40_fu_729_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_26_fu_721_p3),2));
    zext_ln11_41_fu_741_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_27_fu_733_p3),2));
    zext_ln11_42_fu_753_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_28_fu_745_p3),2));
    zext_ln11_43_fu_765_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_29_fu_757_p3),2));
    zext_ln11_44_fu_775_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_15_fu_769_p2),3));
    zext_ln11_45_fu_785_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_16_fu_779_p2),3));
    zext_ln11_46_fu_1517_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_17_reg_1771),4));
    zext_ln11_47_fu_801_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_18_fu_795_p2),3));
    zext_ln11_48_fu_811_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_19_fu_805_p2),3));
    zext_ln11_49_fu_1520_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_20_reg_1776),4));
    zext_ln11_4_fu_342_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_fu_334_p3),2));
    zext_ln11_50_fu_1529_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_21_fu_1523_p2),5));
    zext_ln11_51_fu_827_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_22_fu_821_p2),3));
    zext_ln11_52_fu_837_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_23_fu_831_p2),3));
    zext_ln11_53_fu_1533_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_24_reg_1781),4));
    zext_ln11_54_fu_853_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_25_fu_847_p2),3));
    zext_ln11_55_fu_863_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_26_fu_857_p2),3));
    zext_ln11_56_fu_1536_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_27_reg_1786),4));
    zext_ln11_57_fu_1545_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_28_fu_1539_p2),5));
    zext_ln11_58_fu_900_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_30_fu_892_p3),2));
    zext_ln11_59_fu_912_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_31_fu_904_p3),2));
    zext_ln11_5_fu_354_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_fu_346_p3),2));
    zext_ln11_60_fu_924_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_32_fu_916_p3),2));
    zext_ln11_61_fu_936_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_33_fu_928_p3),2));
    zext_ln11_62_fu_948_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_34_fu_940_p3),2));
    zext_ln11_63_fu_960_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_35_fu_952_p3),2));
    zext_ln11_64_fu_972_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_36_fu_964_p3),2));
    zext_ln11_65_fu_984_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_37_fu_976_p3),2));
    zext_ln11_66_fu_996_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_38_fu_988_p3),2));
    zext_ln11_67_fu_1008_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_39_fu_1000_p3),2));
    zext_ln11_68_fu_1020_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_40_fu_1012_p3),2));
    zext_ln11_69_fu_1032_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_41_fu_1024_p3),2));
    zext_ln11_6_fu_366_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_fu_358_p3),2));
    zext_ln11_70_fu_1044_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_42_fu_1036_p3),2));
    zext_ln11_71_fu_1056_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_43_fu_1048_p3),2));
    zext_ln11_72_fu_1068_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_44_fu_1060_p3),2));
    zext_ln11_73_fu_1078_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_30_fu_1072_p2),3));
    zext_ln11_74_fu_1088_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_31_fu_1082_p2),3));
    zext_ln11_75_fu_1555_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_32_reg_1791),4));
    zext_ln11_76_fu_1104_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_33_fu_1098_p2),3));
    zext_ln11_77_fu_1114_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_34_fu_1108_p2),3));
    zext_ln11_78_fu_1558_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_35_reg_1796),4));
    zext_ln11_79_fu_1567_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_36_fu_1561_p2),5));
    zext_ln11_7_fu_378_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_370_p3),2));
    zext_ln11_80_fu_1130_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_37_fu_1124_p2),3));
    zext_ln11_81_fu_1140_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_38_fu_1134_p2),3));
    zext_ln11_82_fu_1571_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_39_reg_1801),4));
    zext_ln11_83_fu_1156_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_40_fu_1150_p2),3));
    zext_ln11_84_fu_1166_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_41_fu_1160_p2),3));
    zext_ln11_85_fu_1574_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_42_reg_1806),4));
    zext_ln11_86_fu_1583_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln11_43_fu_1577_p2),5));
    zext_ln11_87_fu_1203_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_45_fu_1195_p3),2));
    zext_ln11_88_fu_1215_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_46_fu_1207_p3),2));
    zext_ln11_89_fu_1227_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_47_fu_1219_p3),2));
    zext_ln11_8_fu_390_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_fu_382_p3),2));
    zext_ln11_90_fu_1239_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_48_fu_1231_p3),2));
    zext_ln11_91_fu_1251_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_49_fu_1243_p3),2));
    zext_ln11_92_fu_1263_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_50_fu_1255_p3),2));
    zext_ln11_93_fu_1275_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_51_fu_1267_p3),2));
    zext_ln11_94_fu_1287_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_52_fu_1279_p3),2));
    zext_ln11_95_fu_1299_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_53_fu_1291_p3),2));
    zext_ln11_96_fu_1311_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_54_fu_1303_p3),2));
    zext_ln11_97_fu_1323_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_55_fu_1315_p3),2));
    zext_ln11_98_fu_1335_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_56_fu_1327_p3),2));
    zext_ln11_99_fu_1347_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_57_fu_1339_p3),2));
    zext_ln11_9_fu_402_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_fu_394_p3),2));
    zext_ln11_fu_294_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_286_p3),2));
    zext_ln139_fu_1673_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(n_1_reg_1722_pp0_iter2_reg),64));
    zext_ln60_1_fu_231_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln60_7_fu_223_p3),64));
    zext_ln60_2_fu_244_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln60_8_fu_236_p3),64));
    zext_ln60_3_fu_257_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln60_9_fu_249_p3),64));
    zext_ln60_fu_218_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln2_fu_210_p3),64));
    zext_ln61_1_fu_1635_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(cnt_3_fu_1549_p2),6));
    zext_ln61_2_fu_1639_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(cnt_5_fu_1587_p2),6));
    zext_ln61_fu_1631_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(cnt_1_fu_1511_p2),6));
    zext_ln64_1_fu_1653_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_fu_1647_p2),7));
    zext_ln64_2_fu_1663_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_1_fu_1657_p2),7));
    zext_ln64_fu_1643_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(cnt_7_fu_1625_p2),6));
    zext_ln8_1_fu_585_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(cnt_2_fu_581_p1),2));
    zext_ln8_2_fu_888_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(cnt_4_fu_884_p1),2));
    zext_ln8_3_fu_1191_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(cnt_6_fu_1187_p1),2));
    zext_ln8_fu_282_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(cnt_fu_278_p1),2));
end behav;
