// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module dft_sin_or_cos_double_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        t_in,
        do_cos,
        ap_return
);

parameter    ap_ST_fsm_state1 = 37'd1;
parameter    ap_ST_fsm_state2 = 37'd2;
parameter    ap_ST_fsm_state3 = 37'd4;
parameter    ap_ST_fsm_state4 = 37'd8;
parameter    ap_ST_fsm_state5 = 37'd16;
parameter    ap_ST_fsm_state6 = 37'd32;
parameter    ap_ST_fsm_state7 = 37'd64;
parameter    ap_ST_fsm_state8 = 37'd128;
parameter    ap_ST_fsm_state9 = 37'd256;
parameter    ap_ST_fsm_state10 = 37'd512;
parameter    ap_ST_fsm_state11 = 37'd1024;
parameter    ap_ST_fsm_state12 = 37'd2048;
parameter    ap_ST_fsm_state13 = 37'd4096;
parameter    ap_ST_fsm_state14 = 37'd8192;
parameter    ap_ST_fsm_state15 = 37'd16384;
parameter    ap_ST_fsm_state16 = 37'd32768;
parameter    ap_ST_fsm_state17 = 37'd65536;
parameter    ap_ST_fsm_state18 = 37'd131072;
parameter    ap_ST_fsm_state19 = 37'd262144;
parameter    ap_ST_fsm_state20 = 37'd524288;
parameter    ap_ST_fsm_state21 = 37'd1048576;
parameter    ap_ST_fsm_state22 = 37'd2097152;
parameter    ap_ST_fsm_state23 = 37'd4194304;
parameter    ap_ST_fsm_state24 = 37'd8388608;
parameter    ap_ST_fsm_state25 = 37'd16777216;
parameter    ap_ST_fsm_state26 = 37'd33554432;
parameter    ap_ST_fsm_state27 = 37'd67108864;
parameter    ap_ST_fsm_state28 = 37'd134217728;
parameter    ap_ST_fsm_state29 = 37'd268435456;
parameter    ap_ST_fsm_state30 = 37'd536870912;
parameter    ap_ST_fsm_state31 = 37'd1073741824;
parameter    ap_ST_fsm_state32 = 37'd2147483648;
parameter    ap_ST_fsm_state33 = 37'd4294967296;
parameter    ap_ST_fsm_state34 = 37'd8589934592;
parameter    ap_ST_fsm_state35 = 37'd17179869184;
parameter    ap_ST_fsm_state36 = 37'd34359738368;
parameter    ap_ST_fsm_state37 = 37'd68719476736;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] t_in;
input  [0:0] do_cos;
output  [63:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [36:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [3:0] ref_4oPi_table_256_address0;
wire   [255:0] ref_4oPi_table_256_q0;
wire   [7:0] fourth_order_double_sin_cos_K0_address0;
wire   [58:0] fourth_order_double_sin_cos_K0_q0;
wire   [7:0] fourth_order_double_sin_cos_K1_address0;
wire   [51:0] fourth_order_double_sin_cos_K1_q0;
wire   [7:0] fourth_order_double_sin_cos_K2_address0;
wire   [43:0] fourth_order_double_sin_cos_K2_q0;
wire   [7:0] fourth_order_double_sin_cos_K3_address0;
wire   [32:0] fourth_order_double_sin_cos_K3_q0;
wire   [7:0] fourth_order_double_sin_cos_K4_address0;
wire   [24:0] fourth_order_double_sin_cos_K4_q0;
reg   [0:0] din_sign_reg_1428;
wire   [10:0] din_exp_fu_457_p3;
reg   [10:0] din_exp_reg_1434;
wire   [51:0] din_sig_fu_465_p1;
reg   [51:0] din_sig_reg_1441;
wire   [0:0] closepath_fu_469_p2;
reg   [0:0] closepath_reg_1447;
wire   [6:0] trunc_ln398_fu_504_p1;
reg   [6:0] trunc_ln398_reg_1458;
reg   [255:0] table_256_reg_1463;
wire    ap_CS_fsm_state2;
reg  signed [169:0] ret_1_reg_1468;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire   [0:0] and_ln271_fu_546_p2;
reg   [0:0] and_ln271_reg_1478;
reg   [123:0] Mx_bits_reg_1485;
wire    ap_CS_fsm_state8;
reg   [2:0] trunc_ln_reg_1491;
wire   [2:0] k_fu_572_p3;
reg   [2:0] k_reg_1496;
wire    ap_CS_fsm_state9;
wire   [123:0] Mx_bits_3_fu_587_p3;
reg   [123:0] Mx_bits_3_reg_1501;
reg   [60:0] tmp_8_reg_1506;
wire   [0:0] tmp_1_fu_602_p19;
reg   [0:0] tmp_1_reg_1511;
wire    ap_CS_fsm_state10;
wire   [61:0] Mx_zeros_fu_661_p3;
reg   [61:0] Mx_zeros_reg_1523;
wire   [10:0] Ex_1_fu_673_p2;
reg   [10:0] Ex_1_reg_1528;
reg   [0:0] tmp_reg_1535;
wire   [0:0] sin_basis_fu_692_p3;
reg   [0:0] sin_basis_reg_1541;
wire   [0:0] cos_basis_fu_699_p3;
reg   [0:0] cos_basis_reg_1546;
wire   [0:0] icmp_ln282_fu_875_p2;
reg   [0:0] icmp_ln282_reg_1552;
wire   [0:0] results_sign_3_fu_892_p3;
reg   [0:0] results_sign_3_reg_1559;
reg   [62:0] Mx_reg_1564;
wire    ap_CS_fsm_state11;
wire   [10:0] sub_ln506_fu_917_p2;
reg   [10:0] sub_ln506_reg_1571;
reg   [6:0] tmp_5_reg_1576;
wire    ap_CS_fsm_state12;
wire   [55:0] B_fu_956_p1;
reg   [55:0] B_reg_1581;
reg   [48:0] B_trunc_reg_1586;
wire   [97:0] zext_ln25_fu_970_p1;
reg   [97:0] zext_ln25_reg_1591;
wire    ap_CS_fsm_state13;
wire   [63:0] zext_ln32_fu_981_p1;
reg   [63:0] zext_ln32_reg_1597;
wire    ap_CS_fsm_state16;
reg   [48:0] B_squared_reg_1614;
wire    ap_CS_fsm_state17;
reg  signed [51:0] fourth_order_double_sin_cos_K1_load_reg_1620;
reg  signed [43:0] fourth_order_double_sin_cos_K2_load_reg_1625;
wire   [97:0] zext_ln25_1_fu_997_p1;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state21;
reg   [58:0] fourth_order_double_sin_cos_K0_load_reg_1672;
wire    ap_CS_fsm_state22;
reg   [55:0] trunc_ln2_reg_1677;
reg   [47:0] trunc_ln3_reg_1682;
reg   [41:0] tmp_3_reg_1687;
reg   [32:0] fourth_order_double_sin_cos_K3_load_reg_1692;
reg   [34:0] tmp_4_reg_1697;
reg   [24:0] fourth_order_double_sin_cos_K4_load_reg_1702;
wire    ap_CS_fsm_state23;
wire   [63:0] add_ln37_1_fu_1098_p2;
reg   [63:0] add_ln37_1_reg_1727;
reg   [28:0] lshr_ln_reg_1732;
wire    ap_CS_fsm_state24;
reg   [36:0] tmp_6_reg_1737;
wire   [63:0] add_ln37_3_fu_1135_p2;
reg  signed [63:0] add_ln37_3_reg_1742;
wire    ap_CS_fsm_state25;
wire   [62:0] Mx_2_fu_1141_p3;
reg   [62:0] Mx_2_reg_1747;
wire    ap_CS_fsm_state26;
reg   [62:0] result_reg_1762;
wire    ap_CS_fsm_state30;
reg   [14:0] tmp_9_reg_1769;
wire   [31:0] out_bits_6_fu_1199_p3;
reg   [31:0] out_bits_6_reg_1792;
wire    ap_CS_fsm_state33;
wire   [0:0] icmp_ln433_fu_1223_p2;
reg   [0:0] icmp_ln433_reg_1809;
wire    ap_CS_fsm_state35;
wire    grp_sin_or_cos_double_Pipeline_1_fu_372_ap_start;
wire    grp_sin_or_cos_double_Pipeline_1_fu_372_ap_done;
wire    grp_sin_or_cos_double_Pipeline_1_fu_372_ap_idle;
wire    grp_sin_or_cos_double_Pipeline_1_fu_372_ap_ready;
wire   [31:0] grp_sin_or_cos_double_Pipeline_1_fu_372_out_bits_5_out;
wire    grp_sin_or_cos_double_Pipeline_1_fu_372_out_bits_5_out_ap_vld;
wire   [31:0] grp_sin_or_cos_double_Pipeline_1_fu_372_out_bits_4_out;
wire    grp_sin_or_cos_double_Pipeline_1_fu_372_out_bits_4_out_ap_vld;
wire   [31:0] grp_sin_or_cos_double_Pipeline_1_fu_372_out_bits_3_out;
wire    grp_sin_or_cos_double_Pipeline_1_fu_372_out_bits_3_out_ap_vld;
wire    grp_sin_or_cos_double_Pipeline_2_fu_379_ap_start;
wire    grp_sin_or_cos_double_Pipeline_2_fu_379_ap_done;
wire    grp_sin_or_cos_double_Pipeline_2_fu_379_ap_idle;
wire    grp_sin_or_cos_double_Pipeline_2_fu_379_ap_ready;
wire   [31:0] grp_sin_or_cos_double_Pipeline_2_fu_379_out_bits_9_out;
wire    grp_sin_or_cos_double_Pipeline_2_fu_379_out_bits_9_out_ap_vld;
wire   [31:0] grp_sin_or_cos_double_Pipeline_2_fu_379_out_bits_8_out;
wire    grp_sin_or_cos_double_Pipeline_2_fu_379_out_bits_8_out_ap_vld;
wire   [31:0] grp_sin_or_cos_double_Pipeline_2_fu_379_out_bits_7_out;
wire    grp_sin_or_cos_double_Pipeline_2_fu_379_out_bits_7_out_ap_vld;
wire    grp_sin_or_cos_double_Pipeline_3_fu_390_ap_start;
wire    grp_sin_or_cos_double_Pipeline_3_fu_390_ap_done;
wire    grp_sin_or_cos_double_Pipeline_3_fu_390_ap_idle;
wire    grp_sin_or_cos_double_Pipeline_3_fu_390_ap_ready;
wire   [31:0] grp_sin_or_cos_double_Pipeline_3_fu_390_c_3_out;
wire    grp_sin_or_cos_double_Pipeline_3_fu_390_c_3_out_ap_vld;
wire   [31:0] grp_sin_or_cos_double_Pipeline_3_fu_390_c_2_out;
wire    grp_sin_or_cos_double_Pipeline_3_fu_390_c_2_out_ap_vld;
wire   [31:0] grp_sin_or_cos_double_Pipeline_3_fu_390_c_1_out;
wire    grp_sin_or_cos_double_Pipeline_3_fu_390_c_1_out_ap_vld;
wire   [31:0] grp_sin_or_cos_double_Pipeline_3_fu_390_c_out;
wire    grp_sin_or_cos_double_Pipeline_3_fu_390_c_out_ap_vld;
wire    grp_sin_or_cos_double_Pipeline_4_fu_402_ap_start;
wire    grp_sin_or_cos_double_Pipeline_4_fu_402_ap_done;
wire    grp_sin_or_cos_double_Pipeline_4_fu_402_ap_idle;
wire    grp_sin_or_cos_double_Pipeline_4_fu_402_ap_ready;
wire   [31:0] grp_sin_or_cos_double_Pipeline_4_fu_402_shift_1_out;
wire    grp_sin_or_cos_double_Pipeline_4_fu_402_shift_1_out_ap_vld;
wire   [61:0] grp_sin_or_cos_double_Pipeline_4_fu_402_in_shift_out;
wire    grp_sin_or_cos_double_Pipeline_4_fu_402_in_shift_out_ap_vld;
reg    grp_sin_or_cos_double_Pipeline_1_fu_372_ap_start_reg;
reg   [31:0] out_bits_5_loc_fu_278;
reg   [31:0] out_bits_4_loc_fu_274;
reg   [31:0] out_bits_3_loc_fu_270;
reg    grp_sin_or_cos_double_Pipeline_2_fu_379_ap_start_reg;
wire    ap_CS_fsm_state31;
wire    ap_CS_fsm_state32;
reg    grp_sin_or_cos_double_Pipeline_3_fu_390_ap_start_reg;
wire    ap_CS_fsm_state34;
reg    grp_sin_or_cos_double_Pipeline_4_fu_402_ap_start_reg;
wire    ap_CS_fsm_state36;
wire   [63:0] zext_ln397_fu_499_p1;
wire    ap_CS_fsm_state37;
reg    ref_4oPi_table_256_ce0_local;
reg    fourth_order_double_sin_cos_K1_ce0_local;
reg    fourth_order_double_sin_cos_K2_ce0_local;
reg    fourth_order_double_sin_cos_K0_ce0_local;
reg    fourth_order_double_sin_cos_K3_ce0_local;
reg    fourth_order_double_sin_cos_K4_ce0_local;
wire   [34:0] grp_fu_413_p0;
wire   [24:0] grp_fu_413_p1;
wire   [41:0] grp_fu_417_p0;
wire   [32:0] grp_fu_417_p1;
wire   [48:0] grp_fu_421_p0;
reg   [48:0] grp_fu_425_p0;
reg   [48:0] grp_fu_425_p1;
wire   [48:0] grp_fu_429_p0;
wire   [48:0] grp_fu_429_p1;
wire   [55:0] grp_fu_433_p0;
wire   [62:0] grp_fu_437_p1;
wire   [52:0] grp_fu_441_p1;
wire   [63:0] data_fu_445_p1;
wire   [10:0] add_ln396_fu_475_p2;
wire   [10:0] addr_fu_481_p3;
wire   [3:0] tmp_2_fu_489_p4;
wire   [255:0] zext_ln398_fu_508_p1;
wire   [255:0] shl_ln398_fu_511_p2;
wire   [52:0] X_fu_524_p3;
wire   [0:0] icmp_ln271_fu_536_p2;
wire   [0:0] icmp_ln271_1_fu_541_p2;
wire   [169:0] grp_fu_441_p2;
wire   [0:0] trunc_ln491_fu_578_p1;
wire   [123:0] Mx_bits_1_fu_582_p2;
wire   [0:0] tmp_1_fu_602_p17;
wire   [10:0] add_ln454_fu_642_p2;
wire   [61:0] Mx_zeros_fu_661_p1;
wire   [10:0] Ex_fu_647_p3;
wire   [10:0] trunc_ln505_fu_669_p1;
wire   [0:0] xor_ln242_fu_687_p2;
wire   [0:0] tmp_s_fu_712_p33;
wire   [3:0] index_fu_706_p3;
wire   [0:0] tmp_10_fu_784_p33;
wire   [0:0] tmp_s_fu_712_p35;
wire   [0:0] tmp_10_fu_784_p35;
wire   [0:0] xor_ln278_fu_864_p2;
wire   [0:0] results_sign_fu_856_p3;
wire   [0:0] xor_ln282_fu_880_p2;
wire   [0:0] results_sign_2_fu_870_p2;
wire   [0:0] results_sign_4_fu_886_p2;
wire   [123:0] zext_ln504_fu_899_p1;
wire   [123:0] shl_ln504_fu_902_p2;
wire   [10:0] select_ln506_fu_922_p3;
wire   [62:0] zext_ln506_fu_927_p1;
wire   [62:0] lshr_ln506_fu_931_p2;
wire   [62:0] shl_ln506_fu_936_p2;
wire   [62:0] x_1_fu_941_p3;
wire   [7:0] A_fu_975_p3;
wire   [97:0] grp_fu_425_p2;
wire   [107:0] grp_fu_433_p2;
wire   [92:0] grp_fu_421_p2;
wire   [97:0] grp_fu_429_p2;
wire   [62:0] t1_fu_1059_p3;
wire  signed [63:0] sext_ln37_fu_1082_p1;
wire  signed [63:0] sext_ln37_1_fu_1086_p1;
wire   [63:0] add_ln37_fu_1089_p2;
wire  signed [63:0] sext_ln37_2_fu_1095_p1;
wire   [59:0] grp_fu_413_p2;
wire   [74:0] grp_fu_417_p2;
wire   [63:0] zext_ln37_1_fu_1124_p1;
wire   [63:0] add_ln37_2_fu_1127_p2;
wire   [63:0] zext_ln242_fu_1132_p1;
wire   [125:0] grp_fu_437_p2;
wire   [10:0] Ex_3_fu_1228_p3;
wire  signed [11:0] sext_ln252_fu_1234_p1;
wire   [11:0] add_ln432_fu_1244_p2;
wire  signed [31:0] sext_ln432_fu_1250_p1;
wire   [31:0] newexp_fu_1254_p2;
wire   [0:0] tmp_7_fu_1260_p3;
wire   [0:0] or_ln433_fu_1268_p2;
wire   [0:0] or_ln282_fu_1301_p2;
wire   [10:0] select_ln282_fu_1294_p3;
wire   [10:0] empty_fu_1273_p1;
wire   [51:0] select_ln282_2_fu_1314_p3;
wire   [51:0] phitmp_fu_1277_p4;
wire   [10:0] select_ln259_fu_1287_p3;
wire   [10:0] results_exp_fu_1306_p3;
wire   [51:0] results_sig_fu_1321_p3;
wire   [10:0] results_exp_1_fu_1329_p3;
wire   [51:0] results_sig_1_fu_1336_p3;
wire   [63:0] t_2_fu_1343_p4;
reg   [36:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
reg    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
reg    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
reg    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire   [59:0] grp_fu_413_p00;
wire   [59:0] grp_fu_413_p10;
wire   [74:0] grp_fu_417_p00;
wire   [74:0] grp_fu_417_p10;
wire   [92:0] grp_fu_421_p00;
wire   [107:0] grp_fu_433_p00;
wire   [125:0] grp_fu_437_p10;
wire   [169:0] grp_fu_441_p10;
wire   [2:0] tmp_1_fu_602_p1;
wire   [2:0] tmp_1_fu_602_p3;
wire   [2:0] tmp_1_fu_602_p5;
wire   [2:0] tmp_1_fu_602_p7;
wire  signed [2:0] tmp_1_fu_602_p9;
wire  signed [2:0] tmp_1_fu_602_p11;
wire  signed [2:0] tmp_1_fu_602_p13;
wire  signed [2:0] tmp_1_fu_602_p15;
wire   [61:0] Mx_zeros_fu_661_p0;
wire   [0:0] Mx_zeros_fu_661_p2;
wire   [3:0] tmp_s_fu_712_p1;
wire   [3:0] tmp_s_fu_712_p3;
wire   [3:0] tmp_s_fu_712_p5;
wire   [3:0] tmp_s_fu_712_p7;
wire   [3:0] tmp_s_fu_712_p9;
wire   [3:0] tmp_s_fu_712_p11;
wire   [3:0] tmp_s_fu_712_p13;
wire   [3:0] tmp_s_fu_712_p15;
wire  signed [3:0] tmp_s_fu_712_p17;
wire  signed [3:0] tmp_s_fu_712_p19;
wire  signed [3:0] tmp_s_fu_712_p21;
wire  signed [3:0] tmp_s_fu_712_p23;
wire  signed [3:0] tmp_s_fu_712_p25;
wire  signed [3:0] tmp_s_fu_712_p27;
wire  signed [3:0] tmp_s_fu_712_p29;
wire  signed [3:0] tmp_s_fu_712_p31;
wire   [3:0] tmp_10_fu_784_p1;
wire   [3:0] tmp_10_fu_784_p3;
wire   [3:0] tmp_10_fu_784_p5;
wire   [3:0] tmp_10_fu_784_p7;
wire   [3:0] tmp_10_fu_784_p9;
wire   [3:0] tmp_10_fu_784_p11;
wire   [3:0] tmp_10_fu_784_p13;
wire   [3:0] tmp_10_fu_784_p15;
wire  signed [3:0] tmp_10_fu_784_p17;
wire  signed [3:0] tmp_10_fu_784_p19;
wire  signed [3:0] tmp_10_fu_784_p21;
wire  signed [3:0] tmp_10_fu_784_p23;
wire  signed [3:0] tmp_10_fu_784_p25;
wire  signed [3:0] tmp_10_fu_784_p27;
wire  signed [3:0] tmp_10_fu_784_p29;
wire  signed [3:0] tmp_10_fu_784_p31;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 37'd1;
#0 grp_sin_or_cos_double_Pipeline_1_fu_372_ap_start_reg = 1'b0;
#0 grp_sin_or_cos_double_Pipeline_2_fu_379_ap_start_reg = 1'b0;
#0 grp_sin_or_cos_double_Pipeline_3_fu_390_ap_start_reg = 1'b0;
#0 grp_sin_or_cos_double_Pipeline_4_fu_402_ap_start_reg = 1'b0;
end

dft_sin_or_cos_double_s_ref_4oPi_table_256_ROM_AUTO_1R #(
    .DataWidth( 256 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
ref_4oPi_table_256_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(ref_4oPi_table_256_address0),
    .ce0(ref_4oPi_table_256_ce0_local),
    .q0(ref_4oPi_table_256_q0)
);

dft_sin_or_cos_double_s_fourth_order_double_sin_cos_K0_ROM_1P_LUTRAM_1R #(
    .DataWidth( 59 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
fourth_order_double_sin_cos_K0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fourth_order_double_sin_cos_K0_address0),
    .ce0(fourth_order_double_sin_cos_K0_ce0_local),
    .q0(fourth_order_double_sin_cos_K0_q0)
);

dft_sin_or_cos_double_s_fourth_order_double_sin_cos_K1_ROM_1P_LUTRAM_1R #(
    .DataWidth( 52 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
fourth_order_double_sin_cos_K1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fourth_order_double_sin_cos_K1_address0),
    .ce0(fourth_order_double_sin_cos_K1_ce0_local),
    .q0(fourth_order_double_sin_cos_K1_q0)
);

dft_sin_or_cos_double_s_fourth_order_double_sin_cos_K2_ROM_1P_LUTRAM_1R #(
    .DataWidth( 44 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
fourth_order_double_sin_cos_K2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fourth_order_double_sin_cos_K2_address0),
    .ce0(fourth_order_double_sin_cos_K2_ce0_local),
    .q0(fourth_order_double_sin_cos_K2_q0)
);

dft_sin_or_cos_double_s_fourth_order_double_sin_cos_K3_ROM_1P_LUTRAM_1R #(
    .DataWidth( 33 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
fourth_order_double_sin_cos_K3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fourth_order_double_sin_cos_K3_address0),
    .ce0(fourth_order_double_sin_cos_K3_ce0_local),
    .q0(fourth_order_double_sin_cos_K3_q0)
);

dft_sin_or_cos_double_s_fourth_order_double_sin_cos_K4_ROM_1P_LUTRAM_1R #(
    .DataWidth( 25 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
fourth_order_double_sin_cos_K4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fourth_order_double_sin_cos_K4_address0),
    .ce0(fourth_order_double_sin_cos_K4_ce0_local),
    .q0(fourth_order_double_sin_cos_K4_q0)
);

dft_sin_or_cos_double_Pipeline_1 grp_sin_or_cos_double_Pipeline_1_fu_372(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sin_or_cos_double_Pipeline_1_fu_372_ap_start),
    .ap_done(grp_sin_or_cos_double_Pipeline_1_fu_372_ap_done),
    .ap_idle(grp_sin_or_cos_double_Pipeline_1_fu_372_ap_idle),
    .ap_ready(grp_sin_or_cos_double_Pipeline_1_fu_372_ap_ready),
    .out_bits_5_out(grp_sin_or_cos_double_Pipeline_1_fu_372_out_bits_5_out),
    .out_bits_5_out_ap_vld(grp_sin_or_cos_double_Pipeline_1_fu_372_out_bits_5_out_ap_vld),
    .out_bits_4_out(grp_sin_or_cos_double_Pipeline_1_fu_372_out_bits_4_out),
    .out_bits_4_out_ap_vld(grp_sin_or_cos_double_Pipeline_1_fu_372_out_bits_4_out_ap_vld),
    .out_bits_3_out(grp_sin_or_cos_double_Pipeline_1_fu_372_out_bits_3_out),
    .out_bits_3_out_ap_vld(grp_sin_or_cos_double_Pipeline_1_fu_372_out_bits_3_out_ap_vld)
);

dft_sin_or_cos_double_Pipeline_2 grp_sin_or_cos_double_Pipeline_2_fu_379(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sin_or_cos_double_Pipeline_2_fu_379_ap_start),
    .ap_done(grp_sin_or_cos_double_Pipeline_2_fu_379_ap_done),
    .ap_idle(grp_sin_or_cos_double_Pipeline_2_fu_379_ap_idle),
    .ap_ready(grp_sin_or_cos_double_Pipeline_2_fu_379_ap_ready),
    .out_bits_5_reload(out_bits_5_loc_fu_278),
    .out_bits_4_reload(out_bits_4_loc_fu_274),
    .out_bits_3_reload(out_bits_3_loc_fu_270),
    .result(result_reg_1762),
    .out_bits_9_out(grp_sin_or_cos_double_Pipeline_2_fu_379_out_bits_9_out),
    .out_bits_9_out_ap_vld(grp_sin_or_cos_double_Pipeline_2_fu_379_out_bits_9_out_ap_vld),
    .out_bits_8_out(grp_sin_or_cos_double_Pipeline_2_fu_379_out_bits_8_out),
    .out_bits_8_out_ap_vld(grp_sin_or_cos_double_Pipeline_2_fu_379_out_bits_8_out_ap_vld),
    .out_bits_7_out(grp_sin_or_cos_double_Pipeline_2_fu_379_out_bits_7_out),
    .out_bits_7_out_ap_vld(grp_sin_or_cos_double_Pipeline_2_fu_379_out_bits_7_out_ap_vld)
);

dft_sin_or_cos_double_Pipeline_3 grp_sin_or_cos_double_Pipeline_3_fu_390(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sin_or_cos_double_Pipeline_3_fu_390_ap_start),
    .ap_done(grp_sin_or_cos_double_Pipeline_3_fu_390_ap_done),
    .ap_idle(grp_sin_or_cos_double_Pipeline_3_fu_390_ap_idle),
    .ap_ready(grp_sin_or_cos_double_Pipeline_3_fu_390_ap_ready),
    .out_bits_7_reload(grp_sin_or_cos_double_Pipeline_2_fu_379_out_bits_7_out),
    .out_bits_8_reload(grp_sin_or_cos_double_Pipeline_2_fu_379_out_bits_8_out),
    .out_bits_9_reload(grp_sin_or_cos_double_Pipeline_2_fu_379_out_bits_9_out),
    .out_bits_6(out_bits_6_reg_1792),
    .c_3_out(grp_sin_or_cos_double_Pipeline_3_fu_390_c_3_out),
    .c_3_out_ap_vld(grp_sin_or_cos_double_Pipeline_3_fu_390_c_3_out_ap_vld),
    .c_2_out(grp_sin_or_cos_double_Pipeline_3_fu_390_c_2_out),
    .c_2_out_ap_vld(grp_sin_or_cos_double_Pipeline_3_fu_390_c_2_out_ap_vld),
    .c_1_out(grp_sin_or_cos_double_Pipeline_3_fu_390_c_1_out),
    .c_1_out_ap_vld(grp_sin_or_cos_double_Pipeline_3_fu_390_c_1_out_ap_vld),
    .c_out(grp_sin_or_cos_double_Pipeline_3_fu_390_c_out),
    .c_out_ap_vld(grp_sin_or_cos_double_Pipeline_3_fu_390_c_out_ap_vld)
);

dft_sin_or_cos_double_Pipeline_4 grp_sin_or_cos_double_Pipeline_4_fu_402(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sin_or_cos_double_Pipeline_4_fu_402_ap_start),
    .ap_done(grp_sin_or_cos_double_Pipeline_4_fu_402_ap_done),
    .ap_idle(grp_sin_or_cos_double_Pipeline_4_fu_402_ap_idle),
    .ap_ready(grp_sin_or_cos_double_Pipeline_4_fu_402_ap_ready),
    .result(result_reg_1762),
    .c_reload(grp_sin_or_cos_double_Pipeline_3_fu_390_c_out),
    .c_1_reload(grp_sin_or_cos_double_Pipeline_3_fu_390_c_1_out),
    .c_2_reload(grp_sin_or_cos_double_Pipeline_3_fu_390_c_2_out),
    .c_3_reload(grp_sin_or_cos_double_Pipeline_3_fu_390_c_3_out),
    .shift_1_out(grp_sin_or_cos_double_Pipeline_4_fu_402_shift_1_out),
    .shift_1_out_ap_vld(grp_sin_or_cos_double_Pipeline_4_fu_402_shift_1_out_ap_vld),
    .in_shift_out(grp_sin_or_cos_double_Pipeline_4_fu_402_in_shift_out),
    .in_shift_out_ap_vld(grp_sin_or_cos_double_Pipeline_4_fu_402_in_shift_out_ap_vld)
);

dft_mul_35ns_25ns_60_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 35 ),
    .din1_WIDTH( 25 ),
    .dout_WIDTH( 60 ))
mul_35ns_25ns_60_2_1_U35(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_413_p0),
    .din1(grp_fu_413_p1),
    .ce(1'b1),
    .dout(grp_fu_413_p2)
);

dft_mul_42ns_33ns_75_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 42 ),
    .din1_WIDTH( 33 ),
    .dout_WIDTH( 75 ))
mul_42ns_33ns_75_2_1_U36(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_417_p0),
    .din1(grp_fu_417_p1),
    .ce(1'b1),
    .dout(grp_fu_417_p2)
);

dft_mul_49ns_44s_93_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 49 ),
    .din1_WIDTH( 44 ),
    .dout_WIDTH( 93 ))
mul_49ns_44s_93_5_1_U37(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_421_p0),
    .din1(fourth_order_double_sin_cos_K2_load_reg_1625),
    .ce(1'b1),
    .dout(grp_fu_421_p2)
);

dft_mul_49ns_49ns_98_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 49 ),
    .din1_WIDTH( 49 ),
    .dout_WIDTH( 98 ))
mul_49ns_49ns_98_5_1_U38(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_425_p0),
    .din1(grp_fu_425_p1),
    .ce(1'b1),
    .dout(grp_fu_425_p2)
);

dft_mul_49ns_49ns_98_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 49 ),
    .din1_WIDTH( 49 ),
    .dout_WIDTH( 98 ))
mul_49ns_49ns_98_5_1_U39(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_429_p0),
    .din1(grp_fu_429_p1),
    .ce(1'b1),
    .dout(grp_fu_429_p2)
);

dft_mul_56ns_52s_108_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 56 ),
    .din1_WIDTH( 52 ),
    .dout_WIDTH( 108 ))
mul_56ns_52s_108_5_1_U40(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_433_p0),
    .din1(fourth_order_double_sin_cos_K1_load_reg_1620),
    .ce(1'b1),
    .dout(grp_fu_433_p2)
);

dft_mul_64s_63ns_126_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 63 ),
    .dout_WIDTH( 126 ))
mul_64s_63ns_126_5_1_U41(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln37_3_reg_1742),
    .din1(grp_fu_437_p1),
    .ce(1'b1),
    .dout(grp_fu_437_p2)
);

dft_mul_170s_53ns_170_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 170 ),
    .din1_WIDTH( 53 ),
    .dout_WIDTH( 170 ))
mul_170s_53ns_170_5_1_U42(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ret_1_reg_1468),
    .din1(grp_fu_441_p1),
    .ce(1'b1),
    .dout(grp_fu_441_p2)
);

(* dissolve_hierarchy = "yes" *) dft_sparsemux_17_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_17_3_1_1_1_U43(
    .din0(1'd0),
    .din1(1'd1),
    .din2(1'd1),
    .din3(1'd0),
    .din4(1'd0),
    .din5(1'd1),
    .din6(1'd1),
    .din7(1'd0),
    .def(tmp_1_fu_602_p17),
    .sel(k_fu_572_p3),
    .dout(tmp_1_fu_602_p19)
);

dft_ctlz_62_62_1_1 #(
    .din_WIDTH( 62 ),
    .dout_WIDTH( 62 ))
ctlz_62_62_1_1_U44(
    .din(Mx_zeros_fu_661_p1),
    .dout(Mx_zeros_fu_661_p3)
);

(* dissolve_hierarchy = "yes" *) dft_sparsemux_33_4_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 1 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 1 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 1 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 1 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 1 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 1 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 1 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 1 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
sparsemux_33_4_1_1_1_U45(
    .din0(1'd0),
    .din1(1'd0),
    .din2(1'd0),
    .din3(1'd1),
    .din4(1'd1),
    .din5(1'd1),
    .din6(1'd1),
    .din7(1'd0),
    .din8(1'd0),
    .din9(1'd1),
    .din10(1'd1),
    .din11(1'd1),
    .din12(1'd1),
    .din13(1'd0),
    .din14(1'd0),
    .din15(1'd0),
    .def(tmp_s_fu_712_p33),
    .sel(index_fu_706_p3),
    .dout(tmp_s_fu_712_p35)
);

(* dissolve_hierarchy = "yes" *) dft_sparsemux_33_4_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 1 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 1 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 1 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 1 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 1 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 1 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 1 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 1 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
sparsemux_33_4_1_1_1_U46(
    .din0(1'd0),
    .din1(1'd0),
    .din2(1'd1),
    .din3(1'd0),
    .din4(1'd1),
    .din5(1'd1),
    .din6(1'd0),
    .din7(1'd1),
    .din8(1'd1),
    .din9(1'd0),
    .din10(1'd1),
    .din11(1'd1),
    .din12(1'd0),
    .din13(1'd1),
    .din14(1'd0),
    .din15(1'd0),
    .def(tmp_10_fu_784_p33),
    .sel(index_fu_706_p3),
    .dout(tmp_10_fu_784_p35)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sin_or_cos_double_Pipeline_1_fu_372_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_sin_or_cos_double_Pipeline_1_fu_372_ap_start_reg <= 1'b1;
        end else if ((grp_sin_or_cos_double_Pipeline_1_fu_372_ap_ready == 1'b1)) begin
            grp_sin_or_cos_double_Pipeline_1_fu_372_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sin_or_cos_double_Pipeline_2_fu_379_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state31)) begin
            grp_sin_or_cos_double_Pipeline_2_fu_379_ap_start_reg <= 1'b1;
        end else if ((grp_sin_or_cos_double_Pipeline_2_fu_379_ap_ready == 1'b1)) begin
            grp_sin_or_cos_double_Pipeline_2_fu_379_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sin_or_cos_double_Pipeline_3_fu_390_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state33)) begin
            grp_sin_or_cos_double_Pipeline_3_fu_390_ap_start_reg <= 1'b1;
        end else if ((grp_sin_or_cos_double_Pipeline_3_fu_390_ap_ready == 1'b1)) begin
            grp_sin_or_cos_double_Pipeline_3_fu_390_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sin_or_cos_double_Pipeline_4_fu_402_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state35)) begin
            grp_sin_or_cos_double_Pipeline_4_fu_402_ap_start_reg <= 1'b1;
        end else if ((grp_sin_or_cos_double_Pipeline_4_fu_402_ap_ready == 1'b1)) begin
            grp_sin_or_cos_double_Pipeline_4_fu_402_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        B_reg_1581 <= B_fu_956_p1;
        B_trunc_reg_1586 <= {{x_1_fu_941_p3[55:7]}};
        tmp_5_reg_1576 <= {{x_1_fu_941_p3[62:56]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        B_squared_reg_1614 <= {{grp_fu_425_p2[97:49]}};
        fourth_order_double_sin_cos_K1_load_reg_1620 <= fourth_order_double_sin_cos_K1_q0;
        fourth_order_double_sin_cos_K2_load_reg_1625 <= fourth_order_double_sin_cos_K2_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        Ex_1_reg_1528 <= Ex_1_fu_673_p2;
        Mx_zeros_reg_1523 <= Mx_zeros_fu_661_p3;
        cos_basis_reg_1546 <= cos_basis_fu_699_p3;
        icmp_ln282_reg_1552 <= icmp_ln282_fu_875_p2;
        results_sign_3_reg_1559 <= results_sign_3_fu_892_p3;
        sin_basis_reg_1541 <= sin_basis_fu_692_p3;
        tmp_reg_1535 <= Ex_1_fu_673_p2[32'd10];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        Mx_2_reg_1747 <= Mx_2_fu_1141_p3;
        add_ln37_3_reg_1742 <= add_ln37_3_fu_1135_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        Mx_bits_3_reg_1501 <= Mx_bits_3_fu_587_p3;
        k_reg_1496 <= k_fu_572_p3;
        tmp_1_reg_1511 <= tmp_1_fu_602_p19;
        tmp_8_reg_1506 <= {{Mx_bits_3_fu_587_p3[123:63]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        Mx_bits_reg_1485 <= {{grp_fu_441_p2[166:43]}};
        trunc_ln_reg_1491 <= {{grp_fu_441_p2[169:167]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        Mx_reg_1564 <= {{shl_ln504_fu_902_p2[123:61]}};
        sub_ln506_reg_1571 <= sub_ln506_fu_917_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        add_ln37_1_reg_1727 <= add_ln37_1_fu_1098_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        and_ln271_reg_1478 <= and_ln271_fu_546_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        closepath_reg_1447 <= closepath_fu_469_p2;
        din_exp_reg_1434 <= {{data_fu_445_p1[62:52]}};
        din_sig_reg_1441 <= din_sig_fu_465_p1;
        din_sign_reg_1428 <= data_fu_445_p1[32'd63];
        trunc_ln398_reg_1458 <= trunc_ln398_fu_504_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        fourth_order_double_sin_cos_K0_load_reg_1672 <= fourth_order_double_sin_cos_K0_q0;
        fourth_order_double_sin_cos_K3_load_reg_1692 <= fourth_order_double_sin_cos_K3_q0;
        fourth_order_double_sin_cos_K4_load_reg_1702 <= fourth_order_double_sin_cos_K4_q0;
        tmp_3_reg_1687 <= {{grp_fu_425_p2[97:56]}};
        tmp_4_reg_1697 <= {{grp_fu_429_p2[97:63]}};
        trunc_ln2_reg_1677 <= {{grp_fu_433_p2[107:52]}};
        trunc_ln3_reg_1682 <= {{grp_fu_421_p2[92:45]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        icmp_ln433_reg_1809 <= icmp_ln433_fu_1223_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        lshr_ln_reg_1732 <= {{grp_fu_413_p2[59:31]}};
        tmp_6_reg_1737 <= {{grp_fu_417_p2[74:38]}};
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sin_or_cos_double_Pipeline_1_fu_372_out_bits_3_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        out_bits_3_loc_fu_270 <= grp_sin_or_cos_double_Pipeline_1_fu_372_out_bits_3_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sin_or_cos_double_Pipeline_1_fu_372_out_bits_4_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        out_bits_4_loc_fu_274 <= grp_sin_or_cos_double_Pipeline_1_fu_372_out_bits_4_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sin_or_cos_double_Pipeline_1_fu_372_out_bits_5_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        out_bits_5_loc_fu_278 <= grp_sin_or_cos_double_Pipeline_1_fu_372_out_bits_5_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        out_bits_6_reg_1792[31 : 17] <= out_bits_6_fu_1199_p3[31 : 17];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        result_reg_1762 <= {{grp_fu_437_p2[125:63]}};
        tmp_9_reg_1769 <= {{grp_fu_437_p2[77:63]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ret_1_reg_1468 <= {{shl_ln398_fu_511_p2[255:86]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        table_256_reg_1463 <= ref_4oPi_table_256_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        zext_ln25_reg_1591[48 : 0] <= zext_ln25_fu_970_p1[48 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        zext_ln32_reg_1597[7 : 0] <= zext_ln32_fu_981_p1[7 : 0];
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

always @ (*) begin
    if ((grp_sin_or_cos_double_Pipeline_1_fu_372_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

always @ (*) begin
    if ((grp_sin_or_cos_double_Pipeline_2_fu_379_ap_done == 1'b0)) begin
        ap_ST_fsm_state32_blk = 1'b1;
    end else begin
        ap_ST_fsm_state32_blk = 1'b0;
    end
end

assign ap_ST_fsm_state33_blk = 1'b0;

always @ (*) begin
    if ((grp_sin_or_cos_double_Pipeline_3_fu_390_ap_done == 1'b0)) begin
        ap_ST_fsm_state34_blk = 1'b1;
    end else begin
        ap_ST_fsm_state34_blk = 1'b0;
    end
end

assign ap_ST_fsm_state35_blk = 1'b0;

always @ (*) begin
    if ((grp_sin_or_cos_double_Pipeline_4_fu_402_ap_done == 1'b0)) begin
        ap_ST_fsm_state36_blk = 1'b1;
    end else begin
        ap_ST_fsm_state36_blk = 1'b0;
    end
end

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state37) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        fourth_order_double_sin_cos_K0_ce0_local = 1'b1;
    end else begin
        fourth_order_double_sin_cos_K0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        fourth_order_double_sin_cos_K1_ce0_local = 1'b1;
    end else begin
        fourth_order_double_sin_cos_K1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        fourth_order_double_sin_cos_K2_ce0_local = 1'b1;
    end else begin
        fourth_order_double_sin_cos_K2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        fourth_order_double_sin_cos_K3_ce0_local = 1'b1;
    end else begin
        fourth_order_double_sin_cos_K3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        fourth_order_double_sin_cos_K4_ce0_local = 1'b1;
    end else begin
        fourth_order_double_sin_cos_K4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_425_p0 = zext_ln25_1_fu_997_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_425_p0 = zext_ln25_fu_970_p1;
    end else begin
        grp_fu_425_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_425_p1 = zext_ln25_reg_1591;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_425_p1 = zext_ln25_fu_970_p1;
    end else begin
        grp_fu_425_p1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ref_4oPi_table_256_ce0_local = 1'b1;
    end else begin
        ref_4oPi_table_256_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_sin_or_cos_double_Pipeline_1_fu_372_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            if (((grp_sin_or_cos_double_Pipeline_2_fu_379_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state32))) begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            if (((grp_sin_or_cos_double_Pipeline_3_fu_390_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state34))) begin
                ap_NS_fsm = ap_ST_fsm_state35;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            if (((grp_sin_or_cos_double_Pipeline_4_fu_402_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state36))) begin
                ap_NS_fsm = ap_ST_fsm_state37;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state36;
            end
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_fu_975_p3 = {{sin_basis_reg_1541}, {tmp_5_reg_1576}};

assign B_fu_956_p1 = x_1_fu_941_p3[55:0];

assign Ex_1_fu_673_p2 = (Ex_fu_647_p3 - trunc_ln505_fu_669_p1);

assign Ex_3_fu_1228_p3 = ((cos_basis_reg_1546[0:0] == 1'b1) ? 11'd0 : Ex_1_reg_1528);

assign Ex_fu_647_p3 = ((closepath_reg_1447[0:0] == 1'b1) ? add_ln454_fu_642_p2 : 11'd0);

assign Mx_2_fu_1141_p3 = ((cos_basis_reg_1546[0:0] == 1'b1) ? 63'd9223372036854775807 : Mx_reg_1564);

assign Mx_bits_1_fu_582_p2 = (124'd0 - Mx_bits_reg_1485);

assign Mx_bits_3_fu_587_p3 = ((trunc_ln491_fu_578_p1[0:0] == 1'b1) ? Mx_bits_1_fu_582_p2 : Mx_bits_reg_1485);

assign Mx_zeros_fu_661_p1 = {{tmp_8_reg_1506}, {1'd1}};

assign X_fu_524_p3 = {{1'd1}, {din_sig_reg_1441}};

assign add_ln37_1_fu_1098_p2 = ($signed(add_ln37_fu_1089_p2) + $signed(sext_ln37_2_fu_1095_p1));

assign add_ln37_2_fu_1127_p2 = (add_ln37_1_reg_1727 + zext_ln37_1_fu_1124_p1);

assign add_ln37_3_fu_1135_p2 = (add_ln37_2_fu_1127_p2 + zext_ln242_fu_1132_p1);

assign add_ln37_fu_1089_p2 = ($signed(sext_ln37_fu_1082_p1) + $signed(sext_ln37_1_fu_1086_p1));

assign add_ln396_fu_475_p2 = ($signed(din_exp_fu_457_p3) + $signed(11'd1101));

assign add_ln432_fu_1244_p2 = ($signed(sext_ln252_fu_1234_p1) + $signed(12'd1023));

assign add_ln454_fu_642_p2 = ($signed(din_exp_reg_1434) + $signed(11'd1027));

assign addr_fu_481_p3 = ((closepath_fu_469_p2[0:0] == 1'b1) ? 11'd74 : add_ln396_fu_475_p2);

assign and_ln271_fu_546_p2 = (icmp_ln271_fu_536_p2 & icmp_ln271_1_fu_541_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_return = t_2_fu_1343_p4;

assign closepath_fu_469_p2 = ((din_exp_fu_457_p3 < 11'd1022) ? 1'b1 : 1'b0);

assign cos_basis_fu_699_p3 = ((do_cos[0:0] == 1'b1) ? xor_ln242_fu_687_p2 : tmp_1_reg_1511);

assign data_fu_445_p1 = t_in;

assign din_exp_fu_457_p3 = {{data_fu_445_p1[62:52]}};

assign din_sig_fu_465_p1 = data_fu_445_p1[51:0];

assign empty_fu_1273_p1 = newexp_fu_1254_p2[10:0];

assign fourth_order_double_sin_cos_K0_address0 = zext_ln32_reg_1597;

assign fourth_order_double_sin_cos_K1_address0 = zext_ln32_fu_981_p1;

assign fourth_order_double_sin_cos_K2_address0 = zext_ln32_fu_981_p1;

assign fourth_order_double_sin_cos_K3_address0 = zext_ln32_reg_1597;

assign fourth_order_double_sin_cos_K4_address0 = zext_ln32_reg_1597;

assign grp_fu_413_p0 = grp_fu_413_p00;

assign grp_fu_413_p00 = tmp_4_reg_1697;

assign grp_fu_413_p1 = grp_fu_413_p10;

assign grp_fu_413_p10 = fourth_order_double_sin_cos_K4_load_reg_1702;

assign grp_fu_417_p0 = grp_fu_417_p00;

assign grp_fu_417_p00 = tmp_3_reg_1687;

assign grp_fu_417_p1 = grp_fu_417_p10;

assign grp_fu_417_p10 = fourth_order_double_sin_cos_K3_load_reg_1692;

assign grp_fu_421_p0 = grp_fu_421_p00;

assign grp_fu_421_p00 = B_squared_reg_1614;

assign grp_fu_429_p0 = zext_ln25_1_fu_997_p1;

assign grp_fu_429_p1 = zext_ln25_1_fu_997_p1;

assign grp_fu_433_p0 = grp_fu_433_p00;

assign grp_fu_433_p00 = B_reg_1581;

assign grp_fu_437_p1 = grp_fu_437_p10;

assign grp_fu_437_p10 = Mx_2_reg_1747;

assign grp_fu_441_p1 = grp_fu_441_p10;

assign grp_fu_441_p10 = X_fu_524_p3;

assign grp_sin_or_cos_double_Pipeline_1_fu_372_ap_start = grp_sin_or_cos_double_Pipeline_1_fu_372_ap_start_reg;

assign grp_sin_or_cos_double_Pipeline_2_fu_379_ap_start = grp_sin_or_cos_double_Pipeline_2_fu_379_ap_start_reg;

assign grp_sin_or_cos_double_Pipeline_3_fu_390_ap_start = grp_sin_or_cos_double_Pipeline_3_fu_390_ap_start_reg;

assign grp_sin_or_cos_double_Pipeline_4_fu_402_ap_start = grp_sin_or_cos_double_Pipeline_4_fu_402_ap_start_reg;

assign icmp_ln271_1_fu_541_p2 = ((din_sig_reg_1441 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln271_fu_536_p2 = ((din_exp_reg_1434 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln282_fu_875_p2 = ((din_exp_reg_1434 == 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln433_fu_1223_p2 = ((result_reg_1762 == 63'd0) ? 1'b1 : 1'b0);

assign index_fu_706_p3 = {{din_sign_reg_1428}, {k_reg_1496}};

assign k_fu_572_p3 = ((closepath_reg_1447[0:0] == 1'b1) ? 3'd0 : trunc_ln_reg_1491);

assign lshr_ln506_fu_931_p2 = Mx_reg_1564 >> zext_ln506_fu_927_p1;

assign newexp_fu_1254_p2 = ($signed(sext_ln432_fu_1250_p1) - $signed(grp_sin_or_cos_double_Pipeline_4_fu_402_shift_1_out));

assign or_ln282_fu_1301_p2 = (or_ln433_fu_1268_p2 | icmp_ln282_reg_1552);

assign or_ln433_fu_1268_p2 = (tmp_7_fu_1260_p3 | icmp_ln433_reg_1809);

assign out_bits_6_fu_1199_p3 = {{tmp_9_reg_1769}, {17'd65536}};

assign phitmp_fu_1277_p4 = {{grp_sin_or_cos_double_Pipeline_4_fu_402_in_shift_out[61:10]}};

assign ref_4oPi_table_256_address0 = zext_ln397_fu_499_p1;

assign results_exp_1_fu_1329_p3 = ((and_ln271_reg_1478[0:0] == 1'b1) ? select_ln259_fu_1287_p3 : results_exp_fu_1306_p3);

assign results_exp_fu_1306_p3 = ((or_ln282_fu_1301_p2[0:0] == 1'b1) ? select_ln282_fu_1294_p3 : empty_fu_1273_p1);

assign results_sig_1_fu_1336_p3 = ((and_ln271_reg_1478[0:0] == 1'b1) ? 52'd0 : results_sig_fu_1321_p3);

assign results_sig_fu_1321_p3 = ((or_ln282_fu_1301_p2[0:0] == 1'b1) ? select_ln282_2_fu_1314_p3 : phitmp_fu_1277_p4);

assign results_sign_2_fu_870_p2 = (xor_ln278_fu_864_p2 & din_sign_reg_1428);

assign results_sign_3_fu_892_p3 = ((and_ln271_reg_1478[0:0] == 1'b1) ? results_sign_2_fu_870_p2 : results_sign_4_fu_886_p2);

assign results_sign_4_fu_886_p2 = (xor_ln282_fu_880_p2 & results_sign_fu_856_p3);

assign results_sign_fu_856_p3 = ((cos_basis_fu_699_p3[0:0] == 1'b1) ? tmp_s_fu_712_p35 : tmp_10_fu_784_p35);

assign select_ln259_fu_1287_p3 = ((do_cos[0:0] == 1'b1) ? 11'd1023 : 11'd0);

assign select_ln282_2_fu_1314_p3 = ((icmp_ln282_reg_1552[0:0] == 1'b1) ? 52'd4503599627370495 : 52'd0);

assign select_ln282_fu_1294_p3 = ((icmp_ln282_reg_1552[0:0] == 1'b1) ? 11'd2047 : 11'd0);

assign select_ln506_fu_922_p3 = ((tmp_reg_1535[0:0] == 1'b1) ? sub_ln506_reg_1571 : Ex_1_reg_1528);

assign sext_ln252_fu_1234_p1 = $signed(Ex_3_fu_1228_p3);

assign sext_ln37_1_fu_1086_p1 = $signed(trunc_ln2_reg_1677);

assign sext_ln37_2_fu_1095_p1 = $signed(trunc_ln3_reg_1682);

assign sext_ln37_fu_1082_p1 = $signed(t1_fu_1059_p3);

assign sext_ln432_fu_1250_p1 = $signed(add_ln432_fu_1244_p2);

assign shl_ln398_fu_511_p2 = table_256_reg_1463 << zext_ln398_fu_508_p1;

assign shl_ln504_fu_902_p2 = Mx_bits_3_reg_1501 << zext_ln504_fu_899_p1;

assign shl_ln506_fu_936_p2 = Mx_reg_1564 << zext_ln506_fu_927_p1;

assign sin_basis_fu_692_p3 = ((do_cos[0:0] == 1'b1) ? tmp_1_reg_1511 : xor_ln242_fu_687_p2);

assign sub_ln506_fu_917_p2 = (11'd0 - Ex_1_reg_1528);

assign t1_fu_1059_p3 = {{fourth_order_double_sin_cos_K0_load_reg_1672}, {4'd0}};

assign t_2_fu_1343_p4 = {{{results_sign_3_reg_1559}, {results_exp_1_fu_1329_p3}}, {results_sig_1_fu_1336_p3}};

assign tmp_10_fu_784_p33 = 'bx;

assign tmp_1_fu_602_p17 = 'bx;

assign tmp_2_fu_489_p4 = {{addr_fu_481_p3[10:7]}};

assign tmp_7_fu_1260_p3 = newexp_fu_1254_p2[32'd31];

assign tmp_s_fu_712_p33 = 'bx;

assign trunc_ln398_fu_504_p1 = addr_fu_481_p3[6:0];

assign trunc_ln491_fu_578_p1 = k_fu_572_p3[0:0];

assign trunc_ln505_fu_669_p1 = Mx_zeros_fu_661_p3[10:0];

assign x_1_fu_941_p3 = ((tmp_reg_1535[0:0] == 1'b1) ? lshr_ln506_fu_931_p2 : shl_ln506_fu_936_p2);

assign xor_ln242_fu_687_p2 = (tmp_1_reg_1511 ^ 1'd1);

assign xor_ln278_fu_864_p2 = (do_cos ^ 1'd1);

assign xor_ln282_fu_880_p2 = (icmp_ln282_fu_875_p2 ^ 1'd1);

assign zext_ln242_fu_1132_p1 = lshr_ln_reg_1732;

assign zext_ln25_1_fu_997_p1 = B_squared_reg_1614;

assign zext_ln25_fu_970_p1 = B_trunc_reg_1586;

assign zext_ln32_fu_981_p1 = A_fu_975_p3;

assign zext_ln37_1_fu_1124_p1 = tmp_6_reg_1737;

assign zext_ln397_fu_499_p1 = tmp_2_fu_489_p4;

assign zext_ln398_fu_508_p1 = trunc_ln398_reg_1458;

assign zext_ln504_fu_899_p1 = Mx_zeros_reg_1523;

assign zext_ln506_fu_927_p1 = select_ln506_fu_922_p3;

always @ (posedge ap_clk) begin
    zext_ln25_reg_1591[97:49] <= 49'b0000000000000000000000000000000000000000000000000;
    zext_ln32_reg_1597[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    out_bits_6_reg_1792[16:0] <= 17'b10000000000000000;
end

endmodule //dft_sin_or_cos_double_s
