#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("input_real_TDATA", 32, hls_in, 0, "axis", "in_data", 1),
	Port_Property("input_real_TVALID", 1, hls_in, 3, "axis", "in_vld", 1),
	Port_Property("input_real_TREADY", 1, hls_out, 3, "axis", "in_acc", 1),
	Port_Property("input_real_TKEEP", 4, hls_in, 1, "axis", "in_data", 1),
	Port_Property("input_real_TSTRB", 4, hls_in, 2, "axis", "in_data", 1),
	Port_Property("input_real_TLAST", 1, hls_in, 3, "axis", "in_data", 1),
	Port_Property("input_imag_TDATA", 32, hls_in, 4, "axis", "in_data", 1),
	Port_Property("input_imag_TVALID", 1, hls_in, 7, "axis", "in_vld", 1),
	Port_Property("input_imag_TREADY", 1, hls_out, 7, "axis", "in_acc", 1),
	Port_Property("input_imag_TKEEP", 4, hls_in, 5, "axis", "in_data", 1),
	Port_Property("input_imag_TSTRB", 4, hls_in, 6, "axis", "in_data", 1),
	Port_Property("input_imag_TLAST", 1, hls_in, 7, "axis", "in_data", 1),
	Port_Property("output_real_TDATA", 32, hls_out, 8, "axis", "out_data", 1),
	Port_Property("output_real_TVALID", 1, hls_out, 11, "axis", "out_vld", 1),
	Port_Property("output_real_TREADY", 1, hls_in, 11, "axis", "out_acc", 1),
	Port_Property("output_real_TKEEP", 4, hls_out, 9, "axis", "out_data", 1),
	Port_Property("output_real_TSTRB", 4, hls_out, 10, "axis", "out_data", 1),
	Port_Property("output_real_TLAST", 1, hls_out, 11, "axis", "out_data", 1),
	Port_Property("output_imag_TDATA", 32, hls_out, 12, "axis", "out_data", 1),
	Port_Property("output_imag_TVALID", 1, hls_out, 15, "axis", "out_vld", 1),
	Port_Property("output_imag_TREADY", 1, hls_in, 15, "axis", "out_acc", 1),
	Port_Property("output_imag_TKEEP", 4, hls_out, 13, "axis", "out_data", 1),
	Port_Property("output_imag_TSTRB", 4, hls_out, 14, "axis", "out_data", 1),
	Port_Property("output_imag_TLAST", 1, hls_out, 15, "axis", "out_data", 1),
};
const char* HLS_Design_Meta::dut_name = "dft";
