// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module dft_dft_Pipeline_VITIS_LOOP_20_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_ZL15cos_coeff_table_0_load,
        p_ZL15cos_coeff_table_4_load,
        p_ZL15cos_coeff_table_8_load,
        p_ZL15cos_coeff_table_12_load,
        p_ZL15cos_coeff_table_16_load,
        p_ZL15cos_coeff_table_20_load,
        p_ZL15cos_coeff_table_24_load,
        p_ZL15cos_coeff_table_28_load,
        p_ZL15sin_coeff_table_0_load,
        p_ZL15sin_coeff_table_4_load,
        p_ZL15sin_coeff_table_8_load,
        p_ZL15sin_coeff_table_12_load,
        p_ZL15sin_coeff_table_16_load,
        p_ZL15sin_coeff_table_20_load,
        p_ZL15sin_coeff_table_24_load,
        p_ZL15sin_coeff_table_28_load,
        empty_7,
        empty_8,
        empty_9,
        empty_10,
        empty_11,
        empty_12,
        empty_13,
        empty_14,
        empty_15,
        empty_16,
        empty_17,
        empty_18,
        empty_19,
        empty_20,
        empty_21,
        empty_22,
        p_ZL15cos_coeff_table_1_load,
        p_ZL15cos_coeff_table_5_load,
        p_ZL15cos_coeff_table_9_load,
        p_ZL15cos_coeff_table_13_load,
        p_ZL15cos_coeff_table_17_load,
        p_ZL15cos_coeff_table_21_load,
        p_ZL15cos_coeff_table_25_load,
        p_ZL15cos_coeff_table_29_load,
        p_ZL15sin_coeff_table_1_load,
        p_ZL15sin_coeff_table_5_load,
        p_ZL15sin_coeff_table_9_load,
        p_ZL15sin_coeff_table_13_load,
        p_ZL15sin_coeff_table_17_load,
        p_ZL15sin_coeff_table_21_load,
        p_ZL15sin_coeff_table_25_load,
        p_ZL15sin_coeff_table_29_load,
        empty_23,
        empty_24,
        empty_25,
        empty_26,
        empty_27,
        empty_28,
        empty_29,
        empty_30,
        empty_31,
        empty_32,
        empty_33,
        empty_34,
        empty_35,
        empty_36,
        empty_37,
        empty_38,
        p_ZL15cos_coeff_table_2_load,
        p_ZL15cos_coeff_table_6_load,
        p_ZL15cos_coeff_table_10_load,
        p_ZL15cos_coeff_table_14_load,
        p_ZL15cos_coeff_table_18_load,
        p_ZL15cos_coeff_table_22_load,
        p_ZL15cos_coeff_table_26_load,
        p_ZL15cos_coeff_table_30_load,
        p_ZL15sin_coeff_table_2_load,
        p_ZL15sin_coeff_table_6_load,
        p_ZL15sin_coeff_table_10_load,
        p_ZL15sin_coeff_table_14_load,
        p_ZL15sin_coeff_table_18_load,
        p_ZL15sin_coeff_table_22_load,
        p_ZL15sin_coeff_table_26_load,
        p_ZL15sin_coeff_table_30_load,
        empty_39,
        empty_40,
        empty_41,
        empty_42,
        empty_43,
        empty_44,
        empty_45,
        empty_46,
        empty_47,
        empty_48,
        empty_49,
        empty_50,
        empty_51,
        empty_52,
        empty_53,
        empty_54,
        p_ZL15cos_coeff_table_3_load,
        p_ZL15cos_coeff_table_7_load,
        p_ZL15cos_coeff_table_11_load,
        p_ZL15cos_coeff_table_15_load,
        p_ZL15cos_coeff_table_19_load,
        p_ZL15cos_coeff_table_23_load,
        p_ZL15cos_coeff_table_27_load,
        p_ZL15cos_coeff_table_31_load,
        p_ZL15sin_coeff_table_3_load,
        p_ZL15sin_coeff_table_7_load,
        p_ZL15sin_coeff_table_11_load,
        p_ZL15sin_coeff_table_15_load,
        p_ZL15sin_coeff_table_19_load,
        p_ZL15sin_coeff_table_23_load,
        p_ZL15sin_coeff_table_27_load,
        p_ZL15sin_coeff_table_31_load,
        empty_55,
        empty_56,
        empty_57,
        empty_58,
        empty_59,
        empty_60,
        empty_61,
        empty_62,
        empty_63,
        empty_64,
        empty_65,
        empty_66,
        empty_67,
        empty_68,
        empty_69,
        empty,
        add306_out,
        add306_out_ap_vld,
        add5_out,
        add5_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 21'd1;
parameter    ap_ST_fsm_pp0_stage1 = 21'd2;
parameter    ap_ST_fsm_pp0_stage2 = 21'd4;
parameter    ap_ST_fsm_pp0_stage3 = 21'd8;
parameter    ap_ST_fsm_pp0_stage4 = 21'd16;
parameter    ap_ST_fsm_pp0_stage5 = 21'd32;
parameter    ap_ST_fsm_pp0_stage6 = 21'd64;
parameter    ap_ST_fsm_pp0_stage7 = 21'd128;
parameter    ap_ST_fsm_pp0_stage8 = 21'd256;
parameter    ap_ST_fsm_pp0_stage9 = 21'd512;
parameter    ap_ST_fsm_pp0_stage10 = 21'd1024;
parameter    ap_ST_fsm_pp0_stage11 = 21'd2048;
parameter    ap_ST_fsm_pp0_stage12 = 21'd4096;
parameter    ap_ST_fsm_pp0_stage13 = 21'd8192;
parameter    ap_ST_fsm_pp0_stage14 = 21'd16384;
parameter    ap_ST_fsm_pp0_stage15 = 21'd32768;
parameter    ap_ST_fsm_pp0_stage16 = 21'd65536;
parameter    ap_ST_fsm_pp0_stage17 = 21'd131072;
parameter    ap_ST_fsm_pp0_stage18 = 21'd262144;
parameter    ap_ST_fsm_pp0_stage19 = 21'd524288;
parameter    ap_ST_fsm_pp0_stage20 = 21'd1048576;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] p_ZL15cos_coeff_table_0_load;
input  [31:0] p_ZL15cos_coeff_table_4_load;
input  [31:0] p_ZL15cos_coeff_table_8_load;
input  [31:0] p_ZL15cos_coeff_table_12_load;
input  [31:0] p_ZL15cos_coeff_table_16_load;
input  [31:0] p_ZL15cos_coeff_table_20_load;
input  [31:0] p_ZL15cos_coeff_table_24_load;
input  [31:0] p_ZL15cos_coeff_table_28_load;
input  [31:0] p_ZL15sin_coeff_table_0_load;
input  [31:0] p_ZL15sin_coeff_table_4_load;
input  [31:0] p_ZL15sin_coeff_table_8_load;
input  [31:0] p_ZL15sin_coeff_table_12_load;
input  [31:0] p_ZL15sin_coeff_table_16_load;
input  [31:0] p_ZL15sin_coeff_table_20_load;
input  [31:0] p_ZL15sin_coeff_table_24_load;
input  [31:0] p_ZL15sin_coeff_table_28_load;
input  [31:0] empty_7;
input  [31:0] empty_8;
input  [31:0] empty_9;
input  [31:0] empty_10;
input  [31:0] empty_11;
input  [31:0] empty_12;
input  [31:0] empty_13;
input  [31:0] empty_14;
input  [31:0] empty_15;
input  [31:0] empty_16;
input  [31:0] empty_17;
input  [31:0] empty_18;
input  [31:0] empty_19;
input  [31:0] empty_20;
input  [31:0] empty_21;
input  [31:0] empty_22;
input  [31:0] p_ZL15cos_coeff_table_1_load;
input  [31:0] p_ZL15cos_coeff_table_5_load;
input  [31:0] p_ZL15cos_coeff_table_9_load;
input  [31:0] p_ZL15cos_coeff_table_13_load;
input  [31:0] p_ZL15cos_coeff_table_17_load;
input  [31:0] p_ZL15cos_coeff_table_21_load;
input  [31:0] p_ZL15cos_coeff_table_25_load;
input  [31:0] p_ZL15cos_coeff_table_29_load;
input  [31:0] p_ZL15sin_coeff_table_1_load;
input  [31:0] p_ZL15sin_coeff_table_5_load;
input  [31:0] p_ZL15sin_coeff_table_9_load;
input  [31:0] p_ZL15sin_coeff_table_13_load;
input  [31:0] p_ZL15sin_coeff_table_17_load;
input  [31:0] p_ZL15sin_coeff_table_21_load;
input  [31:0] p_ZL15sin_coeff_table_25_load;
input  [31:0] p_ZL15sin_coeff_table_29_load;
input  [31:0] empty_23;
input  [31:0] empty_24;
input  [31:0] empty_25;
input  [31:0] empty_26;
input  [31:0] empty_27;
input  [31:0] empty_28;
input  [31:0] empty_29;
input  [31:0] empty_30;
input  [31:0] empty_31;
input  [31:0] empty_32;
input  [31:0] empty_33;
input  [31:0] empty_34;
input  [31:0] empty_35;
input  [31:0] empty_36;
input  [31:0] empty_37;
input  [31:0] empty_38;
input  [31:0] p_ZL15cos_coeff_table_2_load;
input  [31:0] p_ZL15cos_coeff_table_6_load;
input  [31:0] p_ZL15cos_coeff_table_10_load;
input  [31:0] p_ZL15cos_coeff_table_14_load;
input  [31:0] p_ZL15cos_coeff_table_18_load;
input  [31:0] p_ZL15cos_coeff_table_22_load;
input  [31:0] p_ZL15cos_coeff_table_26_load;
input  [31:0] p_ZL15cos_coeff_table_30_load;
input  [31:0] p_ZL15sin_coeff_table_2_load;
input  [31:0] p_ZL15sin_coeff_table_6_load;
input  [31:0] p_ZL15sin_coeff_table_10_load;
input  [31:0] p_ZL15sin_coeff_table_14_load;
input  [31:0] p_ZL15sin_coeff_table_18_load;
input  [31:0] p_ZL15sin_coeff_table_22_load;
input  [31:0] p_ZL15sin_coeff_table_26_load;
input  [31:0] p_ZL15sin_coeff_table_30_load;
input  [31:0] empty_39;
input  [31:0] empty_40;
input  [31:0] empty_41;
input  [31:0] empty_42;
input  [31:0] empty_43;
input  [31:0] empty_44;
input  [31:0] empty_45;
input  [31:0] empty_46;
input  [31:0] empty_47;
input  [31:0] empty_48;
input  [31:0] empty_49;
input  [31:0] empty_50;
input  [31:0] empty_51;
input  [31:0] empty_52;
input  [31:0] empty_53;
input  [31:0] empty_54;
input  [31:0] p_ZL15cos_coeff_table_3_load;
input  [31:0] p_ZL15cos_coeff_table_7_load;
input  [31:0] p_ZL15cos_coeff_table_11_load;
input  [31:0] p_ZL15cos_coeff_table_15_load;
input  [31:0] p_ZL15cos_coeff_table_19_load;
input  [31:0] p_ZL15cos_coeff_table_23_load;
input  [31:0] p_ZL15cos_coeff_table_27_load;
input  [31:0] p_ZL15cos_coeff_table_31_load;
input  [31:0] p_ZL15sin_coeff_table_3_load;
input  [31:0] p_ZL15sin_coeff_table_7_load;
input  [31:0] p_ZL15sin_coeff_table_11_load;
input  [31:0] p_ZL15sin_coeff_table_15_load;
input  [31:0] p_ZL15sin_coeff_table_19_load;
input  [31:0] p_ZL15sin_coeff_table_23_load;
input  [31:0] p_ZL15sin_coeff_table_27_load;
input  [31:0] p_ZL15sin_coeff_table_31_load;
input  [31:0] empty_55;
input  [31:0] empty_56;
input  [31:0] empty_57;
input  [31:0] empty_58;
input  [31:0] empty_59;
input  [31:0] empty_60;
input  [31:0] empty_61;
input  [31:0] empty_62;
input  [31:0] empty_63;
input  [31:0] empty_64;
input  [31:0] empty_65;
input  [31:0] empty_66;
input  [31:0] empty_67;
input  [31:0] empty_68;
input  [31:0] empty_69;
input  [31:0] empty;
output  [31:0] add306_out;
output   add306_out_ap_vld;
output  [31:0] add5_out;
output   add5_out_ap_vld;

reg ap_idle;
reg add306_out_ap_vld;
reg add5_out_ap_vld;

(* fsm_encoding = "none" *) reg   [20:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage12;
wire    ap_block_pp0_stage12_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] tmp_71_reg_1899;
reg    ap_condition_exit_pp0_iter0_stage12;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage20;
wire    ap_block_pp0_stage20_subdone;
wire   [31:0] grp_fu_1114_p2;
reg   [31:0] reg_1118;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_11001;
wire    ap_CS_fsm_pp0_stage10;
wire    ap_block_pp0_stage10_11001;
wire    ap_CS_fsm_pp0_stage16;
wire    ap_block_pp0_stage16_11001;
reg   [31:0] reg_1124;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5_11001;
wire    ap_CS_fsm_pp0_stage11;
wire    ap_block_pp0_stage11_11001;
wire    ap_CS_fsm_pp0_stage17;
wire    ap_block_pp0_stage17_11001;
reg   [31:0] reg_1130;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6_11001;
wire    ap_block_pp0_stage12_11001;
wire    ap_CS_fsm_pp0_stage18;
wire    ap_block_pp0_stage18_11001;
reg   [31:0] reg_1135;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_pp0_stage7_11001;
wire    ap_CS_fsm_pp0_stage13;
wire    ap_block_pp0_stage13_11001;
wire    ap_CS_fsm_pp0_stage19;
wire    ap_block_pp0_stage19_11001;
reg   [31:0] reg_1140;
wire    ap_CS_fsm_pp0_stage8;
wire    ap_block_pp0_stage8_11001;
wire    ap_CS_fsm_pp0_stage14;
wire    ap_block_pp0_stage14_11001;
reg   [31:0] reg_1146;
wire    ap_CS_fsm_pp0_stage9;
wire    ap_block_pp0_stage9_11001;
wire    ap_CS_fsm_pp0_stage15;
wire    ap_block_pp0_stage15_11001;
wire   [31:0] grp_fu_1106_p2;
reg   [31:0] reg_1152;
wire    ap_block_pp0_stage20_11001;
reg   [31:0] reg_1158;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
reg   [31:0] reg_1164;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_11001;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] tmp_71_fu_1187_p3;
wire   [31:0] c_fu_1199_p19;
reg   [31:0] c_reg_1903;
wire   [31:0] s_fu_1239_p19;
reg   [31:0] s_reg_1908;
wire   [31:0] tmp_fu_1279_p19;
reg   [31:0] tmp_reg_1913;
wire   [31:0] tmp_1_fu_1319_p19;
reg   [31:0] tmp_1_reg_1918;
wire   [31:0] c_1_fu_1359_p19;
reg   [31:0] c_1_reg_1923;
wire   [31:0] s_1_fu_1399_p19;
reg   [31:0] s_1_reg_1928;
wire   [31:0] tmp_4_fu_1439_p19;
reg   [31:0] tmp_4_reg_1933;
wire   [31:0] tmp_5_fu_1479_p19;
reg   [31:0] tmp_5_reg_1938;
wire   [31:0] c_2_fu_1519_p19;
reg   [31:0] c_2_reg_1943;
wire   [31:0] s_2_fu_1559_p19;
reg   [31:0] s_2_reg_1948;
wire   [31:0] tmp_8_fu_1599_p19;
reg   [31:0] tmp_8_reg_1953;
wire   [31:0] tmp_9_fu_1639_p19;
reg   [31:0] tmp_9_reg_1958;
wire   [31:0] c_3_fu_1679_p19;
reg   [31:0] c_3_reg_1963;
wire   [31:0] s_3_fu_1719_p19;
reg   [31:0] s_3_reg_1968;
wire   [31:0] tmp_s_fu_1759_p19;
reg   [31:0] tmp_s_reg_1973;
wire   [31:0] tmp_2_fu_1799_p19;
reg   [31:0] tmp_2_reg_1978;
reg   [31:0] add27_1_reg_1993;
reg   [31:0] sub_2_reg_1998;
wire   [31:0] grp_fu_1110_p2;
reg   [31:0] add27_2_reg_2003;
reg   [31:0] sub_3_reg_2008;
reg   [31:0] add5_fu_312;
wire    ap_loop_init;
wire    ap_block_pp0_stage11;
wire    ap_block_pp0_stage12;
reg   [31:0] add306_fu_316;
wire    ap_block_pp0_stage13;
reg   [5:0] j_fu_320;
wire   [5:0] add_ln20_fu_1839_p2;
reg   [5:0] ap_sig_allocacmp_j_1;
wire    ap_block_pp0_stage0;
wire    ap_block_pp0_stage12_01001;
reg   [31:0] grp_fu_1106_p0;
reg   [31:0] grp_fu_1106_p1;
wire    ap_block_pp0_stage6;
wire    ap_block_pp0_stage8;
wire    ap_block_pp0_stage10;
wire    ap_block_pp0_stage14;
wire    ap_block_pp0_stage16;
wire    ap_block_pp0_stage18;
wire    ap_block_pp0_stage20;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2;
wire    ap_block_pp0_stage5;
wire    ap_block_pp0_stage7;
reg   [31:0] grp_fu_1110_p0;
reg   [31:0] grp_fu_1110_p1;
reg   [31:0] grp_fu_1114_p0;
reg   [31:0] grp_fu_1114_p1;
wire    ap_block_pp0_stage1;
wire    ap_block_pp0_stage3;
wire    ap_block_pp0_stage4;
wire    ap_block_pp0_stage9;
wire    ap_block_pp0_stage15;
wire   [31:0] c_fu_1199_p17;
wire   [4:0] trunc_ln20_fu_1195_p1;
wire   [31:0] s_fu_1239_p17;
wire   [31:0] tmp_fu_1279_p17;
wire   [31:0] tmp_1_fu_1319_p17;
wire   [31:0] c_1_fu_1359_p17;
wire   [31:0] s_1_fu_1399_p17;
wire   [31:0] tmp_4_fu_1439_p17;
wire   [31:0] tmp_5_fu_1479_p17;
wire   [31:0] c_2_fu_1519_p17;
wire   [31:0] s_2_fu_1559_p17;
wire   [31:0] tmp_8_fu_1599_p17;
wire   [31:0] tmp_9_fu_1639_p17;
wire   [31:0] c_3_fu_1679_p17;
wire   [31:0] s_3_fu_1719_p17;
wire   [31:0] tmp_s_fu_1759_p17;
wire   [31:0] tmp_2_fu_1799_p17;
reg   [1:0] grp_fu_1106_opcode;
wire    ap_block_pp0_stage8_00001;
wire    ap_block_pp0_stage11_00001;
wire    ap_block_pp0_stage12_00001;
wire    ap_block_pp0_stage13_00001;
wire    ap_block_pp0_stage16_00001;
wire    ap_block_pp0_stage18_00001;
wire    ap_block_pp0_stage20_00001;
wire    ap_block_pp0_stage0_00001;
wire    ap_block_pp0_stage2_00001;
wire    ap_block_pp0_stage5_00001;
wire    ap_block_pp0_stage7_00001;
wire    ap_block_pp0_stage6_00001;
wire    ap_block_pp0_stage10_00001;
wire    ap_block_pp0_stage14_00001;
reg   [1:0] grp_fu_1110_opcode;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [20:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage6_subdone;
wire    ap_block_pp0_stage7_subdone;
wire    ap_block_pp0_stage8_subdone;
wire    ap_block_pp0_stage9_subdone;
wire    ap_block_pp0_stage10_subdone;
wire    ap_block_pp0_stage11_subdone;
wire    ap_block_pp0_stage13_subdone;
wire    ap_block_pp0_stage14_subdone;
wire    ap_block_pp0_stage15_subdone;
wire    ap_block_pp0_stage16_subdone;
wire    ap_block_pp0_stage17_subdone;
wire    ap_block_pp0_stage18_subdone;
wire    ap_block_pp0_stage19_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [4:0] c_fu_1199_p1;
wire   [4:0] c_fu_1199_p3;
wire   [4:0] c_fu_1199_p5;
wire   [4:0] c_fu_1199_p7;
wire  signed [4:0] c_fu_1199_p9;
wire  signed [4:0] c_fu_1199_p11;
wire  signed [4:0] c_fu_1199_p13;
wire  signed [4:0] c_fu_1199_p15;
wire   [4:0] s_fu_1239_p1;
wire   [4:0] s_fu_1239_p3;
wire   [4:0] s_fu_1239_p5;
wire   [4:0] s_fu_1239_p7;
wire  signed [4:0] s_fu_1239_p9;
wire  signed [4:0] s_fu_1239_p11;
wire  signed [4:0] s_fu_1239_p13;
wire  signed [4:0] s_fu_1239_p15;
wire   [4:0] tmp_fu_1279_p1;
wire   [4:0] tmp_fu_1279_p3;
wire   [4:0] tmp_fu_1279_p5;
wire   [4:0] tmp_fu_1279_p7;
wire  signed [4:0] tmp_fu_1279_p9;
wire  signed [4:0] tmp_fu_1279_p11;
wire  signed [4:0] tmp_fu_1279_p13;
wire  signed [4:0] tmp_fu_1279_p15;
wire   [4:0] tmp_1_fu_1319_p1;
wire   [4:0] tmp_1_fu_1319_p3;
wire   [4:0] tmp_1_fu_1319_p5;
wire   [4:0] tmp_1_fu_1319_p7;
wire  signed [4:0] tmp_1_fu_1319_p9;
wire  signed [4:0] tmp_1_fu_1319_p11;
wire  signed [4:0] tmp_1_fu_1319_p13;
wire  signed [4:0] tmp_1_fu_1319_p15;
wire   [4:0] c_1_fu_1359_p1;
wire   [4:0] c_1_fu_1359_p3;
wire   [4:0] c_1_fu_1359_p5;
wire   [4:0] c_1_fu_1359_p7;
wire  signed [4:0] c_1_fu_1359_p9;
wire  signed [4:0] c_1_fu_1359_p11;
wire  signed [4:0] c_1_fu_1359_p13;
wire  signed [4:0] c_1_fu_1359_p15;
wire   [4:0] s_1_fu_1399_p1;
wire   [4:0] s_1_fu_1399_p3;
wire   [4:0] s_1_fu_1399_p5;
wire   [4:0] s_1_fu_1399_p7;
wire  signed [4:0] s_1_fu_1399_p9;
wire  signed [4:0] s_1_fu_1399_p11;
wire  signed [4:0] s_1_fu_1399_p13;
wire  signed [4:0] s_1_fu_1399_p15;
wire   [4:0] tmp_4_fu_1439_p1;
wire   [4:0] tmp_4_fu_1439_p3;
wire   [4:0] tmp_4_fu_1439_p5;
wire   [4:0] tmp_4_fu_1439_p7;
wire  signed [4:0] tmp_4_fu_1439_p9;
wire  signed [4:0] tmp_4_fu_1439_p11;
wire  signed [4:0] tmp_4_fu_1439_p13;
wire  signed [4:0] tmp_4_fu_1439_p15;
wire   [4:0] tmp_5_fu_1479_p1;
wire   [4:0] tmp_5_fu_1479_p3;
wire   [4:0] tmp_5_fu_1479_p5;
wire   [4:0] tmp_5_fu_1479_p7;
wire  signed [4:0] tmp_5_fu_1479_p9;
wire  signed [4:0] tmp_5_fu_1479_p11;
wire  signed [4:0] tmp_5_fu_1479_p13;
wire  signed [4:0] tmp_5_fu_1479_p15;
wire   [4:0] c_2_fu_1519_p1;
wire   [4:0] c_2_fu_1519_p3;
wire   [4:0] c_2_fu_1519_p5;
wire   [4:0] c_2_fu_1519_p7;
wire  signed [4:0] c_2_fu_1519_p9;
wire  signed [4:0] c_2_fu_1519_p11;
wire  signed [4:0] c_2_fu_1519_p13;
wire  signed [4:0] c_2_fu_1519_p15;
wire   [4:0] s_2_fu_1559_p1;
wire   [4:0] s_2_fu_1559_p3;
wire   [4:0] s_2_fu_1559_p5;
wire   [4:0] s_2_fu_1559_p7;
wire  signed [4:0] s_2_fu_1559_p9;
wire  signed [4:0] s_2_fu_1559_p11;
wire  signed [4:0] s_2_fu_1559_p13;
wire  signed [4:0] s_2_fu_1559_p15;
wire   [4:0] tmp_8_fu_1599_p1;
wire   [4:0] tmp_8_fu_1599_p3;
wire   [4:0] tmp_8_fu_1599_p5;
wire   [4:0] tmp_8_fu_1599_p7;
wire  signed [4:0] tmp_8_fu_1599_p9;
wire  signed [4:0] tmp_8_fu_1599_p11;
wire  signed [4:0] tmp_8_fu_1599_p13;
wire  signed [4:0] tmp_8_fu_1599_p15;
wire   [4:0] tmp_9_fu_1639_p1;
wire   [4:0] tmp_9_fu_1639_p3;
wire   [4:0] tmp_9_fu_1639_p5;
wire   [4:0] tmp_9_fu_1639_p7;
wire  signed [4:0] tmp_9_fu_1639_p9;
wire  signed [4:0] tmp_9_fu_1639_p11;
wire  signed [4:0] tmp_9_fu_1639_p13;
wire  signed [4:0] tmp_9_fu_1639_p15;
wire   [4:0] c_3_fu_1679_p1;
wire   [4:0] c_3_fu_1679_p3;
wire   [4:0] c_3_fu_1679_p5;
wire   [4:0] c_3_fu_1679_p7;
wire  signed [4:0] c_3_fu_1679_p9;
wire  signed [4:0] c_3_fu_1679_p11;
wire  signed [4:0] c_3_fu_1679_p13;
wire  signed [4:0] c_3_fu_1679_p15;
wire   [4:0] s_3_fu_1719_p1;
wire   [4:0] s_3_fu_1719_p3;
wire   [4:0] s_3_fu_1719_p5;
wire   [4:0] s_3_fu_1719_p7;
wire  signed [4:0] s_3_fu_1719_p9;
wire  signed [4:0] s_3_fu_1719_p11;
wire  signed [4:0] s_3_fu_1719_p13;
wire  signed [4:0] s_3_fu_1719_p15;
wire   [4:0] tmp_s_fu_1759_p1;
wire   [4:0] tmp_s_fu_1759_p3;
wire   [4:0] tmp_s_fu_1759_p5;
wire   [4:0] tmp_s_fu_1759_p7;
wire  signed [4:0] tmp_s_fu_1759_p9;
wire  signed [4:0] tmp_s_fu_1759_p11;
wire  signed [4:0] tmp_s_fu_1759_p13;
wire  signed [4:0] tmp_s_fu_1759_p15;
wire   [4:0] tmp_2_fu_1799_p1;
wire   [4:0] tmp_2_fu_1799_p3;
wire   [4:0] tmp_2_fu_1799_p5;
wire   [4:0] tmp_2_fu_1799_p7;
wire  signed [4:0] tmp_2_fu_1799_p9;
wire  signed [4:0] tmp_2_fu_1799_p11;
wire  signed [4:0] tmp_2_fu_1799_p13;
wire  signed [4:0] tmp_2_fu_1799_p15;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 21'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 add5_fu_312 = 32'd0;
#0 add306_fu_316 = 32'd0;
#0 j_fu_320 = 6'd0;
#0 ap_done_reg = 1'b0;
end

dft_faddfsub_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
faddfsub_32ns_32ns_32_5_full_dsp_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1106_p0),
    .din1(grp_fu_1106_p1),
    .opcode(grp_fu_1106_opcode),
    .ce(1'b1),
    .dout(grp_fu_1106_p2)
);

dft_faddfsub_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
faddfsub_32ns_32ns_32_5_full_dsp_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1110_p0),
    .din1(grp_fu_1110_p1),
    .opcode(grp_fu_1110_opcode),
    .ce(1'b1),
    .dout(grp_fu_1110_p2)
);

dft_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1114_p0),
    .din1(grp_fu_1114_p1),
    .ce(1'b1),
    .dout(grp_fu_1114_p2)
);

(* dissolve_hierarchy = "yes" *) dft_sparsemux_17_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h4 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h8 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'hC ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h10 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h14 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h18 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h1C ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_17_5_32_1_1_U4(
    .din0(p_ZL15cos_coeff_table_0_load),
    .din1(p_ZL15cos_coeff_table_4_load),
    .din2(p_ZL15cos_coeff_table_8_load),
    .din3(p_ZL15cos_coeff_table_12_load),
    .din4(p_ZL15cos_coeff_table_16_load),
    .din5(p_ZL15cos_coeff_table_20_load),
    .din6(p_ZL15cos_coeff_table_24_load),
    .din7(p_ZL15cos_coeff_table_28_load),
    .def(c_fu_1199_p17),
    .sel(trunc_ln20_fu_1195_p1),
    .dout(c_fu_1199_p19)
);

(* dissolve_hierarchy = "yes" *) dft_sparsemux_17_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h4 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h8 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'hC ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h10 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h14 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h18 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h1C ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_17_5_32_1_1_U5(
    .din0(p_ZL15sin_coeff_table_0_load),
    .din1(p_ZL15sin_coeff_table_4_load),
    .din2(p_ZL15sin_coeff_table_8_load),
    .din3(p_ZL15sin_coeff_table_12_load),
    .din4(p_ZL15sin_coeff_table_16_load),
    .din5(p_ZL15sin_coeff_table_20_load),
    .din6(p_ZL15sin_coeff_table_24_load),
    .din7(p_ZL15sin_coeff_table_28_load),
    .def(s_fu_1239_p17),
    .sel(trunc_ln20_fu_1195_p1),
    .dout(s_fu_1239_p19)
);

(* dissolve_hierarchy = "yes" *) dft_sparsemux_17_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h4 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h8 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'hC ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h10 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h14 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h18 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h1C ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_17_5_32_1_1_U6(
    .din0(empty_7),
    .din1(empty_8),
    .din2(empty_9),
    .din3(empty_10),
    .din4(empty_11),
    .din5(empty_12),
    .din6(empty_13),
    .din7(empty_14),
    .def(tmp_fu_1279_p17),
    .sel(trunc_ln20_fu_1195_p1),
    .dout(tmp_fu_1279_p19)
);

(* dissolve_hierarchy = "yes" *) dft_sparsemux_17_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h4 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h8 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'hC ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h10 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h14 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h18 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h1C ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_17_5_32_1_1_U7(
    .din0(empty_15),
    .din1(empty_16),
    .din2(empty_17),
    .din3(empty_18),
    .din4(empty_19),
    .din5(empty_20),
    .din6(empty_21),
    .din7(empty_22),
    .def(tmp_1_fu_1319_p17),
    .sel(trunc_ln20_fu_1195_p1),
    .dout(tmp_1_fu_1319_p19)
);

(* dissolve_hierarchy = "yes" *) dft_sparsemux_17_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h4 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h8 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'hC ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h10 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h14 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h18 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h1C ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_17_5_32_1_1_U8(
    .din0(p_ZL15cos_coeff_table_1_load),
    .din1(p_ZL15cos_coeff_table_5_load),
    .din2(p_ZL15cos_coeff_table_9_load),
    .din3(p_ZL15cos_coeff_table_13_load),
    .din4(p_ZL15cos_coeff_table_17_load),
    .din5(p_ZL15cos_coeff_table_21_load),
    .din6(p_ZL15cos_coeff_table_25_load),
    .din7(p_ZL15cos_coeff_table_29_load),
    .def(c_1_fu_1359_p17),
    .sel(trunc_ln20_fu_1195_p1),
    .dout(c_1_fu_1359_p19)
);

(* dissolve_hierarchy = "yes" *) dft_sparsemux_17_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h4 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h8 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'hC ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h10 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h14 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h18 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h1C ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_17_5_32_1_1_U9(
    .din0(p_ZL15sin_coeff_table_1_load),
    .din1(p_ZL15sin_coeff_table_5_load),
    .din2(p_ZL15sin_coeff_table_9_load),
    .din3(p_ZL15sin_coeff_table_13_load),
    .din4(p_ZL15sin_coeff_table_17_load),
    .din5(p_ZL15sin_coeff_table_21_load),
    .din6(p_ZL15sin_coeff_table_25_load),
    .din7(p_ZL15sin_coeff_table_29_load),
    .def(s_1_fu_1399_p17),
    .sel(trunc_ln20_fu_1195_p1),
    .dout(s_1_fu_1399_p19)
);

(* dissolve_hierarchy = "yes" *) dft_sparsemux_17_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h4 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h8 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'hC ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h10 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h14 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h18 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h1C ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_17_5_32_1_1_U10(
    .din0(empty_23),
    .din1(empty_24),
    .din2(empty_25),
    .din3(empty_26),
    .din4(empty_27),
    .din5(empty_28),
    .din6(empty_29),
    .din7(empty_30),
    .def(tmp_4_fu_1439_p17),
    .sel(trunc_ln20_fu_1195_p1),
    .dout(tmp_4_fu_1439_p19)
);

(* dissolve_hierarchy = "yes" *) dft_sparsemux_17_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h4 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h8 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'hC ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h10 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h14 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h18 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h1C ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_17_5_32_1_1_U11(
    .din0(empty_31),
    .din1(empty_32),
    .din2(empty_33),
    .din3(empty_34),
    .din4(empty_35),
    .din5(empty_36),
    .din6(empty_37),
    .din7(empty_38),
    .def(tmp_5_fu_1479_p17),
    .sel(trunc_ln20_fu_1195_p1),
    .dout(tmp_5_fu_1479_p19)
);

(* dissolve_hierarchy = "yes" *) dft_sparsemux_17_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h4 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h8 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'hC ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h10 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h14 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h18 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h1C ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_17_5_32_1_1_U12(
    .din0(p_ZL15cos_coeff_table_2_load),
    .din1(p_ZL15cos_coeff_table_6_load),
    .din2(p_ZL15cos_coeff_table_10_load),
    .din3(p_ZL15cos_coeff_table_14_load),
    .din4(p_ZL15cos_coeff_table_18_load),
    .din5(p_ZL15cos_coeff_table_22_load),
    .din6(p_ZL15cos_coeff_table_26_load),
    .din7(p_ZL15cos_coeff_table_30_load),
    .def(c_2_fu_1519_p17),
    .sel(trunc_ln20_fu_1195_p1),
    .dout(c_2_fu_1519_p19)
);

(* dissolve_hierarchy = "yes" *) dft_sparsemux_17_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h4 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h8 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'hC ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h10 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h14 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h18 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h1C ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_17_5_32_1_1_U13(
    .din0(p_ZL15sin_coeff_table_2_load),
    .din1(p_ZL15sin_coeff_table_6_load),
    .din2(p_ZL15sin_coeff_table_10_load),
    .din3(p_ZL15sin_coeff_table_14_load),
    .din4(p_ZL15sin_coeff_table_18_load),
    .din5(p_ZL15sin_coeff_table_22_load),
    .din6(p_ZL15sin_coeff_table_26_load),
    .din7(p_ZL15sin_coeff_table_30_load),
    .def(s_2_fu_1559_p17),
    .sel(trunc_ln20_fu_1195_p1),
    .dout(s_2_fu_1559_p19)
);

(* dissolve_hierarchy = "yes" *) dft_sparsemux_17_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h4 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h8 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'hC ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h10 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h14 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h18 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h1C ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_17_5_32_1_1_U14(
    .din0(empty_39),
    .din1(empty_40),
    .din2(empty_41),
    .din3(empty_42),
    .din4(empty_43),
    .din5(empty_44),
    .din6(empty_45),
    .din7(empty_46),
    .def(tmp_8_fu_1599_p17),
    .sel(trunc_ln20_fu_1195_p1),
    .dout(tmp_8_fu_1599_p19)
);

(* dissolve_hierarchy = "yes" *) dft_sparsemux_17_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h4 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h8 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'hC ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h10 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h14 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h18 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h1C ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_17_5_32_1_1_U15(
    .din0(empty_47),
    .din1(empty_48),
    .din2(empty_49),
    .din3(empty_50),
    .din4(empty_51),
    .din5(empty_52),
    .din6(empty_53),
    .din7(empty_54),
    .def(tmp_9_fu_1639_p17),
    .sel(trunc_ln20_fu_1195_p1),
    .dout(tmp_9_fu_1639_p19)
);

(* dissolve_hierarchy = "yes" *) dft_sparsemux_17_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h4 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h8 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'hC ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h10 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h14 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h18 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h1C ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_17_5_32_1_1_U16(
    .din0(p_ZL15cos_coeff_table_3_load),
    .din1(p_ZL15cos_coeff_table_7_load),
    .din2(p_ZL15cos_coeff_table_11_load),
    .din3(p_ZL15cos_coeff_table_15_load),
    .din4(p_ZL15cos_coeff_table_19_load),
    .din5(p_ZL15cos_coeff_table_23_load),
    .din6(p_ZL15cos_coeff_table_27_load),
    .din7(p_ZL15cos_coeff_table_31_load),
    .def(c_3_fu_1679_p17),
    .sel(trunc_ln20_fu_1195_p1),
    .dout(c_3_fu_1679_p19)
);

(* dissolve_hierarchy = "yes" *) dft_sparsemux_17_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h4 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h8 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'hC ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h10 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h14 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h18 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h1C ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_17_5_32_1_1_U17(
    .din0(p_ZL15sin_coeff_table_3_load),
    .din1(p_ZL15sin_coeff_table_7_load),
    .din2(p_ZL15sin_coeff_table_11_load),
    .din3(p_ZL15sin_coeff_table_15_load),
    .din4(p_ZL15sin_coeff_table_19_load),
    .din5(p_ZL15sin_coeff_table_23_load),
    .din6(p_ZL15sin_coeff_table_27_load),
    .din7(p_ZL15sin_coeff_table_31_load),
    .def(s_3_fu_1719_p17),
    .sel(trunc_ln20_fu_1195_p1),
    .dout(s_3_fu_1719_p19)
);

(* dissolve_hierarchy = "yes" *) dft_sparsemux_17_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h4 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h8 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'hC ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h10 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h14 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h18 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h1C ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_17_5_32_1_1_U18(
    .din0(empty_55),
    .din1(empty_56),
    .din2(empty_57),
    .din3(empty_58),
    .din4(empty_59),
    .din5(empty_60),
    .din6(empty_61),
    .din7(empty_62),
    .def(tmp_s_fu_1759_p17),
    .sel(trunc_ln20_fu_1195_p1),
    .dout(tmp_s_fu_1759_p19)
);

(* dissolve_hierarchy = "yes" *) dft_sparsemux_17_5_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 5'h4 ),
    .din1_WIDTH( 32 ),
    .CASE2( 5'h8 ),
    .din2_WIDTH( 32 ),
    .CASE3( 5'hC ),
    .din3_WIDTH( 32 ),
    .CASE4( 5'h10 ),
    .din4_WIDTH( 32 ),
    .CASE5( 5'h14 ),
    .din5_WIDTH( 32 ),
    .CASE6( 5'h18 ),
    .din6_WIDTH( 32 ),
    .CASE7( 5'h1C ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
sparsemux_17_5_32_1_1_U19(
    .din0(empty_63),
    .din1(empty_64),
    .din2(empty_65),
    .din3(empty_66),
    .din4(empty_67),
    .din5(empty_68),
    .din6(empty_69),
    .din7(empty),
    .def(tmp_2_fu_1799_p17),
    .sel(trunc_ln20_fu_1195_p1),
    .dout(tmp_2_fu_1799_p19)
);

dft_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage12),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage12_subdone) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage12)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage12_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage20_subdone) & (1'b1 == ap_CS_fsm_pp0_stage20))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add306_fu_316 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        add306_fu_316 <= reg_1158;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add5_fu_312 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        add5_fu_312 <= reg_1152;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((tmp_71_fu_1187_p3 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_320 <= add_ln20_fu_1839_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_320 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage16_11001) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
        add27_1_reg_1993 <= grp_fu_1106_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage20_11001) & (1'b1 == ap_CS_fsm_pp0_stage20))) begin
        add27_2_reg_2003 <= grp_fu_1110_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        c_1_reg_1923 <= c_1_fu_1359_p19;
        c_2_reg_1943 <= c_2_fu_1519_p19;
        c_3_reg_1963 <= c_3_fu_1679_p19;
        c_reg_1903 <= c_fu_1199_p19;
        s_1_reg_1928 <= s_1_fu_1399_p19;
        s_2_reg_1948 <= s_2_fu_1559_p19;
        s_3_reg_1968 <= s_3_fu_1719_p19;
        s_reg_1908 <= s_fu_1239_p19;
        tmp_1_reg_1918 <= tmp_1_fu_1319_p19;
        tmp_2_reg_1978 <= tmp_2_fu_1799_p19;
        tmp_4_reg_1933 <= tmp_4_fu_1439_p19;
        tmp_5_reg_1938 <= tmp_5_fu_1479_p19;
        tmp_71_reg_1899 <= ap_sig_allocacmp_j_1[32'd5];
        tmp_8_reg_1953 <= tmp_8_fu_1599_p19;
        tmp_9_reg_1958 <= tmp_9_fu_1639_p19;
        tmp_reg_1913 <= tmp_fu_1279_p19;
        tmp_s_reg_1973 <= tmp_s_fu_1759_p19;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage16_11001) & (1'b1 == ap_CS_fsm_pp0_stage16)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage10_11001) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)))) begin
        reg_1118 <= grp_fu_1114_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage17_11001) & (1'b1 == ap_CS_fsm_pp0_stage17)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage11_11001) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        reg_1124 <= grp_fu_1114_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage18_11001) & (1'b1 == ap_CS_fsm_pp0_stage18)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage12_11001) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6)))) begin
        reg_1130 <= grp_fu_1114_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage19_11001) & (1'b1 == ap_CS_fsm_pp0_stage19)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage13_11001) & (1'b1 == ap_CS_fsm_pp0_stage13)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7)))) begin
        reg_1135 <= grp_fu_1114_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage14_11001) & (1'b1 == ap_CS_fsm_pp0_stage14)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8)))) begin
        reg_1140 <= grp_fu_1114_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage15_11001) & (1'b1 == ap_CS_fsm_pp0_stage15)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9)))) begin
        reg_1146 <= grp_fu_1114_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage20_11001) & (1'b1 == ap_CS_fsm_pp0_stage20)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage15_11001) & (1'b1 == ap_CS_fsm_pp0_stage15)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage10_11001) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)))) begin
        reg_1152 <= grp_fu_1106_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage12_11001) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage17_11001) & (1'b1 == ap_CS_fsm_pp0_stage17)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage11_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11)))) begin
        reg_1158 <= grp_fu_1106_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage14_11001) & (1'b1 == ap_CS_fsm_pp0_stage14)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        reg_1164 <= grp_fu_1106_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage18_11001) & (1'b1 == ap_CS_fsm_pp0_stage18))) begin
        sub_2_reg_1998 <= grp_fu_1106_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        sub_3_reg_2008 <= grp_fu_1110_p2;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (tmp_71_reg_1899 == 1'd1) & (1'b0 == ap_block_pp0_stage12_11001) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        add306_out_ap_vld = 1'b1;
    end else begin
        add306_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (tmp_71_reg_1899 == 1'd1) & (1'b0 == ap_block_pp0_stage12_11001) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        add5_out_ap_vld = 1'b1;
    end else begin
        add5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_71_reg_1899 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage12_subdone) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        ap_condition_exit_pp0_iter0_stage12 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage12 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage12_subdone) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage20_subdone) & (1'b1 == ap_CS_fsm_pp0_stage20))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_1 = 6'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_320;
    end
end

always @ (*) begin
    if ((((tmp_71_reg_1899 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage14_00001) & (1'b1 == ap_CS_fsm_pp0_stage14)) | ((tmp_71_reg_1899 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage10_00001) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((tmp_71_reg_1899 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_00001) & (1'b1 == ap_CS_fsm_pp0_stage6)))) begin
        grp_fu_1106_opcode = 2'd1;
    end else if ((((tmp_71_reg_1899 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage20_00001) & (1'b1 == ap_CS_fsm_pp0_stage20)) | ((tmp_71_reg_1899 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage18_00001) & (1'b1 == ap_CS_fsm_pp0_stage18)) | ((tmp_71_reg_1899 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage16_00001) & (1'b1 == ap_CS_fsm_pp0_stage16)) | ((tmp_71_reg_1899 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage13_00001) & (1'b1 == ap_CS_fsm_pp0_stage13)) | ((tmp_71_reg_1899 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage12_00001) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((tmp_71_reg_1899 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage11_00001) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((tmp_71_reg_1899 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage8_00001) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage7_00001) 
    & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage5_00001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage2_00001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_00001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_1106_opcode = 2'd0;
    end else begin
        grp_fu_1106_opcode = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage18) & (1'b1 == ap_CS_fsm_pp0_stage18)))) begin
        grp_fu_1106_p0 = reg_1158;
    end else if ((((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage16) & (1'b1 == ap_CS_fsm_pp0_stage16)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_1106_p0 = reg_1152;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage13) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
        grp_fu_1106_p0 = add306_fu_316;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage11) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        grp_fu_1106_p0 = add5_fu_312;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage10) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        grp_fu_1106_p0 = reg_1140;
    end else if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage20) & (1'b1 == ap_CS_fsm_pp0_stage20)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage14) & (1'b1 == ap_CS_fsm_pp0_stage14)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage8) & (1'b1 == ap_CS_fsm_pp0_stage8)))) begin
        grp_fu_1106_p0 = reg_1130;
    end else if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage12) & (1'b1 == ap_CS_fsm_pp0_stage12)))) begin
        grp_fu_1106_p0 = reg_1118;
    end else begin
        grp_fu_1106_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_1106_p1 = sub_3_reg_2008;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_1106_p1 = add27_2_reg_2003;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1106_p1 = sub_2_reg_1998;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage18) & (1'b1 == ap_CS_fsm_pp0_stage18))) begin
        grp_fu_1106_p1 = add27_1_reg_1993;
    end else if ((((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage16) & (1'b1 == ap_CS_fsm_pp0_stage16)))) begin
        grp_fu_1106_p1 = reg_1164;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage13) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
        grp_fu_1106_p1 = reg_1158;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage11) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        grp_fu_1106_p1 = reg_1152;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage10) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        grp_fu_1106_p1 = reg_1146;
    end else if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage20) & (1'b1 == ap_CS_fsm_pp0_stage20)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage14) & (1'b1 == ap_CS_fsm_pp0_stage14)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage8) & (1'b1 == ap_CS_fsm_pp0_stage8)))) begin
        grp_fu_1106_p1 = reg_1135;
    end else if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage12) & (1'b1 == ap_CS_fsm_pp0_stage12)))) begin
        grp_fu_1106_p1 = reg_1124;
    end else begin
        grp_fu_1106_p1 = 'bx;
    end
end

always @ (*) begin
    if (((tmp_71_reg_1899 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        if (((1'b0 == ap_block_pp0_stage18_00001) & (1'b1 == ap_CS_fsm_pp0_stage18))) begin
            grp_fu_1110_opcode = 2'd1;
        end else if (((1'b0 == ap_block_pp0_stage16_00001) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
            grp_fu_1110_opcode = 2'd0;
        end else begin
            grp_fu_1110_opcode = 'bx;
        end
    end else begin
        grp_fu_1110_opcode = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0_reg == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage18) & (1'b1 == ap_CS_fsm_pp0_stage18))) begin
            grp_fu_1110_p0 = reg_1118;
        end else if (((1'b0 == ap_block_pp0_stage16) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
            grp_fu_1110_p0 = reg_1140;
        end else begin
            grp_fu_1110_p0 = 'bx;
        end
    end else begin
        grp_fu_1110_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0_reg == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage18) & (1'b1 == ap_CS_fsm_pp0_stage18))) begin
            grp_fu_1110_p1 = reg_1124;
        end else if (((1'b0 == ap_block_pp0_stage16) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
            grp_fu_1110_p1 = reg_1146;
        end else begin
            grp_fu_1110_p1 = 'bx;
        end
    end else begin
        grp_fu_1110_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage16) & (1'b1 == ap_CS_fsm_pp0_stage16)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage14) & (1'b1 == ap_CS_fsm_pp0_stage14)))) begin
        grp_fu_1114_p0 = tmp_2_reg_1978;
    end else if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage15) & (1'b1 == ap_CS_fsm_pp0_stage15)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage13) & (1'b1 == ap_CS_fsm_pp0_stage13)))) begin
        grp_fu_1114_p0 = tmp_s_reg_1973;
    end else if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage10) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage12) & (1'b1 == ap_CS_fsm_pp0_stage12)))) begin
        grp_fu_1114_p0 = tmp_9_reg_1958;
    end else if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage9) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage11) & (1'b1 == ap_CS_fsm_pp0_stage11)))) begin
        grp_fu_1114_p0 = tmp_8_reg_1953;
    end else if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage8) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6)))) begin
        grp_fu_1114_p0 = tmp_5_reg_1938;
    end else if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        grp_fu_1114_p0 = tmp_4_reg_1933;
    end else if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        grp_fu_1114_p0 = tmp_1_reg_1918;
    end else if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_1114_p0 = tmp_reg_1913;
    end else begin
        grp_fu_1114_p0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage15) & (1'b1 == ap_CS_fsm_pp0_stage15)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage14) & (1'b1 == ap_CS_fsm_pp0_stage14)))) begin
        grp_fu_1114_p1 = s_3_reg_1968;
    end else if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage16) & (1'b1 == ap_CS_fsm_pp0_stage16)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage13) & (1'b1 == ap_CS_fsm_pp0_stage13)))) begin
        grp_fu_1114_p1 = c_3_reg_1963;
    end else if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage10) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage11) & (1'b1 == ap_CS_fsm_pp0_stage11)))) begin
        grp_fu_1114_p1 = s_2_reg_1948;
    end else if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage9) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage12) & (1'b1 == ap_CS_fsm_pp0_stage12)))) begin
        grp_fu_1114_p1 = c_2_reg_1943;
    end else if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6)))) begin
        grp_fu_1114_p1 = s_1_reg_1928;
    end else if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage8) & (1'b1 == ap_CS_fsm_pp0_stage8)))) begin
        grp_fu_1114_p1 = c_1_reg_1923;
    end else if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        grp_fu_1114_p1 = s_reg_1908;
    end else if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_1114_p1 = c_reg_1903;
    end else begin
        grp_fu_1114_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_pp0_stage8 : begin
            if ((1'b0 == ap_block_pp0_stage8_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end
        end
        ap_ST_fsm_pp0_stage9 : begin
            if ((1'b0 == ap_block_pp0_stage9_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end
        end
        ap_ST_fsm_pp0_stage10 : begin
            if ((1'b0 == ap_block_pp0_stage10_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end
        end
        ap_ST_fsm_pp0_stage11 : begin
            if ((1'b0 == ap_block_pp0_stage11_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end
        end
        ap_ST_fsm_pp0_stage12 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage12)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage12_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end
        end
        ap_ST_fsm_pp0_stage13 : begin
            if ((1'b0 == ap_block_pp0_stage13_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage13;
            end
        end
        ap_ST_fsm_pp0_stage14 : begin
            if ((1'b0 == ap_block_pp0_stage14_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage14;
            end
        end
        ap_ST_fsm_pp0_stage15 : begin
            if ((1'b0 == ap_block_pp0_stage15_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage15;
            end
        end
        ap_ST_fsm_pp0_stage16 : begin
            if ((1'b0 == ap_block_pp0_stage16_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage16;
            end
        end
        ap_ST_fsm_pp0_stage17 : begin
            if ((1'b0 == ap_block_pp0_stage17_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage17;
            end
        end
        ap_ST_fsm_pp0_stage18 : begin
            if ((1'b0 == ap_block_pp0_stage18_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage18;
            end
        end
        ap_ST_fsm_pp0_stage19 : begin
            if ((1'b0 == ap_block_pp0_stage19_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage19;
            end
        end
        ap_ST_fsm_pp0_stage20 : begin
            if ((1'b0 == ap_block_pp0_stage20_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage20;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add306_out = add306_fu_316;

assign add5_out = add5_fu_312;

assign add_ln20_fu_1839_p2 = (ap_sig_allocacmp_j_1 + 6'd4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage10 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_pp0_stage11 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_pp0_stage12 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_pp0_stage13 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_pp0_stage14 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_pp0_stage15 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_pp0_stage16 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_pp0_stage17 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_pp0_stage18 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_pp0_stage19 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage20 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp0_stage8 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp0_stage9 = ap_CS_fsm[32'd9];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage13 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage13_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage13_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage13_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage14 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage14_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage14_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage14_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage15 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage15_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage15_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage16 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage16_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage16_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage16_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage17_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage17_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage18 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage18_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage18_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage18_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage19_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage19_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage20 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage20_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage20_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage20_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage12;

assign ap_ready = ap_ready_sig;

assign c_1_fu_1359_p17 = 'bx;

assign c_2_fu_1519_p17 = 'bx;

assign c_3_fu_1679_p17 = 'bx;

assign c_fu_1199_p17 = 'bx;

assign s_1_fu_1399_p17 = 'bx;

assign s_2_fu_1559_p17 = 'bx;

assign s_3_fu_1719_p17 = 'bx;

assign s_fu_1239_p17 = 'bx;

assign tmp_1_fu_1319_p17 = 'bx;

assign tmp_2_fu_1799_p17 = 'bx;

assign tmp_4_fu_1439_p17 = 'bx;

assign tmp_5_fu_1479_p17 = 'bx;

assign tmp_71_fu_1187_p3 = ap_sig_allocacmp_j_1[32'd5];

assign tmp_8_fu_1599_p17 = 'bx;

assign tmp_9_fu_1639_p17 = 'bx;

assign tmp_fu_1279_p17 = 'bx;

assign tmp_s_fu_1759_p17 = 'bx;

assign trunc_ln20_fu_1195_p1 = ap_sig_allocacmp_j_1[4:0];

endmodule //dft_dft_Pipeline_VITIS_LOOP_20_2
