-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bnn_bnn_Pipeline_pack_loop1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    l2_bits_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_16_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_32_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_48_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_1_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_17_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_33_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_49_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_2_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_18_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_34_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_50_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_3_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_19_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_35_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_51_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_4_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_20_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_36_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_52_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_5_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_21_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_37_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_53_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_6_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_22_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_38_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_54_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_7_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_23_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_39_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_55_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_8_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_24_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_40_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_56_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_9_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_25_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_41_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_57_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_10_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_26_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_42_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_58_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_11_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_27_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_43_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_59_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_12_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_28_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_44_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_60_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_13_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_29_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_45_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_61_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_14_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_30_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_46_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_62_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_15_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_31_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_47_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_63_reload : IN STD_LOGIC_VECTOR (0 downto 0);
    p_0_0271_3110_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_0_0271_3110_out_ap_vld : OUT STD_LOGIC;
    p_0_0271_2108_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_0_0271_2108_out_ap_vld : OUT STD_LOGIC;
    p_0_0271_1106_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_0_0271_1106_out_ap_vld : OUT STD_LOGIC;
    p_0_0271104_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_0_0271104_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of bnn_bnn_Pipeline_pack_loop1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln26_fu_616_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal w_fu_176 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal add_ln26_fu_622_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_w_1 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_0_0271104_fu_180 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal word_2_fu_1016_p17 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln26_fu_628_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_0_0271_1106_fu_184 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_0_0271_2108_fu_188 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_0_0271_3110_fu_192 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal word_fu_632_p9 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_656_p9 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_680_p9 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_704_p9 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_728_p9 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_752_p9 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_776_p9 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_800_p9 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_824_p9 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_848_p9 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_872_p9 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_fu_896_p9 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_fu_920_p9 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_944_p9 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_fu_968_p9 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_fu_992_p9 : STD_LOGIC_VECTOR (0 downto 0);
    signal word_fu_632_p11 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_656_p11 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_680_p11 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_704_p11 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_728_p11 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_752_p11 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_776_p11 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_800_p11 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_824_p11 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_848_p11 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_872_p11 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_fu_896_p11 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_fu_920_p11 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_944_p11 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_fu_968_p11 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_fu_992_p11 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal word_fu_632_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal word_fu_632_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal word_fu_632_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal word_fu_632_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_656_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_656_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_656_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_656_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_680_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_680_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_680_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_680_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_704_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_704_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_704_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_704_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_728_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_728_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_728_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_728_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_4_fu_752_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_4_fu_752_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_4_fu_752_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_4_fu_752_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_5_fu_776_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_5_fu_776_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_5_fu_776_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_5_fu_776_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_6_fu_800_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_6_fu_800_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_6_fu_800_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_6_fu_800_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_7_fu_824_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_7_fu_824_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_7_fu_824_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_7_fu_824_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_8_fu_848_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_8_fu_848_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_8_fu_848_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_8_fu_848_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_9_fu_872_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_9_fu_872_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_9_fu_872_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_9_fu_872_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_10_fu_896_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_10_fu_896_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_10_fu_896_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_10_fu_896_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_11_fu_920_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_11_fu_920_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_11_fu_920_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_11_fu_920_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_12_fu_944_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_12_fu_944_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_12_fu_944_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_12_fu_944_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_13_fu_968_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_13_fu_968_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_13_fu_968_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_13_fu_968_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_14_fu_992_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_14_fu_992_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_14_fu_992_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_14_fu_992_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component bnn_sparsemux_9_2_1_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (1 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (0 downto 0);
        din1 : IN STD_LOGIC_VECTOR (0 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        din3 : IN STD_LOGIC_VECTOR (0 downto 0);
        def : IN STD_LOGIC_VECTOR (0 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component bnn_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_9_2_1_1_1_U407 : component bnn_sparsemux_9_2_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 1,
        CASE1 => "01",
        din1_WIDTH => 1,
        CASE2 => "10",
        din2_WIDTH => 1,
        CASE3 => "11",
        din3_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => l2_bits_reload,
        din1 => l2_bits_16_reload,
        din2 => l2_bits_32_reload,
        din3 => l2_bits_48_reload,
        def => word_fu_632_p9,
        sel => trunc_ln26_fu_628_p1,
        dout => word_fu_632_p11);

    sparsemux_9_2_1_1_1_U408 : component bnn_sparsemux_9_2_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 1,
        CASE1 => "01",
        din1_WIDTH => 1,
        CASE2 => "10",
        din2_WIDTH => 1,
        CASE3 => "11",
        din3_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => l2_bits_1_reload,
        din1 => l2_bits_17_reload,
        din2 => l2_bits_33_reload,
        din3 => l2_bits_49_reload,
        def => tmp_s_fu_656_p9,
        sel => trunc_ln26_fu_628_p1,
        dout => tmp_s_fu_656_p11);

    sparsemux_9_2_1_1_1_U409 : component bnn_sparsemux_9_2_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 1,
        CASE1 => "01",
        din1_WIDTH => 1,
        CASE2 => "10",
        din2_WIDTH => 1,
        CASE3 => "11",
        din3_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => l2_bits_2_reload,
        din1 => l2_bits_18_reload,
        din2 => l2_bits_34_reload,
        din3 => l2_bits_50_reload,
        def => tmp_1_fu_680_p9,
        sel => trunc_ln26_fu_628_p1,
        dout => tmp_1_fu_680_p11);

    sparsemux_9_2_1_1_1_U410 : component bnn_sparsemux_9_2_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 1,
        CASE1 => "01",
        din1_WIDTH => 1,
        CASE2 => "10",
        din2_WIDTH => 1,
        CASE3 => "11",
        din3_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => l2_bits_3_reload,
        din1 => l2_bits_19_reload,
        din2 => l2_bits_35_reload,
        din3 => l2_bits_51_reload,
        def => tmp_2_fu_704_p9,
        sel => trunc_ln26_fu_628_p1,
        dout => tmp_2_fu_704_p11);

    sparsemux_9_2_1_1_1_U411 : component bnn_sparsemux_9_2_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 1,
        CASE1 => "01",
        din1_WIDTH => 1,
        CASE2 => "10",
        din2_WIDTH => 1,
        CASE3 => "11",
        din3_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => l2_bits_4_reload,
        din1 => l2_bits_20_reload,
        din2 => l2_bits_36_reload,
        din3 => l2_bits_52_reload,
        def => tmp_3_fu_728_p9,
        sel => trunc_ln26_fu_628_p1,
        dout => tmp_3_fu_728_p11);

    sparsemux_9_2_1_1_1_U412 : component bnn_sparsemux_9_2_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 1,
        CASE1 => "01",
        din1_WIDTH => 1,
        CASE2 => "10",
        din2_WIDTH => 1,
        CASE3 => "11",
        din3_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => l2_bits_5_reload,
        din1 => l2_bits_21_reload,
        din2 => l2_bits_37_reload,
        din3 => l2_bits_53_reload,
        def => tmp_4_fu_752_p9,
        sel => trunc_ln26_fu_628_p1,
        dout => tmp_4_fu_752_p11);

    sparsemux_9_2_1_1_1_U413 : component bnn_sparsemux_9_2_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 1,
        CASE1 => "01",
        din1_WIDTH => 1,
        CASE2 => "10",
        din2_WIDTH => 1,
        CASE3 => "11",
        din3_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => l2_bits_6_reload,
        din1 => l2_bits_22_reload,
        din2 => l2_bits_38_reload,
        din3 => l2_bits_54_reload,
        def => tmp_5_fu_776_p9,
        sel => trunc_ln26_fu_628_p1,
        dout => tmp_5_fu_776_p11);

    sparsemux_9_2_1_1_1_U414 : component bnn_sparsemux_9_2_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 1,
        CASE1 => "01",
        din1_WIDTH => 1,
        CASE2 => "10",
        din2_WIDTH => 1,
        CASE3 => "11",
        din3_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => l2_bits_7_reload,
        din1 => l2_bits_23_reload,
        din2 => l2_bits_39_reload,
        din3 => l2_bits_55_reload,
        def => tmp_6_fu_800_p9,
        sel => trunc_ln26_fu_628_p1,
        dout => tmp_6_fu_800_p11);

    sparsemux_9_2_1_1_1_U415 : component bnn_sparsemux_9_2_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 1,
        CASE1 => "01",
        din1_WIDTH => 1,
        CASE2 => "10",
        din2_WIDTH => 1,
        CASE3 => "11",
        din3_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => l2_bits_8_reload,
        din1 => l2_bits_24_reload,
        din2 => l2_bits_40_reload,
        din3 => l2_bits_56_reload,
        def => tmp_7_fu_824_p9,
        sel => trunc_ln26_fu_628_p1,
        dout => tmp_7_fu_824_p11);

    sparsemux_9_2_1_1_1_U416 : component bnn_sparsemux_9_2_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 1,
        CASE1 => "01",
        din1_WIDTH => 1,
        CASE2 => "10",
        din2_WIDTH => 1,
        CASE3 => "11",
        din3_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => l2_bits_9_reload,
        din1 => l2_bits_25_reload,
        din2 => l2_bits_41_reload,
        din3 => l2_bits_57_reload,
        def => tmp_8_fu_848_p9,
        sel => trunc_ln26_fu_628_p1,
        dout => tmp_8_fu_848_p11);

    sparsemux_9_2_1_1_1_U417 : component bnn_sparsemux_9_2_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 1,
        CASE1 => "01",
        din1_WIDTH => 1,
        CASE2 => "10",
        din2_WIDTH => 1,
        CASE3 => "11",
        din3_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => l2_bits_10_reload,
        din1 => l2_bits_26_reload,
        din2 => l2_bits_42_reload,
        din3 => l2_bits_58_reload,
        def => tmp_9_fu_872_p9,
        sel => trunc_ln26_fu_628_p1,
        dout => tmp_9_fu_872_p11);

    sparsemux_9_2_1_1_1_U418 : component bnn_sparsemux_9_2_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 1,
        CASE1 => "01",
        din1_WIDTH => 1,
        CASE2 => "10",
        din2_WIDTH => 1,
        CASE3 => "11",
        din3_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => l2_bits_11_reload,
        din1 => l2_bits_27_reload,
        din2 => l2_bits_43_reload,
        din3 => l2_bits_59_reload,
        def => tmp_10_fu_896_p9,
        sel => trunc_ln26_fu_628_p1,
        dout => tmp_10_fu_896_p11);

    sparsemux_9_2_1_1_1_U419 : component bnn_sparsemux_9_2_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 1,
        CASE1 => "01",
        din1_WIDTH => 1,
        CASE2 => "10",
        din2_WIDTH => 1,
        CASE3 => "11",
        din3_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => l2_bits_12_reload,
        din1 => l2_bits_28_reload,
        din2 => l2_bits_44_reload,
        din3 => l2_bits_60_reload,
        def => tmp_11_fu_920_p9,
        sel => trunc_ln26_fu_628_p1,
        dout => tmp_11_fu_920_p11);

    sparsemux_9_2_1_1_1_U420 : component bnn_sparsemux_9_2_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 1,
        CASE1 => "01",
        din1_WIDTH => 1,
        CASE2 => "10",
        din2_WIDTH => 1,
        CASE3 => "11",
        din3_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => l2_bits_13_reload,
        din1 => l2_bits_29_reload,
        din2 => l2_bits_45_reload,
        din3 => l2_bits_61_reload,
        def => tmp_12_fu_944_p9,
        sel => trunc_ln26_fu_628_p1,
        dout => tmp_12_fu_944_p11);

    sparsemux_9_2_1_1_1_U421 : component bnn_sparsemux_9_2_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 1,
        CASE1 => "01",
        din1_WIDTH => 1,
        CASE2 => "10",
        din2_WIDTH => 1,
        CASE3 => "11",
        din3_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => l2_bits_14_reload,
        din1 => l2_bits_30_reload,
        din2 => l2_bits_46_reload,
        din3 => l2_bits_62_reload,
        def => tmp_13_fu_968_p9,
        sel => trunc_ln26_fu_628_p1,
        dout => tmp_13_fu_968_p11);

    sparsemux_9_2_1_1_1_U422 : component bnn_sparsemux_9_2_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 1,
        CASE1 => "01",
        din1_WIDTH => 1,
        CASE2 => "10",
        din2_WIDTH => 1,
        CASE3 => "11",
        din3_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => l2_bits_15_reload,
        din1 => l2_bits_31_reload,
        din2 => l2_bits_47_reload,
        din3 => l2_bits_63_reload,
        def => tmp_14_fu_992_p9,
        sel => trunc_ln26_fu_628_p1,
        dout => tmp_14_fu_992_p11);

    flow_control_loop_pipe_sequential_init_U : component bnn_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    w_fu_176_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((icmp_ln26_fu_616_p2 = ap_const_lv1_0)) then 
                    w_fu_176 <= add_ln26_fu_622_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    w_fu_176 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln26_fu_616_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln26_fu_628_p1 = ap_const_lv2_0))) then
                p_0_0271104_fu_180 <= word_2_fu_1016_p17;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln26_fu_616_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln26_fu_628_p1 = ap_const_lv2_1))) then
                p_0_0271_1106_fu_184 <= word_2_fu_1016_p17;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln26_fu_616_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln26_fu_628_p1 = ap_const_lv2_2))) then
                p_0_0271_2108_fu_188 <= word_2_fu_1016_p17;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln26_fu_616_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln26_fu_628_p1 = ap_const_lv2_3))) then
                p_0_0271_3110_fu_192 <= word_2_fu_1016_p17;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln26_fu_622_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_w_1) + unsigned(ap_const_lv3_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln26_fu_616_p2)
    begin
        if (((icmp_ln26_fu_616_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_w_1_assign_proc : process(ap_CS_fsm_state1, w_fu_176, ap_loop_init)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_w_1 <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_w_1 <= w_fu_176;
        end if; 
    end process;

    icmp_ln26_fu_616_p2 <= "1" when (ap_sig_allocacmp_w_1 = ap_const_lv3_4) else "0";
    p_0_0271104_out <= p_0_0271104_fu_180;

    p_0_0271104_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln26_fu_616_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln26_fu_616_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_0_0271104_out_ap_vld <= ap_const_logic_1;
        else 
            p_0_0271104_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_0_0271_1106_out <= p_0_0271_1106_fu_184;

    p_0_0271_1106_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln26_fu_616_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln26_fu_616_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_0_0271_1106_out_ap_vld <= ap_const_logic_1;
        else 
            p_0_0271_1106_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_0_0271_2108_out <= p_0_0271_2108_fu_188;

    p_0_0271_2108_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln26_fu_616_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln26_fu_616_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_0_0271_2108_out_ap_vld <= ap_const_logic_1;
        else 
            p_0_0271_2108_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_0_0271_3110_out <= p_0_0271_3110_fu_192;

    p_0_0271_3110_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln26_fu_616_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln26_fu_616_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_0_0271_3110_out_ap_vld <= ap_const_logic_1;
        else 
            p_0_0271_3110_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp_10_fu_896_p9 <= "X";
    tmp_11_fu_920_p9 <= "X";
    tmp_12_fu_944_p9 <= "X";
    tmp_13_fu_968_p9 <= "X";
    tmp_14_fu_992_p9 <= "X";
    tmp_1_fu_680_p9 <= "X";
    tmp_2_fu_704_p9 <= "X";
    tmp_3_fu_728_p9 <= "X";
    tmp_4_fu_752_p9 <= "X";
    tmp_5_fu_776_p9 <= "X";
    tmp_6_fu_800_p9 <= "X";
    tmp_7_fu_824_p9 <= "X";
    tmp_8_fu_848_p9 <= "X";
    tmp_9_fu_872_p9 <= "X";
    tmp_s_fu_656_p9 <= "X";
    trunc_ln26_fu_628_p1 <= ap_sig_allocacmp_w_1(2 - 1 downto 0);
    word_2_fu_1016_p17 <= (((((((((((((((word_fu_632_p11 & tmp_s_fu_656_p11) & tmp_1_fu_680_p11) & tmp_2_fu_704_p11) & tmp_3_fu_728_p11) & tmp_4_fu_752_p11) & tmp_5_fu_776_p11) & tmp_6_fu_800_p11) & tmp_7_fu_824_p11) & tmp_8_fu_848_p11) & tmp_9_fu_872_p11) & tmp_10_fu_896_p11) & tmp_11_fu_920_p11) & tmp_12_fu_944_p11) & tmp_13_fu_968_p11) & tmp_14_fu_992_p11);
    word_fu_632_p9 <= "X";
end behav;
