-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bnn_bnn_Pipeline_VITIS_LOOP_108_2_VITIS_LOOP_50_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    l1_packed_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    l1_packed_ce0 : OUT STD_LOGIC;
    l1_packed_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    l2_bits_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    l2_bits_ce0 : OUT STD_LOGIC;
    l2_bits_we0 : OUT STD_LOGIC;
    l2_bits_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    l2_bits_1_ce0 : OUT STD_LOGIC;
    l2_bits_1_we0 : OUT STD_LOGIC;
    l2_bits_1_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    l2_bits_2_ce0 : OUT STD_LOGIC;
    l2_bits_2_we0 : OUT STD_LOGIC;
    l2_bits_2_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    l2_bits_3_ce0 : OUT STD_LOGIC;
    l2_bits_3_we0 : OUT STD_LOGIC;
    l2_bits_3_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_4_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    l2_bits_4_ce0 : OUT STD_LOGIC;
    l2_bits_4_we0 : OUT STD_LOGIC;
    l2_bits_4_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_5_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    l2_bits_5_ce0 : OUT STD_LOGIC;
    l2_bits_5_we0 : OUT STD_LOGIC;
    l2_bits_5_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_6_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    l2_bits_6_ce0 : OUT STD_LOGIC;
    l2_bits_6_we0 : OUT STD_LOGIC;
    l2_bits_6_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    l2_bits_7_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    l2_bits_7_ce0 : OUT STD_LOGIC;
    l2_bits_7_we0 : OUT STD_LOGIC;
    l2_bits_7_d0 : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of bnn_bnn_Pipeline_VITIS_LOOP_108_2_VITIS_LOOP_50_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv10_200 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv16_F : STD_LOGIC_VECTOR (15 downto 0) := "0000000000001111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv9_180 : STD_LOGIC_VECTOR (8 downto 0) := "110000000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln108_fu_347_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal w2_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal w2_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln50_fu_370_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln50_reg_1436 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln50_reg_1436_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln50_reg_1436_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln108_fu_376_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln108_reg_1441 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln108_fu_398_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln108_reg_1447 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln108_reg_1447_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln108_reg_1447_pp0_iter3_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln108_reg_1447_pp0_iter4_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln110_fu_402_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln110_reg_1451 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln50_2_fu_412_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln50_2_reg_1456 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln50_2_reg_1456_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln50_2_reg_1456_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln50_2_reg_1456_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal lshr_ln1_reg_1460 : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln1_reg_1460_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln1_reg_1460_pp0_iter3_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln1_reg_1460_pp0_iter4_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln56_17_fu_1219_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln56_17_reg_1475 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln56_20_fu_1245_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln56_20_reg_1480 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln56_24_fu_1271_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln56_24_reg_1485 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln56_27_fu_1297_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln56_27_reg_1490 : STD_LOGIC_VECTOR (2 downto 0);
    signal same_2_fu_1355_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal same_2_reg_1495 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln50_fu_445_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln53_fu_458_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln108_fu_1366_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal same_fu_178 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_loop_init : STD_LOGIC;
    signal w_fu_182 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln50_fu_406_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal n_1_fu_186 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal select_ln108_2_fu_390_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal indvar_flatten6_fu_190 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal add_ln108_fu_353_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_sig_allocacmp_indvar_flatten6_load : STD_LOGIC_VECTOR (9 downto 0);
    signal l1_packed_ce0_local : STD_LOGIC;
    signal w2_ce0_local : STD_LOGIC;
    signal l2_bits_6_we0_local : STD_LOGIC;
    signal icmp_ln115_fu_1390_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal l2_bits_6_ce0_local : STD_LOGIC;
    signal l2_bits_5_we0_local : STD_LOGIC;
    signal l2_bits_5_ce0_local : STD_LOGIC;
    signal l2_bits_4_we0_local : STD_LOGIC;
    signal l2_bits_4_ce0_local : STD_LOGIC;
    signal l2_bits_3_we0_local : STD_LOGIC;
    signal l2_bits_3_ce0_local : STD_LOGIC;
    signal l2_bits_2_we0_local : STD_LOGIC;
    signal l2_bits_2_ce0_local : STD_LOGIC;
    signal l2_bits_1_we0_local : STD_LOGIC;
    signal l2_bits_1_ce0_local : STD_LOGIC;
    signal l2_bits_we0_local : STD_LOGIC;
    signal l2_bits_ce0_local : STD_LOGIC;
    signal l2_bits_7_we0_local : STD_LOGIC;
    signal l2_bits_7_ce0_local : STD_LOGIC;
    signal add_ln108_1_fu_384_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln50_3_fu_449_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln2_fu_438_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln53_fu_452_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal bit_sel15_fu_467_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln55_111_fu_475_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln55_145_fu_481_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal bit_sel16_fu_493_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln55_112_fu_501_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln55_fu_463_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal bit_sel17_fu_519_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln55_113_fu_527_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln55_147_fu_533_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal bit_sel18_fu_549_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln55_114_fu_557_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln55_149_fu_563_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal bit_sel19_fu_579_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln55_115_fu_587_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln55_151_fu_593_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal bit_sel20_fu_609_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln55_116_fu_617_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln55_153_fu_623_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal bit_sel21_fu_639_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln55_117_fu_647_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln55_155_fu_653_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal bit_sel22_fu_669_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln55_118_fu_677_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln55_157_fu_683_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal bit_sel23_fu_699_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln55_119_fu_707_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln55_159_fu_713_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal bit_sel24_fu_729_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln55_120_fu_737_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln55_161_fu_743_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal bit_sel25_fu_759_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln55_121_fu_767_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln55_163_fu_773_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal bit_sel26_fu_789_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln55_122_fu_797_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln55_165_fu_803_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal bit_sel27_fu_819_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln55_123_fu_827_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln55_167_fu_833_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal bit_sel28_fu_849_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln55_124_fu_857_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln55_169_fu_863_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal bit_sel29_fu_879_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln55_125_fu_887_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln55_171_fu_893_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal xor_ln55_14_fu_485_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln55_173_fu_915_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln55_32_fu_909_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln55_172_fu_905_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal xor_ln55_30_fu_897_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln55_170_fu_875_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal xor_ln55_29_fu_867_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln55_168_fu_845_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal xor_ln55_28_fu_837_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln55_166_fu_815_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal xor_ln55_27_fu_807_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln55_164_fu_785_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal xor_ln55_26_fu_777_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln55_162_fu_755_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal xor_ln55_25_fu_747_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln55_160_fu_725_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal xor_ln55_24_fu_717_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln55_158_fu_695_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln55_23_fu_687_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln55_156_fu_665_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal xor_ln55_22_fu_657_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln55_154_fu_635_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal xor_ln55_21_fu_627_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln55_152_fu_605_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal xor_ln55_20_fu_597_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln55_150_fu_575_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal xor_ln55_19_fu_567_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln55_148_fu_545_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal xor_ln55_18_fu_537_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln55_146_fu_515_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal xor_ln55_17_fu_507_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal xor_ln11_28_fu_1009_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal xor_ln11_27_fu_1003_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal xor_ln11_26_fu_997_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal xor_ln11_25_fu_991_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal xor_ln11_24_fu_985_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal xor_ln11_23_fu_979_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal xor_ln11_22_fu_973_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln11_21_fu_967_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal xor_ln11_20_fu_961_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal xor_ln11_19_fu_955_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal xor_ln11_18_fu_949_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal xor_ln11_17_fu_943_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal xor_ln11_16_fu_937_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal xor_ln11_15_fu_931_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal xnor_fu_919_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_91_fu_1127_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_82_fu_1055_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_80_fu_1039_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_83_fu_1063_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_86_fu_1087_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_88_fu_1103_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_84_fu_1071_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_85_fu_1079_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_81_fu_1047_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_89_fu_1111_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_78_fu_1023_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_79_fu_1031_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_90_fu_1119_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_1015_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln11_fu_925_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_87_fu_1095_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln56_43_fu_1191_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln56_fu_1135_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln56_fu_1199_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln56_31_fu_1143_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln56_30_fu_1139_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln56_16_fu_1209_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln56_46_fu_1215_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln56_45_fu_1205_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln56_33_fu_1151_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln56_32_fu_1147_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln56_18_fu_1225_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln56_35_fu_1159_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln56_34_fu_1155_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln56_19_fu_1235_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln56_49_fu_1241_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln56_48_fu_1231_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln56_37_fu_1167_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln56_36_fu_1163_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln56_22_fu_1251_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln56_39_fu_1175_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln56_38_fu_1171_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln56_23_fu_1261_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln56_53_fu_1267_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln56_52_fu_1257_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln56_41_fu_1183_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln56_40_fu_1179_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln56_25_fu_1277_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln56_42_fu_1187_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln56_44_fu_1195_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln56_26_fu_1287_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln56_56_fu_1293_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln56_55_fu_1283_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln56_50_fu_1316_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln56_47_fu_1313_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln56_21_fu_1319_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln56_57_fu_1332_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln56_54_fu_1329_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln56_28_fu_1335_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln56_58_fu_1341_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln56_51_fu_1325_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln56_29_fu_1345_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln108_1_fu_1306_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln56_59_fu_1351_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln60_1_fu_1377_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal dot_fu_1384_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component bnn_bnn_Pipeline_VITIS_LOOP_108_2_VITIS_LOOP_50_1_w2_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component bnn_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    w2_U : component bnn_bnn_Pipeline_VITIS_LOOP_108_2_VITIS_LOOP_50_1_w2_ROM_AUTO_1R
    generic map (
        DataWidth => 16,
        AddressRange => 512,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => w2_address0,
        ce0 => w2_ce0_local,
        q0 => w2_q0);

    flow_control_loop_pipe_sequential_init_U : component bnn_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten6_fu_190_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln108_fu_347_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten6_fu_190 <= add_ln108_fu_353_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten6_fu_190 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;

    n_1_fu_186_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    n_1_fu_186 <= ap_const_lv7_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    n_1_fu_186 <= select_ln108_2_fu_390_p3;
                end if;
            end if; 
        end if;
    end process;

    same_fu_178_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    same_fu_178 <= ap_const_lv8_0;
                elsif ((ap_enable_reg_pp0_iter4 = ap_const_logic_1)) then 
                    same_fu_178 <= same_2_fu_1355_p2;
                end if;
            end if; 
        end if;
    end process;

    w_fu_182_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    w_fu_182 <= ap_const_lv4_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    w_fu_182 <= add_ln50_fu_406_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln56_17_reg_1475 <= add_ln56_17_fu_1219_p2;
                add_ln56_20_reg_1480 <= add_ln56_20_fu_1245_p2;
                add_ln56_24_reg_1485 <= add_ln56_24_fu_1271_p2;
                add_ln56_27_reg_1490 <= add_ln56_27_fu_1297_p2;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                icmp_ln50_2_reg_1456_pp0_iter2_reg <= icmp_ln50_2_reg_1456;
                icmp_ln50_2_reg_1456_pp0_iter3_reg <= icmp_ln50_2_reg_1456_pp0_iter2_reg;
                icmp_ln50_2_reg_1456_pp0_iter4_reg <= icmp_ln50_2_reg_1456_pp0_iter3_reg;
                icmp_ln50_reg_1436_pp0_iter2_reg <= icmp_ln50_reg_1436;
                icmp_ln50_reg_1436_pp0_iter3_reg <= icmp_ln50_reg_1436_pp0_iter2_reg;
                lshr_ln1_reg_1460_pp0_iter2_reg <= lshr_ln1_reg_1460;
                lshr_ln1_reg_1460_pp0_iter3_reg <= lshr_ln1_reg_1460_pp0_iter2_reg;
                lshr_ln1_reg_1460_pp0_iter4_reg <= lshr_ln1_reg_1460_pp0_iter3_reg;
                same_2_reg_1495 <= same_2_fu_1355_p2;
                trunc_ln108_reg_1447_pp0_iter2_reg <= trunc_ln108_reg_1447;
                trunc_ln108_reg_1447_pp0_iter3_reg <= trunc_ln108_reg_1447_pp0_iter2_reg;
                trunc_ln108_reg_1447_pp0_iter4_reg <= trunc_ln108_reg_1447_pp0_iter3_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln50_2_reg_1456 <= icmp_ln50_2_fu_412_p2;
                icmp_ln50_reg_1436 <= icmp_ln50_fu_370_p2;
                lshr_ln1_reg_1460 <= select_ln108_2_fu_390_p3(5 downto 3);
                select_ln108_reg_1441 <= select_ln108_fu_376_p3;
                trunc_ln108_reg_1447 <= trunc_ln108_fu_398_p1;
                trunc_ln110_reg_1451 <= trunc_ln110_fu_402_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln108_1_fu_384_p2 <= std_logic_vector(unsigned(n_1_fu_186) + unsigned(ap_const_lv7_1));
    add_ln108_fu_353_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten6_load) + unsigned(ap_const_lv10_1));
    add_ln50_fu_406_p2 <= std_logic_vector(unsigned(select_ln108_fu_376_p3) + unsigned(ap_const_lv4_1));
    add_ln53_fu_452_p2 <= std_logic_vector(unsigned(zext_ln50_3_fu_449_p1) + unsigned(shl_ln2_fu_438_p3));
    add_ln56_16_fu_1209_p2 <= std_logic_vector(unsigned(zext_ln56_31_fu_1143_p1) + unsigned(zext_ln56_30_fu_1139_p1));
    add_ln56_17_fu_1219_p2 <= std_logic_vector(unsigned(zext_ln56_46_fu_1215_p1) + unsigned(zext_ln56_45_fu_1205_p1));
    add_ln56_18_fu_1225_p2 <= std_logic_vector(unsigned(zext_ln56_33_fu_1151_p1) + unsigned(zext_ln56_32_fu_1147_p1));
    add_ln56_19_fu_1235_p2 <= std_logic_vector(unsigned(zext_ln56_35_fu_1159_p1) + unsigned(zext_ln56_34_fu_1155_p1));
    add_ln56_20_fu_1245_p2 <= std_logic_vector(unsigned(zext_ln56_49_fu_1241_p1) + unsigned(zext_ln56_48_fu_1231_p1));
    add_ln56_21_fu_1319_p2 <= std_logic_vector(unsigned(zext_ln56_50_fu_1316_p1) + unsigned(zext_ln56_47_fu_1313_p1));
    add_ln56_22_fu_1251_p2 <= std_logic_vector(unsigned(zext_ln56_37_fu_1167_p1) + unsigned(zext_ln56_36_fu_1163_p1));
    add_ln56_23_fu_1261_p2 <= std_logic_vector(unsigned(zext_ln56_39_fu_1175_p1) + unsigned(zext_ln56_38_fu_1171_p1));
    add_ln56_24_fu_1271_p2 <= std_logic_vector(unsigned(zext_ln56_53_fu_1267_p1) + unsigned(zext_ln56_52_fu_1257_p1));
    add_ln56_25_fu_1277_p2 <= std_logic_vector(unsigned(zext_ln56_41_fu_1183_p1) + unsigned(zext_ln56_40_fu_1179_p1));
    add_ln56_26_fu_1287_p2 <= std_logic_vector(unsigned(zext_ln56_42_fu_1187_p1) + unsigned(zext_ln56_44_fu_1195_p1));
    add_ln56_27_fu_1297_p2 <= std_logic_vector(unsigned(zext_ln56_56_fu_1293_p1) + unsigned(zext_ln56_55_fu_1283_p1));
    add_ln56_28_fu_1335_p2 <= std_logic_vector(unsigned(zext_ln56_57_fu_1332_p1) + unsigned(zext_ln56_54_fu_1329_p1));
    add_ln56_29_fu_1345_p2 <= std_logic_vector(unsigned(zext_ln56_58_fu_1341_p1) + unsigned(zext_ln56_51_fu_1325_p1));
    add_ln56_fu_1199_p2 <= std_logic_vector(unsigned(zext_ln56_43_fu_1191_p1) + unsigned(zext_ln56_fu_1135_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln108_fu_347_p2)
    begin
        if (((icmp_ln108_fu_347_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten6_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten6_fu_190)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten6_load <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_indvar_flatten6_load <= indvar_flatten6_fu_190;
        end if; 
    end process;

    bit_sel15_fu_467_p3 <= w2_q0(15 downto 15);
    bit_sel16_fu_493_p3 <= w2_q0(1 downto 1);
    bit_sel17_fu_519_p3 <= w2_q0(2 downto 2);
    bit_sel18_fu_549_p3 <= w2_q0(3 downto 3);
    bit_sel19_fu_579_p3 <= w2_q0(4 downto 4);
    bit_sel20_fu_609_p3 <= w2_q0(5 downto 5);
    bit_sel21_fu_639_p3 <= w2_q0(6 downto 6);
    bit_sel22_fu_669_p3 <= w2_q0(7 downto 7);
    bit_sel23_fu_699_p3 <= w2_q0(8 downto 8);
    bit_sel24_fu_729_p3 <= w2_q0(9 downto 9);
    bit_sel25_fu_759_p3 <= w2_q0(10 downto 10);
    bit_sel26_fu_789_p3 <= w2_q0(11 downto 11);
    bit_sel27_fu_819_p3 <= w2_q0(12 downto 12);
    bit_sel28_fu_849_p3 <= w2_q0(13 downto 13);
    bit_sel29_fu_879_p3 <= w2_q0(14 downto 14);
    dot_fu_1384_p2 <= std_logic_vector(unsigned(shl_ln60_1_fu_1377_p3) + unsigned(ap_const_lv9_180));
    icmp_ln108_fu_347_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten6_load = ap_const_lv10_200) else "0";
    icmp_ln115_fu_1390_p2 <= "1" when (signed(dot_fu_1384_p2) < signed(ap_const_lv9_1)) else "0";
    icmp_ln50_2_fu_412_p2 <= "1" when (add_ln50_fu_406_p2 = ap_const_lv4_8) else "0";
    icmp_ln50_fu_370_p2 <= "1" when (w_fu_182 = ap_const_lv4_8) else "0";
    l1_packed_address0 <= zext_ln50_fu_445_p1(3 - 1 downto 0);
    l1_packed_ce0 <= l1_packed_ce0_local;

    l1_packed_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            l1_packed_ce0_local <= ap_const_logic_1;
        else 
            l1_packed_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    l2_bits_1_address0 <= zext_ln108_fu_1366_p1(3 - 1 downto 0);
    l2_bits_1_ce0 <= l2_bits_1_ce0_local;

    l2_bits_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            l2_bits_1_ce0_local <= ap_const_logic_1;
        else 
            l2_bits_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    l2_bits_1_d0 <= icmp_ln115_fu_1390_p2;
    l2_bits_1_we0 <= l2_bits_1_we0_local;

    l2_bits_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001, trunc_ln108_reg_1447_pp0_iter4_reg, icmp_ln50_2_reg_1456_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln50_2_reg_1456_pp0_iter4_reg = ap_const_lv1_1) and (trunc_ln108_reg_1447_pp0_iter4_reg = ap_const_lv3_1))) then 
            l2_bits_1_we0_local <= ap_const_logic_1;
        else 
            l2_bits_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    l2_bits_2_address0 <= zext_ln108_fu_1366_p1(3 - 1 downto 0);
    l2_bits_2_ce0 <= l2_bits_2_ce0_local;

    l2_bits_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            l2_bits_2_ce0_local <= ap_const_logic_1;
        else 
            l2_bits_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    l2_bits_2_d0 <= icmp_ln115_fu_1390_p2;
    l2_bits_2_we0 <= l2_bits_2_we0_local;

    l2_bits_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001, trunc_ln108_reg_1447_pp0_iter4_reg, icmp_ln50_2_reg_1456_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln50_2_reg_1456_pp0_iter4_reg = ap_const_lv1_1) and (trunc_ln108_reg_1447_pp0_iter4_reg = ap_const_lv3_2))) then 
            l2_bits_2_we0_local <= ap_const_logic_1;
        else 
            l2_bits_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    l2_bits_3_address0 <= zext_ln108_fu_1366_p1(3 - 1 downto 0);
    l2_bits_3_ce0 <= l2_bits_3_ce0_local;

    l2_bits_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            l2_bits_3_ce0_local <= ap_const_logic_1;
        else 
            l2_bits_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    l2_bits_3_d0 <= icmp_ln115_fu_1390_p2;
    l2_bits_3_we0 <= l2_bits_3_we0_local;

    l2_bits_3_we0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001, trunc_ln108_reg_1447_pp0_iter4_reg, icmp_ln50_2_reg_1456_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln50_2_reg_1456_pp0_iter4_reg = ap_const_lv1_1) and (trunc_ln108_reg_1447_pp0_iter4_reg = ap_const_lv3_3))) then 
            l2_bits_3_we0_local <= ap_const_logic_1;
        else 
            l2_bits_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    l2_bits_4_address0 <= zext_ln108_fu_1366_p1(3 - 1 downto 0);
    l2_bits_4_ce0 <= l2_bits_4_ce0_local;

    l2_bits_4_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            l2_bits_4_ce0_local <= ap_const_logic_1;
        else 
            l2_bits_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    l2_bits_4_d0 <= icmp_ln115_fu_1390_p2;
    l2_bits_4_we0 <= l2_bits_4_we0_local;

    l2_bits_4_we0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001, trunc_ln108_reg_1447_pp0_iter4_reg, icmp_ln50_2_reg_1456_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln50_2_reg_1456_pp0_iter4_reg = ap_const_lv1_1) and (trunc_ln108_reg_1447_pp0_iter4_reg = ap_const_lv3_4))) then 
            l2_bits_4_we0_local <= ap_const_logic_1;
        else 
            l2_bits_4_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    l2_bits_5_address0 <= zext_ln108_fu_1366_p1(3 - 1 downto 0);
    l2_bits_5_ce0 <= l2_bits_5_ce0_local;

    l2_bits_5_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            l2_bits_5_ce0_local <= ap_const_logic_1;
        else 
            l2_bits_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    l2_bits_5_d0 <= icmp_ln115_fu_1390_p2;
    l2_bits_5_we0 <= l2_bits_5_we0_local;

    l2_bits_5_we0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001, trunc_ln108_reg_1447_pp0_iter4_reg, icmp_ln50_2_reg_1456_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln50_2_reg_1456_pp0_iter4_reg = ap_const_lv1_1) and (trunc_ln108_reg_1447_pp0_iter4_reg = ap_const_lv3_5))) then 
            l2_bits_5_we0_local <= ap_const_logic_1;
        else 
            l2_bits_5_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    l2_bits_6_address0 <= zext_ln108_fu_1366_p1(3 - 1 downto 0);
    l2_bits_6_ce0 <= l2_bits_6_ce0_local;

    l2_bits_6_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            l2_bits_6_ce0_local <= ap_const_logic_1;
        else 
            l2_bits_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    l2_bits_6_d0 <= icmp_ln115_fu_1390_p2;
    l2_bits_6_we0 <= l2_bits_6_we0_local;

    l2_bits_6_we0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001, trunc_ln108_reg_1447_pp0_iter4_reg, icmp_ln50_2_reg_1456_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln50_2_reg_1456_pp0_iter4_reg = ap_const_lv1_1) and (trunc_ln108_reg_1447_pp0_iter4_reg = ap_const_lv3_6))) then 
            l2_bits_6_we0_local <= ap_const_logic_1;
        else 
            l2_bits_6_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    l2_bits_7_address0 <= zext_ln108_fu_1366_p1(3 - 1 downto 0);
    l2_bits_7_ce0 <= l2_bits_7_ce0_local;

    l2_bits_7_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            l2_bits_7_ce0_local <= ap_const_logic_1;
        else 
            l2_bits_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    l2_bits_7_d0 <= icmp_ln115_fu_1390_p2;
    l2_bits_7_we0 <= l2_bits_7_we0_local;

    l2_bits_7_we0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001, trunc_ln108_reg_1447_pp0_iter4_reg, icmp_ln50_2_reg_1456_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln50_2_reg_1456_pp0_iter4_reg = ap_const_lv1_1) and (trunc_ln108_reg_1447_pp0_iter4_reg = ap_const_lv3_7))) then 
            l2_bits_7_we0_local <= ap_const_logic_1;
        else 
            l2_bits_7_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    l2_bits_address0 <= zext_ln108_fu_1366_p1(3 - 1 downto 0);
    l2_bits_ce0 <= l2_bits_ce0_local;

    l2_bits_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            l2_bits_ce0_local <= ap_const_logic_1;
        else 
            l2_bits_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    l2_bits_d0 <= icmp_ln115_fu_1390_p2;
    l2_bits_we0 <= l2_bits_we0_local;

    l2_bits_we0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001, trunc_ln108_reg_1447_pp0_iter4_reg, icmp_ln50_2_reg_1456_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln50_2_reg_1456_pp0_iter4_reg = ap_const_lv1_1) and (trunc_ln108_reg_1447_pp0_iter4_reg = ap_const_lv3_0))) then 
            l2_bits_we0_local <= ap_const_logic_1;
        else 
            l2_bits_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    same_2_fu_1355_p2 <= std_logic_vector(unsigned(select_ln108_1_fu_1306_p3) + unsigned(zext_ln56_59_fu_1351_p1));
    select_ln108_1_fu_1306_p3 <= 
        ap_const_lv8_0 when (icmp_ln50_reg_1436_pp0_iter3_reg(0) = '1') else 
        same_fu_178;
    select_ln108_2_fu_390_p3 <= 
        add_ln108_1_fu_384_p2 when (icmp_ln50_fu_370_p2(0) = '1') else 
        n_1_fu_186;
    select_ln108_fu_376_p3 <= 
        ap_const_lv4_0 when (icmp_ln50_fu_370_p2(0) = '1') else 
        w_fu_182;
    shl_ln2_fu_438_p3 <= (trunc_ln110_reg_1451 & ap_const_lv3_0);
    shl_ln60_1_fu_1377_p3 <= (same_2_reg_1495 & ap_const_lv1_0);
    tmp_78_fu_1023_p3 <= xor_ln11_27_fu_1003_p2(2 downto 2);
    tmp_79_fu_1031_p3 <= xor_ln11_26_fu_997_p2(3 downto 3);
    tmp_80_fu_1039_p3 <= xor_ln11_25_fu_991_p2(4 downto 4);
    tmp_81_fu_1047_p3 <= xor_ln11_24_fu_985_p2(5 downto 5);
    tmp_82_fu_1055_p3 <= xor_ln11_23_fu_979_p2(6 downto 6);
    tmp_83_fu_1063_p3 <= xor_ln11_22_fu_973_p2(7 downto 7);
    tmp_84_fu_1071_p3 <= xor_ln11_21_fu_967_p2(8 downto 8);
    tmp_85_fu_1079_p3 <= xor_ln11_20_fu_961_p2(9 downto 9);
    tmp_86_fu_1087_p3 <= xor_ln11_19_fu_955_p2(10 downto 10);
    tmp_87_fu_1095_p3 <= xor_ln11_18_fu_949_p2(11 downto 11);
    tmp_88_fu_1103_p3 <= xor_ln11_17_fu_943_p2(12 downto 12);
    tmp_89_fu_1111_p3 <= xor_ln11_16_fu_937_p2(13 downto 13);
    tmp_90_fu_1119_p3 <= xor_ln11_15_fu_931_p2(14 downto 14);
    tmp_91_fu_1127_p3 <= xnor_fu_919_p2(15 downto 15);
    tmp_fu_1015_p3 <= xor_ln11_28_fu_1009_p2(1 downto 1);
    trunc_ln108_fu_398_p1 <= select_ln108_2_fu_390_p3(3 - 1 downto 0);
    trunc_ln110_fu_402_p1 <= select_ln108_2_fu_390_p3(6 - 1 downto 0);
    trunc_ln55_145_fu_481_p1 <= w2_q0(15 - 1 downto 0);
    trunc_ln55_146_fu_515_p1 <= l1_packed_q0(2 - 1 downto 0);
    trunc_ln55_147_fu_533_p1 <= w2_q0(2 - 1 downto 0);
    trunc_ln55_148_fu_545_p1 <= l1_packed_q0(3 - 1 downto 0);
    trunc_ln55_149_fu_563_p1 <= w2_q0(3 - 1 downto 0);
    trunc_ln55_150_fu_575_p1 <= l1_packed_q0(4 - 1 downto 0);
    trunc_ln55_151_fu_593_p1 <= w2_q0(4 - 1 downto 0);
    trunc_ln55_152_fu_605_p1 <= l1_packed_q0(5 - 1 downto 0);
    trunc_ln55_153_fu_623_p1 <= w2_q0(5 - 1 downto 0);
    trunc_ln55_154_fu_635_p1 <= l1_packed_q0(6 - 1 downto 0);
    trunc_ln55_155_fu_653_p1 <= w2_q0(6 - 1 downto 0);
    trunc_ln55_156_fu_665_p1 <= l1_packed_q0(7 - 1 downto 0);
    trunc_ln55_157_fu_683_p1 <= w2_q0(7 - 1 downto 0);
    trunc_ln55_158_fu_695_p1 <= l1_packed_q0(8 - 1 downto 0);
    trunc_ln55_159_fu_713_p1 <= w2_q0(8 - 1 downto 0);
    trunc_ln55_160_fu_725_p1 <= l1_packed_q0(9 - 1 downto 0);
    trunc_ln55_161_fu_743_p1 <= w2_q0(9 - 1 downto 0);
    trunc_ln55_162_fu_755_p1 <= l1_packed_q0(10 - 1 downto 0);
    trunc_ln55_163_fu_773_p1 <= w2_q0(10 - 1 downto 0);
    trunc_ln55_164_fu_785_p1 <= l1_packed_q0(11 - 1 downto 0);
    trunc_ln55_165_fu_803_p1 <= w2_q0(11 - 1 downto 0);
    trunc_ln55_166_fu_815_p1 <= l1_packed_q0(12 - 1 downto 0);
    trunc_ln55_167_fu_833_p1 <= w2_q0(12 - 1 downto 0);
    trunc_ln55_168_fu_845_p1 <= l1_packed_q0(13 - 1 downto 0);
    trunc_ln55_169_fu_863_p1 <= w2_q0(13 - 1 downto 0);
    trunc_ln55_170_fu_875_p1 <= l1_packed_q0(14 - 1 downto 0);
    trunc_ln55_171_fu_893_p1 <= w2_q0(14 - 1 downto 0);
    trunc_ln55_172_fu_905_p1 <= l1_packed_q0(15 - 1 downto 0);
    trunc_ln55_173_fu_915_p1 <= l1_packed_q0(1 - 1 downto 0);
    trunc_ln55_fu_463_p1 <= w2_q0(1 - 1 downto 0);
    w2_address0 <= zext_ln53_fu_458_p1(9 - 1 downto 0);

    w2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            w2_ce0_local <= ap_const_logic_1;
        else 
            w2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    xnor_fu_919_p2 <= (xor_ln55_14_fu_485_p3 xor l1_packed_q0);
    xor_ln11_15_fu_931_p2 <= (xor_ln55_30_fu_897_p3 xor trunc_ln55_172_fu_905_p1);
    xor_ln11_16_fu_937_p2 <= (xor_ln55_29_fu_867_p3 xor trunc_ln55_170_fu_875_p1);
    xor_ln11_17_fu_943_p2 <= (xor_ln55_28_fu_837_p3 xor trunc_ln55_168_fu_845_p1);
    xor_ln11_18_fu_949_p2 <= (xor_ln55_27_fu_807_p3 xor trunc_ln55_166_fu_815_p1);
    xor_ln11_19_fu_955_p2 <= (xor_ln55_26_fu_777_p3 xor trunc_ln55_164_fu_785_p1);
    xor_ln11_20_fu_961_p2 <= (xor_ln55_25_fu_747_p3 xor trunc_ln55_162_fu_755_p1);
    xor_ln11_21_fu_967_p2 <= (xor_ln55_24_fu_717_p3 xor trunc_ln55_160_fu_725_p1);
    xor_ln11_22_fu_973_p2 <= (xor_ln55_23_fu_687_p3 xor trunc_ln55_158_fu_695_p1);
    xor_ln11_23_fu_979_p2 <= (xor_ln55_22_fu_657_p3 xor trunc_ln55_156_fu_665_p1);
    xor_ln11_24_fu_985_p2 <= (xor_ln55_21_fu_627_p3 xor trunc_ln55_154_fu_635_p1);
    xor_ln11_25_fu_991_p2 <= (xor_ln55_20_fu_597_p3 xor trunc_ln55_152_fu_605_p1);
    xor_ln11_26_fu_997_p2 <= (xor_ln55_19_fu_567_p3 xor trunc_ln55_150_fu_575_p1);
    xor_ln11_27_fu_1003_p2 <= (xor_ln55_18_fu_537_p3 xor trunc_ln55_148_fu_545_p1);
    xor_ln11_28_fu_1009_p2 <= (xor_ln55_17_fu_507_p3 xor trunc_ln55_146_fu_515_p1);
    xor_ln11_fu_925_p2 <= (xor_ln55_32_fu_909_p2 xor trunc_ln55_173_fu_915_p1);
    xor_ln55_111_fu_475_p2 <= (bit_sel15_fu_467_p3 xor ap_const_lv1_1);
    xor_ln55_112_fu_501_p2 <= (bit_sel16_fu_493_p3 xor ap_const_lv1_1);
    xor_ln55_113_fu_527_p2 <= (bit_sel17_fu_519_p3 xor ap_const_lv1_1);
    xor_ln55_114_fu_557_p2 <= (bit_sel18_fu_549_p3 xor ap_const_lv1_1);
    xor_ln55_115_fu_587_p2 <= (bit_sel19_fu_579_p3 xor ap_const_lv1_1);
    xor_ln55_116_fu_617_p2 <= (bit_sel20_fu_609_p3 xor ap_const_lv1_1);
    xor_ln55_117_fu_647_p2 <= (bit_sel21_fu_639_p3 xor ap_const_lv1_1);
    xor_ln55_118_fu_677_p2 <= (bit_sel22_fu_669_p3 xor ap_const_lv1_1);
    xor_ln55_119_fu_707_p2 <= (bit_sel23_fu_699_p3 xor ap_const_lv1_1);
    xor_ln55_120_fu_737_p2 <= (bit_sel24_fu_729_p3 xor ap_const_lv1_1);
    xor_ln55_121_fu_767_p2 <= (bit_sel25_fu_759_p3 xor ap_const_lv1_1);
    xor_ln55_122_fu_797_p2 <= (bit_sel26_fu_789_p3 xor ap_const_lv1_1);
    xor_ln55_123_fu_827_p2 <= (bit_sel27_fu_819_p3 xor ap_const_lv1_1);
    xor_ln55_124_fu_857_p2 <= (bit_sel28_fu_849_p3 xor ap_const_lv1_1);
    xor_ln55_125_fu_887_p2 <= (bit_sel29_fu_879_p3 xor ap_const_lv1_1);
    xor_ln55_14_fu_485_p3 <= (xor_ln55_111_fu_475_p2 & trunc_ln55_145_fu_481_p1);
    xor_ln55_17_fu_507_p3 <= (xor_ln55_112_fu_501_p2 & trunc_ln55_fu_463_p1);
    xor_ln55_18_fu_537_p3 <= (xor_ln55_113_fu_527_p2 & trunc_ln55_147_fu_533_p1);
    xor_ln55_19_fu_567_p3 <= (xor_ln55_114_fu_557_p2 & trunc_ln55_149_fu_563_p1);
    xor_ln55_20_fu_597_p3 <= (xor_ln55_115_fu_587_p2 & trunc_ln55_151_fu_593_p1);
    xor_ln55_21_fu_627_p3 <= (xor_ln55_116_fu_617_p2 & trunc_ln55_153_fu_623_p1);
    xor_ln55_22_fu_657_p3 <= (xor_ln55_117_fu_647_p2 & trunc_ln55_155_fu_653_p1);
    xor_ln55_23_fu_687_p3 <= (xor_ln55_118_fu_677_p2 & trunc_ln55_157_fu_683_p1);
    xor_ln55_24_fu_717_p3 <= (xor_ln55_119_fu_707_p2 & trunc_ln55_159_fu_713_p1);
    xor_ln55_25_fu_747_p3 <= (xor_ln55_120_fu_737_p2 & trunc_ln55_161_fu_743_p1);
    xor_ln55_26_fu_777_p3 <= (xor_ln55_121_fu_767_p2 & trunc_ln55_163_fu_773_p1);
    xor_ln55_27_fu_807_p3 <= (xor_ln55_122_fu_797_p2 & trunc_ln55_165_fu_803_p1);
    xor_ln55_28_fu_837_p3 <= (xor_ln55_123_fu_827_p2 & trunc_ln55_167_fu_833_p1);
    xor_ln55_29_fu_867_p3 <= (xor_ln55_124_fu_857_p2 & trunc_ln55_169_fu_863_p1);
    xor_ln55_30_fu_897_p3 <= (xor_ln55_125_fu_887_p2 & trunc_ln55_171_fu_893_p1);
    xor_ln55_32_fu_909_p2 <= (trunc_ln55_fu_463_p1 xor ap_const_lv1_1);
    zext_ln108_fu_1366_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln1_reg_1460_pp0_iter4_reg),64));
    zext_ln50_3_fu_449_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln108_reg_1441),9));
    zext_ln50_fu_445_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln108_reg_1441),64));
    zext_ln53_fu_458_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln53_fu_452_p2),64));
    zext_ln56_30_fu_1139_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_82_fu_1055_p3),2));
    zext_ln56_31_fu_1143_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_80_fu_1039_p3),2));
    zext_ln56_32_fu_1147_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_83_fu_1063_p3),2));
    zext_ln56_33_fu_1151_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_86_fu_1087_p3),2));
    zext_ln56_34_fu_1155_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_88_fu_1103_p3),2));
    zext_ln56_35_fu_1159_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_84_fu_1071_p3),2));
    zext_ln56_36_fu_1163_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_85_fu_1079_p3),2));
    zext_ln56_37_fu_1167_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_81_fu_1047_p3),2));
    zext_ln56_38_fu_1171_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_89_fu_1111_p3),2));
    zext_ln56_39_fu_1175_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_78_fu_1023_p3),2));
    zext_ln56_40_fu_1179_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_79_fu_1031_p3),2));
    zext_ln56_41_fu_1183_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_90_fu_1119_p3),2));
    zext_ln56_42_fu_1187_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_1015_p3),2));
    zext_ln56_43_fu_1191_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xor_ln11_fu_925_p2),2));
    zext_ln56_44_fu_1195_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_87_fu_1095_p3),2));
    zext_ln56_45_fu_1205_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln56_fu_1199_p2),3));
    zext_ln56_46_fu_1215_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln56_16_fu_1209_p2),3));
    zext_ln56_47_fu_1313_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln56_17_reg_1475),4));
    zext_ln56_48_fu_1231_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln56_18_fu_1225_p2),3));
    zext_ln56_49_fu_1241_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln56_19_fu_1235_p2),3));
    zext_ln56_50_fu_1316_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln56_20_reg_1480),4));
    zext_ln56_51_fu_1325_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln56_21_fu_1319_p2),5));
    zext_ln56_52_fu_1257_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln56_22_fu_1251_p2),3));
    zext_ln56_53_fu_1267_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln56_23_fu_1261_p2),3));
    zext_ln56_54_fu_1329_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln56_24_reg_1485),4));
    zext_ln56_55_fu_1283_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln56_25_fu_1277_p2),3));
    zext_ln56_56_fu_1293_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln56_26_fu_1287_p2),3));
    zext_ln56_57_fu_1332_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln56_27_reg_1490),4));
    zext_ln56_58_fu_1341_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln56_28_fu_1335_p2),5));
    zext_ln56_59_fu_1351_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln56_29_fu_1345_p2),8));
    zext_ln56_fu_1135_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_91_fu_1127_p3),2));
end behav;
