// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module dft_dft_Pipeline_COMPUTE_DFT_INNER_LOOP (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        output_real_din,
        output_real_full_n,
        output_real_write,
        output_imag_din,
        output_imag_full_n,
        output_imag_write,
        real_sample_address0,
        real_sample_ce0,
        real_sample_q0,
        imag_sample_address0,
        imag_sample_ce0,
        imag_sample_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 6'd1;
parameter    ap_ST_fsm_pp0_stage1 = 6'd2;
parameter    ap_ST_fsm_pp0_stage2 = 6'd4;
parameter    ap_ST_fsm_pp0_stage3 = 6'd8;
parameter    ap_ST_fsm_pp0_stage4 = 6'd16;
parameter    ap_ST_fsm_pp0_stage5 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] output_real_din;
input   output_real_full_n;
output   output_real_write;
output  [31:0] output_imag_din;
input   output_imag_full_n;
output   output_imag_write;
output  [9:0] real_sample_address0;
output   real_sample_ce0;
input  [31:0] real_sample_q0;
output  [9:0] imag_sample_address0;
output   imag_sample_ce0;
input  [31:0] imag_sample_q0;

reg ap_idle;
reg output_real_write;
reg output_imag_write;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln19_reg_348;
reg    ap_condition_exit_pp0_iter0_stage5;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [9:0] cos_coefficients_table_address0;
wire   [31:0] cos_coefficients_table_q0;
wire   [9:0] sin_coefficients_table_address0;
wire   [31:0] sin_coefficients_table_q0;
reg    output_real_blk_n;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_grp1;
reg   [0:0] icmp_ln23_1_reg_374;
reg   [0:0] icmp_ln23_1_reg_374_pp0_iter3_reg;
reg    ap_block_pp0_stage3_subdone_grp1_done_reg;
reg    ap_block_pp0_stage3_subdone_grp1;
reg    ap_block_pp0_stage3_subdone;
reg    output_imag_blk_n;
wire    ap_block_pp0_stage3_grp2;
reg    ap_block_pp0_stage3_subdone_grp2_done_reg;
reg    ap_block_pp0_stage3_subdone_grp2;
wire   [31:0] grp_fu_138_p2;
reg   [31:0] reg_146;
reg    ap_block_state22_pp0_stage3_iter3_grp2;
reg    ap_block_pp0_stage3_11001_grp2;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln19_fu_179_p2;
reg   [0:0] icmp_ln19_reg_348_pp0_iter1_reg;
reg   [0:0] icmp_ln19_reg_348_pp0_iter2_reg;
wire   [0:0] icmp_ln23_fu_194_p2;
reg   [0:0] icmp_ln23_reg_352;
reg   [0:0] icmp_ln23_reg_352_pp0_iter1_reg;
reg   [0:0] icmp_ln23_reg_352_pp0_iter2_reg;
wire  signed [9:0] trunc_ln24_1_fu_214_p1;
reg  signed [9:0] trunc_ln24_1_reg_359;
wire   [0:0] icmp_ln23_1_fu_224_p2;
reg   [0:0] icmp_ln23_1_reg_374_pp0_iter1_reg;
reg   [0:0] icmp_ln23_1_reg_374_pp0_iter2_reg;
wire   [9:0] idx_fu_260_p2;
reg   [9:0] idx_reg_378;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
reg   [31:0] real_sample_load_reg_383;
reg   [31:0] imag_sample_load_reg_388;
reg   [31:0] c_reg_403;
wire    ap_block_pp0_stage3_11001_grp0;
reg    ap_block_pp0_stage3_subdone_grp0_done_reg;
wire    ap_block_pp0_stage3_subdone_grp0;
reg   [31:0] s_reg_408;
wire   [31:0] grp_fu_142_p2;
reg   [31:0] mul_reg_413;
reg   [31:0] mul1_reg_418;
reg   [31:0] mul2_reg_423;
reg   [31:0] mul3_reg_428;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_11001;
wire   [31:0] select_ln7_2_fu_278_p3;
reg   [31:0] select_ln7_2_reg_433;
reg   [31:0] sub_reg_438;
wire   [31:0] select_ln7_1_fu_288_p3;
reg   [31:0] select_ln7_1_reg_443;
reg   [31:0] temp_real_1_reg_448;
reg    ap_block_state22_pp0_stage3_iter3_grp1;
wire   [63:0] zext_ln23_fu_208_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln25_fu_270_p1;
wire    ap_block_pp0_stage2;
reg   [31:0] temp_real_fu_52;
reg   [31:0] ap_sig_allocacmp_temp_real_load;
wire    ap_block_pp0_stage1;
wire    ap_loop_init;
reg   [31:0] temp_imag_fu_56;
reg   [31:0] ap_sig_allocacmp_temp_imag_load;
wire    ap_block_pp0_stage3_grp0;
reg   [10:0] j_1_fu_60;
wire   [10:0] add_ln23_fu_218_p2;
reg   [10:0] ap_sig_allocacmp_j_1_load;
reg   [10:0] i_fu_64;
wire   [10:0] select_ln19_fu_249_p3;
reg   [20:0] indvar_flatten_fu_68;
wire   [20:0] add_ln19_fu_185_p2;
reg   [20:0] ap_sig_allocacmp_indvar_flatten_load;
reg    ap_block_pp0_stage3_01001_grp1;
reg    ap_block_pp0_stage3_11001_grp1;
reg    ap_block_pp0_stage3_01001_grp2;
reg    real_sample_ce0_local;
reg    imag_sample_ce0_local;
reg    cos_coefficients_table_ce0_local;
reg    sin_coefficients_table_ce0_local;
reg   [31:0] grp_fu_138_p0;
reg   [31:0] grp_fu_138_p1;
wire    ap_block_pp0_stage5;
wire    ap_block_pp0_stage4;
reg   [31:0] grp_fu_142_p0;
reg   [31:0] grp_fu_142_p1;
wire   [10:0] select_ln7_fu_200_p3;
wire   [10:0] add_ln19_1_fu_243_p2;
wire  signed [9:0] idx_fu_260_p1;
reg   [1:0] grp_fu_138_opcode;
wire    ap_block_pp0_stage5_00001;
wire    ap_block_pp0_stage2_00001;
wire    ap_block_pp0_stage4_00001;
reg    ap_block_pp0_stage3_00001_grp2;
reg    grp_fu_138_ce;
reg    ap_block_pp0_stage3_11001;
wire    ap_block_pp0_stage5_11001;
reg    grp_fu_142_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter2_stage3;
reg    ap_idle_pp0_0to1;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [5:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to3;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage3_subdone_grp1_done_reg = 1'b0;
#0 ap_block_pp0_stage3_subdone_grp2_done_reg = 1'b0;
#0 ap_block_pp0_stage3_subdone_grp0_done_reg = 1'b0;
#0 temp_real_fu_52 = 32'd0;
#0 temp_imag_fu_56 = 32'd0;
#0 j_1_fu_60 = 11'd0;
#0 i_fu_64 = 11'd0;
#0 indvar_flatten_fu_68 = 21'd0;
#0 ap_done_reg = 1'b0;
end

dft_dft_Pipeline_COMPUTE_DFT_INNER_LOOP_cos_coefficients_table_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
cos_coefficients_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(cos_coefficients_table_address0),
    .ce0(cos_coefficients_table_ce0_local),
    .q0(cos_coefficients_table_q0)
);

dft_dft_Pipeline_COMPUTE_DFT_INNER_LOOP_sin_coefficients_table_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
sin_coefficients_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sin_coefficients_table_address0),
    .ce0(sin_coefficients_table_ce0_local),
    .q0(sin_coefficients_table_q0)
);

dft_faddfsub_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
faddfsub_32ns_32ns_32_5_full_dsp_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_138_p0),
    .din1(grp_fu_138_p1),
    .opcode(grp_fu_138_opcode),
    .ce(grp_fu_138_ce),
    .dout(grp_fu_138_p2)
);

dft_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_142_p0),
    .din1(grp_fu_142_p1),
    .ce(grp_fu_142_ce),
    .dout(grp_fu_142_p2)
);

dft_mul_10s_10s_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 10 ))
mul_10s_10s_10_1_1_U7(
    .din0(trunc_ln24_1_reg_359),
    .din1(idx_fu_260_p1),
    .dout(idx_fu_260_p2)
);

dft_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage5),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage3_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage3)) begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_block_pp0_stage3_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage3_subdone_grp0)) begin
                ap_block_pp0_stage3_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage3_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage3)) begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_block_pp0_stage3_subdone_grp1_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage3_subdone_grp1)) begin
                ap_block_pp0_stage3_subdone_grp1_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage3_subdone_grp2_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage3)) begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_block_pp0_stage3_subdone_grp2_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage3_subdone_grp2)) begin
                ap_block_pp0_stage3_subdone_grp2_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage5)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to1 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter2_stage3))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to1 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter2_stage3))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_fu_64 <= 11'd0;
    end else if (((icmp_ln19_reg_348 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        i_fu_64 <= select_ln19_fu_249_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln19_fu_179_p2 == 1'd0))) begin
            indvar_flatten_fu_68 <= add_ln19_fu_185_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_68 <= 21'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln19_fu_179_p2 == 1'd0))) begin
            j_1_fu_60 <= add_ln23_fu_218_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_1_fu_60 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_imag_fu_56 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage3_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage3_11001_grp0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        temp_imag_fu_56 <= reg_146;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_real_fu_52 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        temp_real_fu_52 <= temp_real_1_reg_448;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage3_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        c_reg_403 <= cos_coefficients_table_q0;
        s_reg_408 <= sin_coefficients_table_q0;
        select_ln7_1_reg_443 <= select_ln7_1_fu_288_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln19_reg_348 <= icmp_ln19_fu_179_p2;
        icmp_ln19_reg_348_pp0_iter1_reg <= icmp_ln19_reg_348;
        icmp_ln19_reg_348_pp0_iter2_reg <= icmp_ln19_reg_348_pp0_iter1_reg;
        icmp_ln23_1_reg_374 <= icmp_ln23_1_fu_224_p2;
        icmp_ln23_1_reg_374_pp0_iter1_reg <= icmp_ln23_1_reg_374;
        icmp_ln23_1_reg_374_pp0_iter2_reg <= icmp_ln23_1_reg_374_pp0_iter1_reg;
        icmp_ln23_1_reg_374_pp0_iter3_reg <= icmp_ln23_1_reg_374_pp0_iter2_reg;
        icmp_ln23_reg_352 <= icmp_ln23_fu_194_p2;
        icmp_ln23_reg_352_pp0_iter1_reg <= icmp_ln23_reg_352;
        icmp_ln23_reg_352_pp0_iter2_reg <= icmp_ln23_reg_352_pp0_iter1_reg;
        trunc_ln24_1_reg_359 <= trunc_ln24_1_fu_214_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        idx_reg_378 <= idx_fu_260_p2;
        imag_sample_load_reg_388 <= imag_sample_q0;
        real_sample_load_reg_383 <= real_sample_q0;
        select_ln7_2_reg_433 <= select_ln7_2_fu_278_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mul1_reg_418 <= grp_fu_142_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage3_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        mul2_reg_423 <= grp_fu_142_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        mul3_reg_428 <= grp_fu_142_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        mul_reg_413 <= grp_fu_142_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage3_11001_grp2) & (1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        reg_146 <= grp_fu_138_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        sub_reg_438 <= grp_fu_138_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_real_1_reg_448 <= grp_fu_138_p2;
    end
end

always @ (*) begin
    if (((icmp_ln19_reg_348 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        ap_condition_exit_pp0_iter0_stage5 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (icmp_ln19_reg_348_pp0_iter2_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter2_stage3 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to3 = 1'b1;
    end else begin
        ap_idle_pp0_1to3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 21'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_68;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_1_load = 11'd0;
    end else begin
        ap_sig_allocacmp_j_1_load = j_1_fu_60;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_grp0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_sig_allocacmp_temp_imag_load = reg_146;
    end else begin
        ap_sig_allocacmp_temp_imag_load = temp_imag_fu_56;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_temp_real_load = temp_real_1_reg_448;
    end else begin
        ap_sig_allocacmp_temp_real_load = temp_real_fu_52;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        cos_coefficients_table_ce0_local = 1'b1;
    end else begin
        cos_coefficients_table_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage3_11001_grp2) & (1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        grp_fu_138_ce = 1'b1;
    end else begin
        grp_fu_138_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_00001_grp2) & (1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_138_opcode = 2'd1;
    end else if ((((1'b0 == ap_block_pp0_stage4_00001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage2_00001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage5_00001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        grp_fu_138_opcode = 2'd0;
    end else begin
        grp_fu_138_opcode = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_138_p0 = select_ln7_1_reg_443;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_138_p0 = select_ln7_2_reg_433;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_138_p0 = mul2_reg_423;
    end else if (((1'b0 == ap_block_pp0_stage3_grp2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_138_p0 = mul_reg_413;
    end else begin
        grp_fu_138_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_138_p1 = reg_146;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_138_p1 = sub_reg_438;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_138_p1 = mul3_reg_428;
    end else if (((1'b0 == ap_block_pp0_stage3_grp2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_138_p1 = mul1_reg_418;
    end else begin
        grp_fu_138_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage3_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        grp_fu_142_ce = 1'b1;
    end else begin
        grp_fu_142_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_142_p0 = imag_sample_load_reg_388;
    end else if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_142_p0 = real_sample_load_reg_383;
    end else begin
        grp_fu_142_p0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_142_p1 = s_reg_408;
    end else if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_142_p1 = c_reg_403;
    end else begin
        grp_fu_142_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        imag_sample_ce0_local = 1'b1;
    end else begin
        imag_sample_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg) & (1'b0 == ap_block_pp0_stage3_grp2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (icmp_ln23_1_reg_374_pp0_iter3_reg == 1'd1))) begin
        output_imag_blk_n = output_imag_full_n;
    end else begin
        output_imag_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_11001_grp2) & (1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (icmp_ln23_1_reg_374_pp0_iter3_reg == 1'd1))) begin
        output_imag_write = 1'b1;
    end else begin
        output_imag_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage3_grp1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (icmp_ln23_1_reg_374_pp0_iter3_reg == 1'd1))) begin
        output_real_blk_n = output_real_full_n;
    end else begin
        output_real_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_11001_grp1) & (1'b0 == ap_block_pp0_stage3_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (icmp_ln23_1_reg_374_pp0_iter3_reg == 1'd1))) begin
        output_real_write = 1'b1;
    end else begin
        output_real_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        real_sample_ce0_local = 1'b1;
    end else begin
        real_sample_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        sin_coefficients_table_ce0_local = 1'b1;
    end else begin
        sin_coefficients_table_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to3 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if (((ap_idle_pp0_0to1 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter2_stage3))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln19_1_fu_243_p2 = (i_fu_64 + 11'd1);

assign add_ln19_fu_185_p2 = (ap_sig_allocacmp_indvar_flatten_load + 21'd1);

assign add_ln23_fu_218_p2 = (select_ln7_fu_200_p3 + 11'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_00001_grp2 = ((1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state22_pp0_stage3_iter3_grp2));
end

always @ (*) begin
    ap_block_pp0_stage3_01001_grp1 = ((1'b0 == ap_block_pp0_stage3_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state22_pp0_stage3_iter3_grp1));
end

always @ (*) begin
    ap_block_pp0_stage3_01001_grp2 = ((1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state22_pp0_stage3_iter3_grp2));
end

always @ (*) begin
    ap_block_pp0_stage3_11001 = ((ap_enable_reg_pp0_iter3 == 1'b1) & (((1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg) & (1'b1 == ap_block_state22_pp0_stage3_iter3_grp2)) | ((1'b0 == ap_block_pp0_stage3_subdone_grp1_done_reg) & (1'b1 == ap_block_state22_pp0_stage3_iter3_grp1))));
end

assign ap_block_pp0_stage3_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_11001_grp1 = ((1'b0 == ap_block_pp0_stage3_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state22_pp0_stage3_iter3_grp1));
end

always @ (*) begin
    ap_block_pp0_stage3_11001_grp2 = ((1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state22_pp0_stage3_iter3_grp2));
end

assign ap_block_pp0_stage3_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_grp1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_subdone = ((ap_enable_reg_pp0_iter3 == 1'b1) & (((1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg) & (1'b1 == ap_block_state22_pp0_stage3_iter3_grp2)) | ((1'b0 == ap_block_pp0_stage3_subdone_grp1_done_reg) & (1'b1 == ap_block_state22_pp0_stage3_iter3_grp1))));
end

assign ap_block_pp0_stage3_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_subdone_grp1 = ((1'b0 == ap_block_pp0_stage3_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state22_pp0_stage3_iter3_grp1));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone_grp2 = ((1'b0 == ap_block_pp0_stage3_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state22_pp0_stage3_iter3_grp2));
end

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state22_pp0_stage3_iter3_grp1 = ((output_real_full_n == 1'b0) & (icmp_ln23_1_reg_374_pp0_iter3_reg == 1'd1));
end

always @ (*) begin
    ap_block_state22_pp0_stage3_iter3_grp2 = ((output_imag_full_n == 1'b0) & (icmp_ln23_1_reg_374_pp0_iter3_reg == 1'd1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage5;

assign ap_ready = ap_ready_sig;

assign cos_coefficients_table_address0 = zext_ln25_fu_270_p1;

assign icmp_ln19_fu_179_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 21'd1048576) ? 1'b1 : 1'b0);

assign icmp_ln23_1_fu_224_p2 = ((add_ln23_fu_218_p2 == 11'd1024) ? 1'b1 : 1'b0);

assign icmp_ln23_fu_194_p2 = ((ap_sig_allocacmp_j_1_load == 11'd1024) ? 1'b1 : 1'b0);

assign idx_fu_260_p1 = select_ln19_fu_249_p3[9:0];

assign imag_sample_address0 = zext_ln23_fu_208_p1;

assign imag_sample_ce0 = imag_sample_ce0_local;

assign output_imag_din = reg_146;

assign output_real_din = temp_real_1_reg_448;

assign real_sample_address0 = zext_ln23_fu_208_p1;

assign real_sample_ce0 = real_sample_ce0_local;

assign select_ln19_fu_249_p3 = ((icmp_ln23_reg_352[0:0] == 1'b1) ? add_ln19_1_fu_243_p2 : i_fu_64);

assign select_ln7_1_fu_288_p3 = ((icmp_ln23_reg_352_pp0_iter2_reg[0:0] == 1'b1) ? 32'd0 : ap_sig_allocacmp_temp_imag_load);

assign select_ln7_2_fu_278_p3 = ((icmp_ln23_reg_352_pp0_iter2_reg[0:0] == 1'b1) ? 32'd0 : ap_sig_allocacmp_temp_real_load);

assign select_ln7_fu_200_p3 = ((icmp_ln23_fu_194_p2[0:0] == 1'b1) ? 11'd0 : ap_sig_allocacmp_j_1_load);

assign sin_coefficients_table_address0 = zext_ln25_fu_270_p1;

assign trunc_ln24_1_fu_214_p1 = select_ln7_fu_200_p3[9:0];

assign zext_ln23_fu_208_p1 = select_ln7_fu_200_p3;

assign zext_ln25_fu_270_p1 = idx_reg_378;

endmodule //dft_dft_Pipeline_COMPUTE_DFT_INNER_LOOP
